"""Emit C++ syntax architecture descriptors from ``ir.syntax_ast``."""

from __future__ import annotations

from pathlib import Path

from base.utils import (
    file_stem_to_pascal_case,
    generated_at_comment,
    to_file_stem,
)
from code_gen.cpp_backend import CppDomain, cpp_value
from code_gen.database import CodegenDatabase
from ir.syntax_ast import (
    ModifierPresence,
    OperandLayoutKind,
    OperandPresence,
    OperandSyntaxShape,
    SyntaxInstructionDescriptor,
    SyntaxModifierDescriptor,
    SyntaxOperandLayoutDescriptor,
    SyntaxOperandSlotDescriptor,
    SyntaxVariantDescriptor,
    from_InstructionSpec,
)


def generate_syntax_descriptor_source(
    database: CodegenDatabase,
    *,
    output_path: Path,
) -> None:
    """Generate one private C++ source for syntax descriptor storage."""

    storage_definitions: list[str] = []
    getter_definitions: list[str] = []
    generated_types: set[str] = set()

    for instruction in database.instructions:
        descriptor = from_InstructionSpec(instruction)
        cpp_instruction_name = file_stem_to_pascal_case(descriptor.opcode)
        if cpp_instruction_name in generated_types:
            raise ValueError(
                "cannot generate multiple syntax descriptors for C++ "
                f"instruction type {cpp_instruction_name!r}"
            )

        generated_types.add(cpp_instruction_name)
        storage_definitions.append(_emit_instruction_descriptor_storage(descriptor))
        getter_definitions.append(_emit_instruction_descriptor_getter(descriptor))

    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include <ptx_frontend/resolved_ir/ptx_resolved_ir.hpp>

namespace ptx_frontend::resolved_ir {{

namespace {{

{"\n\n".join(storage_definitions)}

}}  // namespace

{"\n\n".join(getter_definitions)}

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def emit_check_end_instruction_descriptor_implementation(
    descriptor: SyntaxInstructionDescriptor,
) -> str:
    """Emit one ``<Opcode>::get_syntax_descriptor`` C++ implementation.

    The storage struct owns all ``std::array`` instances.  The final
    descriptor contains only ``std::span`` views into that static storage.
    Resolved-field bindings are emitted separately by the Resolved IR
    generator.  This storage contains source syntax constraints only.
    """

    return (
        f"{_emit_instruction_descriptor_storage(descriptor)}\n\n"
        f"{_emit_instruction_descriptor_getter(descriptor)}"
    )


def _emit_instruction_descriptor_storage(
    descriptor: SyntaxInstructionDescriptor,
) -> str:
    """Emit the anonymous-namespace storage for one instruction descriptor."""

    cpp_instruction_name = file_stem_to_pascal_case(descriptor.opcode)
    storage_name = f"{cpp_instruction_name}DescriptorStorage"
    variant_storage = "\n\n".join(
        _emit_variant_storage(variant) for variant in descriptor.variants
    )
    variants = ",\n".join(
        _emit_variant_descriptor(variant, descriptor.opcode)
        for variant in descriptor.variants
    )

    return f"""\
struct {storage_name} {{
{variant_storage}

  inline static constexpr std::array<check_end::SyntaxVariantDescriptor, {len(descriptor.variants)}>
      variants = {{
{variants}
      }};

  inline static constexpr check_end::SyntaxInstructionDescriptor descriptor{{
      .Opcode_name = {_cpp_string(descriptor.opcode)},
      .variants = variants,
  }};
}};
"""


def _emit_instruction_descriptor_getter(
    descriptor: SyntaxInstructionDescriptor,
) -> str:
    """Emit the public descriptor getter for one instruction."""

    cpp_instruction_name = file_stem_to_pascal_case(descriptor.opcode)
    storage_name = f"{cpp_instruction_name}DescriptorStorage"

    return f"""\
const check_end::SyntaxInstructionDescriptor&
{cpp_instruction_name}::get_syntax_descriptor() noexcept {{
  return {storage_name}::descriptor;
}}"""


def _emit_variant_storage(
    variant: SyntaxVariantDescriptor,
) -> str:
    name = to_file_stem(variant.variant_id)
    allowed_value_arrays = "\n\n".join(
        _emit_allowed_value_array(name, index, modifier)
        for index, modifier in enumerate(variant.modifiers)
        if modifier.allowed_spellings
    )
    modifiers = _emit_modifier_array(name, variant.modifiers)
    slot_arrays = "\n\n".join(
        _emit_operand_slot_array(name, index, layout)
        for index, layout in enumerate(variant.operand_layouts)
    )
    layouts = _emit_operand_layout_array(name, variant.operand_layouts)

    parts = [
        part
        for part in (allowed_value_arrays, modifiers, slot_arrays, layouts)
        if part
    ]
    return "\n\n".join(parts)


def _emit_allowed_value_array(
    variant_name: str,
    modifier_index: int,
    modifier: SyntaxModifierDescriptor,
) -> str:
    values = ", ".join(_cpp_string(value) for value in modifier.allowed_spellings)
    return f"""\
  inline static constexpr std::array<std::string_view, {len(modifier.allowed_spellings)}>
      {variant_name}_modifier_{modifier_index}_allowed_values = {{
          {values},
      }};"""


def _emit_modifier_array(
    variant_name: str,
    modifiers: tuple[SyntaxModifierDescriptor, ...],
) -> str:
    entries = ",\n".join(
        _emit_modifier_entry(variant_name, index, modifier)
        for index, modifier in enumerate(modifiers)
    )
    return f"""\
  inline static constexpr std::array<check_end::SyntaxModifierDescriptor, {len(modifiers)}>
      {variant_name}_modifiers = {{
{entries}
      }};"""


def _emit_modifier_entry(
    variant_name: str,
    modifier_index: int,
    modifier: SyntaxModifierDescriptor,
) -> str:
    allowed_values = (
        f"{variant_name}_modifier_{modifier_index}_allowed_values"
        if modifier.allowed_spellings
        else "{}"
    )
    return f"""\
          check_end::SyntaxModifierDescriptor{{
              .allowed_values = {allowed_values},
              .presence = {cpp_value(CppDomain.SYNTAX_MODIFIER_PRESENCE, modifier.presence.value)},
              .kind_id = {_cpp_string(modifier.kind_id)},
          }}"""


def _emit_operand_slot_array(
    variant_name: str,
    layout_index: int,
    layout: SyntaxOperandLayoutDescriptor,
) -> str:
    slots = ",\n".join(
        _emit_operand_slot(slot)
        for slot in layout.slots
    )
    return f"""\
  inline static constexpr std::array<check_end::SyntaxOperandSlotDescriptor, {len(layout.slots)}>
      {variant_name}_layout_{layout_index}_slots = {{
{slots}
      }};"""


def _emit_operand_layout_array(
    variant_name: str,
    layouts: tuple[SyntaxOperandLayoutDescriptor, ...],
) -> str:
    entries = ",\n".join(
        f"""\
          check_end::SyntaxOperandLayoutDescriptor{{
              .layout_id = {_cpp_string(layout.layout_id)},
              .kind = {cpp_value(CppDomain.SYNTAX_OPERAND_LAYOUT_KINDS, layout.kind.value)},
              .slots = {variant_name}_layout_{index}_slots,
          }}"""
        for index, layout in enumerate(layouts)
    )
    return f"""\
  inline static constexpr std::array<check_end::SyntaxOperandLayoutDescriptor, {len(layouts)}>
      {variant_name}_operand_layouts = {{
{entries}
      }};"""


def _emit_operand_slot(
    slot: SyntaxOperandSlotDescriptor,
) -> str:
    allowed_shapes = _cpp_operand_syntax_shape(slot.allowed_syntax_shapes)
    return f"""\
          check_end::SyntaxOperandSlotDescriptor{{
              .allowed_shapes = {allowed_shapes},
              .presence = {cpp_value(CppDomain.SYNTAX_OPERAND_PRESENCE, slot.presence.value)},
          }}"""


def _emit_variant_descriptor(
    variant: SyntaxVariantDescriptor,
    opcode: str,
) -> str:
    name = to_file_stem(variant.variant_id)
    return f"""\
          check_end::SyntaxVariantDescriptor{{
              .variant_name = {_cpp_string(_cpp_variant_name(opcode, variant.variant_id))},
              .modifiers = {name}_modifiers,
              .operand_layouts = {name}_operand_layouts,
          }}"""


def _cpp_operand_syntax_shape(shape: OperandSyntaxShape) -> str:
    values = [
        cpp_value(CppDomain.SYNTAX_OPERAND_SHAPES, flag.name)
        for flag in OperandSyntaxShape
        if shape & flag
    ]
    if not values:
        raise ValueError("operand syntax shape must not be empty")
    return " | ".join(values)


def _cpp_variant_name(opcode: str, variant_id: str) -> str:
    prefix = f"{opcode}_"
    if not variant_id.startswith(prefix):
        raise ValueError(
            f"variant {variant_id!r} does not start with opcode prefix {prefix!r}"
        )
    return file_stem_to_pascal_case(variant_id.removeprefix(prefix))


def _cpp_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
