"""Emit resolved descriptor storage and resolve specializations."""

from __future__ import annotations

from pathlib import Path

from base.utils import generated_at_comment, to_file_stem
from code_gen.database import CodegenDatabase
from ir.resolved_ir import (
    ResolvedField,
    ResolvedInstruction,
    ResolvedModifierBinding,
    ResolvedOperandAccess,
    ResolvedOperandLayout,
    ResolvedOperandRole,
    ResolvedOperandShape,
    ResolvedOperandTypeExpression,
    ResolvedOperandTypeExpressionKind,
    ResolvedVariant,
    ResolvedValueKind,
    from_instruction_spec,
)
from ir.scalar_types import SCALAR_TYPE_CPP_ENUM_NAMES


_CPP_RESOLVED_VALUE_KINDS = {
    ResolvedValueKind.BOOL: "check_end::ResolvedValueKind::Bool",
    ResolvedValueKind.SCALAR_TYPE: "check_end::ResolvedValueKind::ScalarType",
    ResolvedValueKind.REGISTER: "check_end::ResolvedValueKind::Register",
    ResolvedValueKind.PREDICATE: "check_end::ResolvedValueKind::Predicate",
    ResolvedValueKind.IMMEDIATE: "check_end::ResolvedValueKind::Immediate",
    ResolvedValueKind.REG_OR_IMM: "check_end::ResolvedValueKind::RegOrImm",
}

_CPP_OPERAND_ROLES = {
    ResolvedOperandRole.DESTINATION: "check_end::OperandRole::Destination",
    ResolvedOperandRole.SOURCE: "check_end::OperandRole::Source",
    ResolvedOperandRole.ADDRESS: "check_end::OperandRole::Address",
    ResolvedOperandRole.PREDICATE: "check_end::OperandRole::Predicate",
    ResolvedOperandRole.BRANCH_TARGET: "check_end::OperandRole::BranchTarget",
    ResolvedOperandRole.BARRIER: "check_end::OperandRole::Barrier",
    ResolvedOperandRole.THREAD_COUNT: "check_end::OperandRole::ThreadCount",
}

_CPP_OPERAND_ACCESS = {
    ResolvedOperandAccess.READ: "check_end::OperandAccess::Read",
    ResolvedOperandAccess.WRITE: "check_end::OperandAccess::Write",
    ResolvedOperandAccess.READ_WRITE: "check_end::OperandAccess::ReadWrite",
}

_CPP_OPERAND_SHAPES = {
    ResolvedOperandShape.REGISTER: "check_end::OperandShape::Register",
    ResolvedOperandShape.PREDICATE: "check_end::OperandShape::Predicate",
    ResolvedOperandShape.IMMEDIATE: "check_end::OperandShape::Immediate",
    ResolvedOperandShape.ADDRESS: "check_end::OperandShape::Address",
    ResolvedOperandShape.SYMBOL: "check_end::OperandShape::Symbol",
    ResolvedOperandShape.VECTOR: "check_end::OperandShape::Vector",
}

_CPP_OPERAND_TYPE_EXPRESSION_KINDS = {
    ResolvedOperandTypeExpressionKind.NONE:
        "check_end::OperandTypeExpressionKind::None",
    ResolvedOperandTypeExpressionKind.FIXED_SCALAR:
        "check_end::OperandTypeExpressionKind::FixedScalar",
    ResolvedOperandTypeExpressionKind.MODIFIER_FIELD:
        "check_end::OperandTypeExpressionKind::ModifierField",
}

def generate_resolved_descriptor_source(
    database: CodegenDatabase,
    *,
    output_path: Path,
) -> None:
    """Generate one private C++ source for resolved descriptor storage."""

    instructions = tuple(
        from_instruction_spec(instruction) for instruction in database.instructions
    )
    _validate_unique_cpp_names(instructions)
    storage_definitions = "\n\n".join(
        _emit_resolved_descriptor_storage(instruction)
        for instruction in instructions
    )
    getter_definitions = "\n\n".join(
        _emit_resolved_descriptor_getter(instruction)
        for instruction in instructions
    )
    content = f"""// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include "ptx_ir/resolved/ptx_resolved_ir.hpp"

namespace ptx_frontend::resolved_ir {{

namespace generated_detail {{

{storage_definitions}

}}  // namespace generated_detail

{getter_definitions}

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def _emit_resolved_instruction_implementation(
    instruction: ResolvedInstruction,
) -> str:
    return (
        f"{_emit_resolved_descriptor_storage(instruction)}\n\n"
        f"{_emit_resolved_descriptor_getter(instruction)}"
    )


def _emit_resolved_descriptor_storage(
    instruction: ResolvedInstruction,
) -> str:
    storage_name = f"{instruction.cpp_name}ResolvedDescriptorStorage"
    variant_storage = "\n\n".join(
        _emit_resolved_variant_storage(variant) for variant in instruction.variants
    )
    variants = ",\n".join(
        _emit_resolved_variant_descriptor(variant) for variant in instruction.variants
    )

    return f"""struct {storage_name} {{
{variant_storage}

  static constexpr std::array<check_end::ResolvedVariantDescriptor, {len(instruction.variants)}>
      variants = {{
{variants}
      }};

  static constexpr check_end::ResolvedInstructionDescriptor descriptor{{
      .opcode_name = "{instruction.opcode}",
      .variants = variants,
  }};
}};
"""



def _emit_resolved_descriptor_getter(
    instruction: ResolvedInstruction,
) -> str:
    """Emit the resolved descriptor getter outside generated_detail."""

    storage_name = f"{instruction.cpp_name}ResolvedDescriptorStorage"
    return f"""\
const check_end::ResolvedInstructionDescriptor&
{instruction.cpp_name}::get_resolved_descriptor() noexcept {{
  return generated_detail::{storage_name}::descriptor;
}}"""


def _emit_resolved_variant_storage(variant: ResolvedVariant) -> str:
    name = to_file_stem(variant.variant_id)
    fields = ",\n".join(
        _emit_resolved_field_descriptor(field) for field in variant.modifier_fields
    )
    modifier_bindings = ",\n".join(
        _emit_modifier_binding_descriptor(binding)
        for binding in variant.modifier_bindings
    )
    operand_layout_storage = "\n\n".join(
        _emit_operand_layout_storage(name, index, layout)
        for index, layout in enumerate(variant.operand_layouts)
    )
    operand_layouts = ",\n".join(
        f"""check_end::ResolvedOperandLayoutDescriptor{{
              .layout_id = "{layout.layout_id}",
              .fields = {name}_operand_layout_{index}_fields,
              .bindings = {name}_operand_layout_{index}_bindings,
          }}"""
        for index, layout in enumerate(variant.operand_layouts)
    )

    return f"""  static constexpr std::array<check_end::ResolvedFieldDescriptor, {len(variant.modifier_fields)}>
      {name}_fields = {{
{fields}
      }};

  static constexpr std::array<check_end::ResolvedModifierBindingDescriptor, {len(variant.modifier_bindings)}>
      {name}_modifier_bindings = {{
{modifier_bindings}
      }};

{operand_layout_storage}

  static constexpr std::array<check_end::ResolvedOperandLayoutDescriptor, {len(variant.operand_layouts)}>
      {name}_operand_layouts = {{
{operand_layouts}
      }};"""


def _emit_resolved_field_descriptor(field: ResolvedField) -> str:
    return f"""          check_end::ResolvedFieldDescriptor{{
              .field_id = "{field.name}",
              .value_kind = {_CPP_RESOLVED_VALUE_KINDS[field.value_kind]},
          }}"""


def _emit_modifier_binding_descriptor(binding: ResolvedModifierBinding) -> str:
    return f"""          check_end::ResolvedModifierBindingDescriptor{{
              .source_kind_id = "{binding.source_kind_id}",
              .target_field_id = "{binding.target_field_id}",
              .default_value = {_emit_modifier_default_descriptor(binding)},
          }}"""


def _emit_modifier_default_descriptor(binding: ResolvedModifierBinding) -> str:
    default = binding.default_value
    if default is None:
        return "check_end::ResolvedModifierDefaultDescriptor{}"
    if default.value_cpp_type == "bool" and type(default.value) is bool:
        bool_value = "true" if default.value else "false"
        return f"""check_end::ResolvedModifierDefaultDescriptor{{
                  .kind = check_end::ResolvedModifierDefaultKind::Bool,
                  .bool_value = {bool_value},
                  .scalar_type = ScalarType::Invalid,
              }}"""
    if default.value_cpp_type == "ScalarType" and isinstance(default.value, str):
        try:
            scalar_type = SCALAR_TYPE_CPP_ENUM_NAMES[default.value]
        except KeyError as error:
            raise ValueError(
                f"unsupported scalar-type modifier default {default.value!r}"
            ) from error
        return f"""check_end::ResolvedModifierDefaultDescriptor{{
                  .kind = check_end::ResolvedModifierDefaultKind::ScalarType,
                  .bool_value = false,
                  .scalar_type = ScalarType::{scalar_type},
              }}"""
    raise ValueError(
        f"unsupported modifier default {default.value!r} for "
        f"{default.value_cpp_type}"
    )


def _emit_operand_layout_storage(
    variant_name: str,
    layout_index: int,
    layout: ResolvedOperandLayout,
) -> str:
    fields = ",\n".join(
        _emit_resolved_field_descriptor(field) for field in layout.fields
    )
    bindings = ",\n".join(
        _emit_operand_binding_descriptor(binding) for binding in layout.bindings
    )
    return f"""  static constexpr std::array<check_end::ResolvedFieldDescriptor, {len(layout.fields)}>
      {variant_name}_operand_layout_{layout_index}_fields = {{
{fields}
      }};

  static constexpr std::array<check_end::ResolvedOperandBindingDescriptor, {len(layout.bindings)}>
      {variant_name}_operand_layout_{layout_index}_bindings = {{
{bindings}
      }};"""


def _emit_operand_binding_descriptor(binding) -> str:
    allowed_shapes = " | ".join(
        _CPP_OPERAND_SHAPES[shape] for shape in binding.allowed_shapes
    )
    return f"""          check_end::ResolvedOperandBindingDescriptor{{
              .target_field_id = "{binding.target_field_id}",
              .type_expression = {_emit_type_expression_descriptor(binding.type_expression)},
              .role = {_CPP_OPERAND_ROLES[binding.role]},
              .access = {_CPP_OPERAND_ACCESS[binding.access]},
              .allowed_shapes = {allowed_shapes},
          }}"""


def _emit_type_expression_descriptor(
    expression: ResolvedOperandTypeExpression,
) -> str:
    """Emit the constexpr C++ representation of one normalized type source."""

    fixed_scalar_type = "ScalarType::Invalid"
    modifier_field_id = '""'
    if expression.kind is ResolvedOperandTypeExpressionKind.FIXED_SCALAR:
        assert expression.scalar_type is not None
        fixed_scalar_type = (
            f"ScalarType::{SCALAR_TYPE_CPP_ENUM_NAMES[expression.scalar_type]}"
        )
    elif expression.kind is ResolvedOperandTypeExpressionKind.MODIFIER_FIELD:
        assert expression.modifier_field_id is not None
        modifier_field_id = f'"{expression.modifier_field_id}"'

    return f"""check_end::TypeExpressionDescriptor{{
                  .kind = {_CPP_OPERAND_TYPE_EXPRESSION_KINDS[expression.kind]},
                  .fixed_scalar_type = {fixed_scalar_type},
                  .modifier_field_id = {modifier_field_id},
              }}"""


def _emit_resolved_variant_descriptor(variant: ResolvedVariant) -> str:
    name = to_file_stem(variant.variant_id)
    return f"""          check_end::ResolvedVariantDescriptor{{
              .variant_name = "{variant.cpp_name}",
              .fields = {name}_fields,
              .modifier_bindings = {name}_modifier_bindings,
              .operand_layouts = {name}_operand_layouts,
          }}"""


def _validate_unique_cpp_names(instructions: tuple[ResolvedInstruction, ...]) -> None:
    seen: set[str] = set()
    for instruction in instructions:
        if instruction.cpp_name in seen:
            raise ValueError(
                f"multiple resolved instructions map to C++ type "
                f"{instruction.cpp_name!r}"
            )
        seen.add(instruction.cpp_name)
