"""Emit private constexpr lookup tables for resolver value domains."""

from __future__ import annotations

from pathlib import Path

from base.utils import file_stem_to_pascal_case, generated_at_comment
from code_gen.model import CodegenUnit, DomainBackend, RuntimeLookupKind


def generate_resolved_value_domain_header(
    backend: CodegenUnit,
    *,
    output_path: Path,
) -> None:
    """Generate resolver lookup tables declared by backend ``runtime_lookup``."""

    domains = tuple(
        (name, domain)
        for name, domain in backend.domains.items()
        if domain.runtime_lookup is RuntimeLookupKind.PTX_SUFFIX
    )
    tables = "\n\n".join(
        _emit_ptx_suffix_table(name, domain) for name, domain in domains
    )
    content = f"""// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#pragma once

#include <array>
#include <string_view>

#include <ptx_frontend/base/base.hpp>

namespace ptx_frontend::resolved_ir::generated_detail {{

template <typename T>
struct PtxSuffixEntry {{
  std::string_view suffix;
  T value;
}};

{tables}

}}  // namespace ptx_frontend::resolved_ir::generated_detail
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def _emit_ptx_suffix_table(name: str, domain: DomainBackend) -> str:
    entries = ",\n".join(
        f'        {{"{suffix}", {value}}}'
        for suffix, value in domain.values.items()
    )
    return f"""inline constexpr std::array<PtxSuffixEntry<{domain.cpp_type}>, {len(domain.values)}>
    k{file_stem_to_pascal_case(name)} = {{{{
{entries}
    }}}};"""
