"""Generate C++ Resolved IR instruction definitions."""

from __future__ import annotations

from pathlib import Path

from base.utils import generated_at_comment
from code_gen.cpp_backend import CppDomain, cpp_default, cpp_value
from code_gen.database import CodegenDatabase
from ir.resolved_ir import (
    ResolvedField,
    ResolvedFieldStorage,
    ResolvedInstruction,
    ResolvedOperandLayout,
    ResolvedVariant,
    from_instruction_spec,
)


def generate_resolved_ir_header(
    database: CodegenDatabase,
    *,
    output_path: Path,
) -> None:
    """Generate a self-contained public Resolved IR header.

    The generated header may be included directly.  It includes the resolved
    IR foundation header, which supplies ``WithLocs``, resolved operand
    primitives, and ``check_end`` descriptors, then declares the generated
    instruction types in ``ptx_frontend::resolved_ir``.
    """

    instructions = tuple(
        from_instruction_spec(instruction) for instruction in database.instructions
    )
    _validate_unique_cpp_names(instructions)

    definitions = "\n\n".join(
        emit_resolved_instruction_definition(instruction)
        for instruction in instructions
    )
    resolve_declarations = "\n\n".join(
        _emit_resolve_specialization_declaration(instruction)
        for instruction in instructions
    )
    check_declarations = "\n\n".join(
        _emit_check_specialization_declaration(instruction)
        for instruction in instructions
    )
    module_containers = _emit_resolved_module_containers(instructions)
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

#include <optional>
#include <string>
#include <variant>
#include <vector>

#include <ptx_frontend/resolved_ir/ptx_resolved_ir.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_checker.hpp>

namespace ptx_frontend::resolved_ir {{

{definitions}

{module_containers}

{resolve_declarations}

namespace checker {{

{check_declarations}

}}  // namespace checker

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def generate_resolved_dispatch_source(
    database: CodegenDatabase,
    *,
    output_path: Path,
) -> None:
    """Generate opcode-independent instruction resolution dispatch."""

    instructions = tuple(
        from_instruction_spec(instruction) for instruction in database.instructions
    )
    _validate_unique_cpp_names(instructions)
    branches = "\n\n".join(
        _emit_resolved_dispatch_branch(instruction)
        for instruction in instructions
    )
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include "resolved_ir.gen.hpp"

#include <utility>

namespace ptx_frontend::resolved_ir {{

namespace {{

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolve_instruction(const syntax_ast::AstInstruction& ast,
                    const ResolveContext* context) {{
{branches}

  return std::unexpected(ResolveDiagnostic{{
      .range = ast.opcode.syntax.range,
      .message = "Unknown PTX opcode '" + ast.opcode.syntax.text + "'.",
  }});
}}

}}  // namespace

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolveInstruction(const syntax_ast::AstInstruction& ast) {{
  return resolve_instruction(ast, nullptr);
}}

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolveInstruction(const syntax_ast::AstInstruction& ast,
                   const ResolveContext& context) {{
  return resolve_instruction(ast, &context);
}}

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def _emit_resolved_module_containers(
    instructions: tuple[ResolvedInstruction, ...],
) -> str:
    alternatives = ", ".join(
        instruction.cpp_name for instruction in instructions
    )
    return f"""\
using ResolvedInstruction = std::variant<{alternatives}>;

struct ResolvedFunction {{
  binding::SymbolId symbol_id;
  std::string name;
  bool is_entry{{}};
  bool is_prototype{{}};
  std::vector<ResolvedInstruction> body;
  SourceRange range;
}};

struct ResolvedModule {{
  binding::SymbolTable symbols;
  std::vector<ResolvedFunction> functions;
  SourceRange range;
}};

/** Check one resolved module against its source .version and .target profile. */
checker::CheckResult checkModuleAvailability(const syntax_ast::AstModule& ast,
                                             const ResolvedModule& module);

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolveInstruction(const syntax_ast::AstInstruction& ast);

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolveInstruction(const syntax_ast::AstInstruction& ast,
                   const ResolveContext& context);

using ModuleResolveDiagnostics = std::vector<ResolveDiagnostic>;

std::expected<ResolvedModule, ModuleResolveDiagnostics>
resolveModule(const syntax_ast::AstModule& ast);"""


def _emit_resolved_dispatch_branch(instruction: ResolvedInstruction) -> str:
    return f"""\
  if (ast.opcode.syntax.text == "{instruction.opcode}") {{
    auto resolved = resolve<{instruction.cpp_name}>(ast, context);
    if (!resolved)
      return std::unexpected(resolved.error());
    return ResolvedInstruction{{std::in_place_type<{instruction.cpp_name}>,
                               std::move(*resolved)}};
  }}"""


def generate_resolved_ir_source(
    database: CodegenDatabase,
    *,
    category: str,
    output_path: Path,
) -> None:
    """Generate out-of-line specializations for one instruction category."""

    instructions = tuple(
        from_instruction_spec(instruction)
        for instruction in database.instructions
        if instruction.codegen_category == category
    )
    if not instructions:
        raise ValueError(f"instruction category {category!r} is empty")
    _validate_unique_cpp_names(instructions)

    resolve_definitions = "\n\n".join(
        _emit_resolve_specialization(instruction) for instruction in instructions
    )
    check_definitions = "\n\n".join(
        _emit_check_specialization(instruction) for instruction in instructions
    )
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include "resolved_ir.gen.hpp"

namespace ptx_frontend::resolved_ir {{

{resolve_definitions}

namespace checker {{

{check_definitions}

}}  // namespace checker

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def emit_resolved_instruction_definition(instruction: ResolvedInstruction) -> str:
    """Emit one opcode-level C++ resolved instruction struct."""

    variant_names = ", ".join(variant.cpp_name for variant in instruction.variants)
    variant_enum_values = "\n".join(
        f"    {variant.cpp_name}," for variant in instruction.variants
    )
    variant_definitions = "\n\n".join(
        _emit_resolved_variant_definition(variant) for variant in instruction.variants
    )

    definition = f"""\
struct {instruction.cpp_name} {{
  enum class VariantType {{
{variant_enum_values}
  }};

{variant_definitions}

  using Variant = std::variant<{variant_names}>;
  std::optional<WithLocs<ResolvedPredicate>> execution_predicate;
  Variant variant;

  static const check_end::SyntaxInstructionDescriptor&
  get_syntax_descriptor() noexcept;
  static const check_end::ResolvedInstructionDescriptor&
  get_resolved_descriptor() noexcept;
  static const checker::InstructionDescriptor&
  get_checker_descriptor() noexcept;
}};"""
    return definition


def _emit_resolve_specialization_declaration(
    instruction: ResolvedInstruction,
) -> str:
    return f"""\
template <>
std::expected<{instruction.cpp_name}, ResolveDiagnostic>
resolve<{instruction.cpp_name}>(const syntax_ast::AstInstruction& ast,
    const ResolveContext* context);"""


def _emit_check_specialization_declaration(
    instruction: ResolvedInstruction,
) -> str:
    return f"""\
template <>
CheckResult check<{instruction.cpp_name}>(
    const {instruction.cpp_name}& instruction, const Context& context);"""


def _emit_resolve_specialization(instruction: ResolvedInstruction) -> str:
    variant_cases = "\n".join(
        _emit_resolve_variant_case(instruction, variant)
        for variant in instruction.variants
    )
    return f"""\
template <>
std::expected<{instruction.cpp_name}, ResolveDiagnostic>
resolve<{instruction.cpp_name}>(const syntax_ast::AstInstruction& ast,
    const ResolveContext* context) {{
  const auto selected_variant = selectVariant<{instruction.cpp_name}>(ast);
  if (!selected_variant)
    return std::unexpected(selected_variant.error());

  auto fields = resolve_fields(
      ast, {instruction.cpp_name}::get_syntax_descriptor(),
      {instruction.cpp_name}::get_resolved_descriptor(),
      magic_enum::enum_name(*selected_variant), context);
  if (!fields)
    return std::unexpected(fields.error());

{variant_cases}

  throw ResolveException("Unknown {instruction.cpp_name} variant in resolved field table.");
}}"""


def _emit_resolve_variant_case(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
) -> str:
    if len(variant.operand_layouts) == 1:
        fields = "\n".join(
            "          " + _emit_resolve_field_initializer(field)
            for field in variant.modifier_fields + variant.operand_layouts[0].fields
            if field.storage is ResolvedFieldStorage.INSTANCE
        )
        return f"""\
  if (fields->variant_name == "{variant.cpp_name}") {{
    return {instruction.cpp_name}{{
        .execution_predicate = std::move(fields->execution_predicate),
        .variant = {instruction.cpp_name}::{variant.cpp_name}{{
                   .operand_layout = fields->operand_layout,
{fields}
    }}}};
  }}"""

    layout_cases = "\n".join(
        _emit_resolve_multi_layout_case(instruction, variant, index)
        for index, _ in enumerate(variant.operand_layouts)
    )
    fields = "\n".join(
        "          " + _emit_resolve_field_initializer(field)
        for field in variant.modifier_fields
        if field.storage is ResolvedFieldStorage.INSTANCE
    )
    return f"""\
  if (fields->variant_name == "{variant.cpp_name}") {{
{layout_cases}
    throw ResolveException("Unknown {instruction.cpp_name}::{variant.cpp_name} operand layout.");
  }}"""


def _emit_resolve_multi_layout_case(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    layout_index: int,
) -> str:
    layout = variant.operand_layouts[layout_index]
    modifier_fields = "\n".join(
        "              " + _emit_resolve_field_initializer(field)
        for field in variant.modifier_fields
        if field.storage is ResolvedFieldStorage.INSTANCE
    )
    operand_fields = "\n".join(
        "                  " + _emit_resolve_field_initializer(field)
        for field in layout.fields
        if field.storage is ResolvedFieldStorage.INSTANCE
    )
    return f"""    if (fields->operand_layout.value == {layout_index}) {{
      return {instruction.cpp_name}{{
          .execution_predicate = std::move(fields->execution_predicate),
          .variant = {instruction.cpp_name}::{variant.cpp_name}{{
              .operand_layout = fields->operand_layout,
{modifier_fields}
              .operands = {instruction.cpp_name}::{variant.cpp_name}::Operands{{
                  {instruction.cpp_name}::{variant.cpp_name}::{layout.cpp_name}Operands{{
{operand_fields}
                  }},
              }},
          }}}};
    }}"""


def _emit_check_specialization(instruction: ResolvedInstruction) -> str:
    variant_lambdas = "\n\n".join(
        _emit_check_variant_lambda(instruction, index, variant)
        for index, variant in enumerate(instruction.variants)
    )
    visitor_lambdas = ", ".join(
        _check_lambda_name(instruction, variant) for variant in instruction.variants
    )
    return f"""\
template <>
CheckResult check<{instruction.cpp_name}>(
    const {instruction.cpp_name}& instruction, const Context& context) {{
{variant_lambdas}

  return std::visit(detail::Overloaded{{{visitor_lambdas}}}, instruction.variant);
}}"""


def _emit_check_variant_lambda(
    instruction: ResolvedInstruction,
    variant_index: int,
    variant: ResolvedVariant,
) -> str:
    modifier_fields = [
        field for field in variant.modifier_fields if field.origin.value == "modifier"
    ]
    modifier_views = ",\n".join(
        _emit_check_modifier_view(instruction, variant, field)
        for field in modifier_fields
    )
    modifier_value_views = ",\n".join(
        _emit_check_modifier_value_view(instruction, variant, field)
        for field in modifier_fields
    )
    operand_check = _emit_check_operand_dispatch(instruction, variant, variant_index)
    lambda_name = _check_lambda_name(instruction, variant)
    return f"""  const auto {lambda_name} =
      [&](const {instruction.cpp_name}::{variant.cpp_name}& selected) -> CheckResult {{
          const std::array<FieldView, {len(modifier_fields)}> fields = {{{{
{modifier_views}
          }}}};
          const std::array<ModifierValueView, {len(modifier_fields)}> modifier_values = {{{{
{modifier_value_views}
          }}}};
          CheckDiagnostics diagnostics;
          const auto common = check_common(
              {instruction.cpp_name}::get_checker_descriptor(), "{variant.cpp_name}",
              context);
          if (!common) {{
            diagnostics.insert(diagnostics.end(), common.error().begin(),
                               common.error().end());
          }}
          const auto modifier_availability = check_modifier_value_availability(
              {instruction.cpp_name}::get_checker_descriptor().variants[{variant_index}]
                  .modifier_value_availabilities,
              modifier_values, context);
          if (!modifier_availability) {{
            diagnostics.insert(diagnostics.end(),
                               modifier_availability.error().begin(),
                               modifier_availability.error().end());
          }}
{operand_check}
          if (diagnostics.empty())
            return CheckResult{{}};
          return std::unexpected(std::move(diagnostics));
      }};
  static_assert(detail::VariantCheckFunction<
      decltype({lambda_name}), {instruction.cpp_name}::{variant.cpp_name}>);"""


def _emit_check_operand_dispatch(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    variant_index: int,
) -> str:
    layouts_expr = (
        f"{instruction.cpp_name}::get_resolved_descriptor().variants[{variant_index}]"
        ".operand_layouts"
    )
    checker_variant_expr = (
        f"{instruction.cpp_name}::get_checker_descriptor().variants[{variant_index}]"
    )
    cross_rule_checks = _emit_cross_rule_checks(variant, checker_variant_expr)
    if len(variant.operand_layouts) == 1:
        operand_views = ",\n".join(
            _emit_check_operand_view(field, "selected")
            for field in variant.operand_layouts[0].fields
        )
        return f"""          const std::array<OperandView, {len(variant.operand_layouts[0].fields)}> operands = {{{{
{operand_views}
          }}}};
          const auto& layouts = {layouts_expr};
          const auto layout_check = check_operand_layout_tag(
              "{variant.cpp_name}", selected.operand_layout.value, layouts.size(),
              context);
          if (!layout_check) {{
            diagnostics.insert(diagnostics.end(), layout_check.error().begin(),
                               layout_check.error().end());
          }} else {{
            const auto availability_check = check_operand_layout_availability(
                {checker_variant_expr}, selected.operand_layout.value, context);
            if (!availability_check) {{
              diagnostics.insert(diagnostics.end(), availability_check.error().begin(),
                                 availability_check.error().end());
            }}
            const auto operand_check = check_operands(
                layouts[selected.operand_layout.value].bindings, fields, operands,
                {checker_variant_expr}.operand_type_compatibilities, context);
            if (!operand_check) {{
              diagnostics.insert(diagnostics.end(), operand_check.error().begin(),
                                 operand_check.error().end());
            }}
{cross_rule_checks}          }}"""

    layout_lambdas = "\n\n".join(
        _emit_check_multi_layout_lambda(
            instruction, variant, variant_index, layout_index
        )
        for layout_index, _ in enumerate(variant.operand_layouts)
    )
    visitor_lambdas = ", ".join(
        _check_layout_lambda_name(variant, layout) for layout in variant.operand_layouts
    )
    return f"""{layout_lambdas}

          const auto& layouts = {layouts_expr};
          const auto layout_check = check_operand_layout_tag(
              "{variant.cpp_name}", selected.operand_layout.value, layouts.size(),
              context);
          if (!layout_check) {{
            diagnostics.insert(diagnostics.end(), layout_check.error().begin(),
                               layout_check.error().end());
          }} else {{
            const auto availability_check = check_operand_layout_availability(
                {checker_variant_expr}, selected.operand_layout.value, context);
            if (!availability_check) {{
              diagnostics.insert(diagnostics.end(), availability_check.error().begin(),
                                 availability_check.error().end());
            }}
            const auto payload_check = std::visit(
                detail::Overloaded{{{visitor_lambdas}}}, selected.operands);
            if (!payload_check) {{
              diagnostics.insert(diagnostics.end(), payload_check.error().begin(),
                                 payload_check.error().end());
            }}
          }}"""


def _emit_check_multi_layout_lambda(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    variant_index: int,
    layout_index: int,
) -> str:
    layout = variant.operand_layouts[layout_index]
    lambda_name = _check_layout_lambda_name(variant, layout)
    operand_views = ",\n".join(
        _emit_check_operand_view(field, "payload") for field in layout.fields
    )
    cross_rule_return = f"""
            return check_operands(
                {instruction.cpp_name}::get_resolved_descriptor().variants[{variant_index}]
                    .operand_layouts[{layout_index}]
                    .bindings,
                fields, operands,
                {instruction.cpp_name}::get_checker_descriptor().variants[{variant_index}]
                    .operand_type_compatibilities,
                context);"""
    cross_rule_checks = _emit_cross_rule_checks(
        variant,
        f"{instruction.cpp_name}::get_checker_descriptor().variants[{variant_index}]",
    )
    if cross_rule_checks:
        cross_rule_return = f"""
            const auto operand_check = check_operands(
                {instruction.cpp_name}::get_resolved_descriptor().variants[{variant_index}]
                    .operand_layouts[{layout_index}]
                    .bindings,
                fields, operands,
                {instruction.cpp_name}::get_checker_descriptor().variants[{variant_index}]
                    .operand_type_compatibilities,
                context);
            CheckDiagnostics diagnostics;
            if (!operand_check) {{
              diagnostics.insert(diagnostics.end(), operand_check.error().begin(),
                                 operand_check.error().end());
            }}
{cross_rule_checks}            if (diagnostics.empty())
              return CheckResult{{}};
            return std::unexpected(std::move(diagnostics));"""
    return f"""          const auto {lambda_name} =
              [&](const {instruction.cpp_name}::{variant.cpp_name}::{layout.cpp_name}Operands& payload)
                  -> CheckResult {{
            if (selected.operand_layout.value != {layout_index}) {{
              return std::unexpected(CheckDiagnostics{{CheckDiagnostic{{
                  .kind = CheckDiagnosticKind::OperandLayoutPayloadMismatch,
                  .range = context.instruction_range,
                  .message = "Resolved operand-layout tag and payload alternative disagree.",
              }}}});
            }}
            const std::array<OperandView, {len(layout.fields)}> operands = {{{{
{operand_views}
            }}}};{cross_rule_return}
          }};
          static_assert(detail::VariantCheckFunction<
              decltype({lambda_name}),
              {instruction.cpp_name}::{variant.cpp_name}::{layout.cpp_name}Operands>);"""


def _emit_cross_rule_checks(
    variant: ResolvedVariant,
    checker_variant_expr: str,
) -> str:
    """Emit a variant's cross-rule checks in a fixed order."""

    checks = ""
    if variant.memory_consistency is not None:
        checks += f"""            const auto consistency_check = check_memory_consistency(
                {checker_variant_expr}.memory_consistency, fields, operands, context);
            if (!consistency_check) {{
              diagnostics.insert(diagnostics.end(), consistency_check.error().begin(),
                                 consistency_check.error().end());
            }}
"""
    if variant.memory_vector is not None:
        checks += f"""            const auto memory_vector_check = check_memory_vector(
                {checker_variant_expr}.memory_vector, fields, operands, context);
            if (!memory_vector_check) {{
              diagnostics.insert(diagnostics.end(), memory_vector_check.error().begin(),
                                 memory_vector_check.error().end());
            }}
"""
    if variant.address_alignment is not None:
        checks += f"""            const auto alignment_check = check_address_alignment(
                {checker_variant_expr}.address_alignment, fields, operands, context);
            if (!alignment_check) {{
              diagnostics.insert(diagnostics.end(), alignment_check.error().begin(),
                                 alignment_check.error().end());
            }}
"""
    if variant.immediate_value is not None:
        checks += f"""            const auto immediate_value_check = check_immediate_value(
                {checker_variant_expr}.immediate_value, operands, context);
            if (!immediate_value_check) {{
              diagnostics.insert(diagnostics.end(), immediate_value_check.error().begin(),
                                 immediate_value_check.error().end());
            }}
"""
    if variant.immediate_ranges:
        checks += f"""            for (const auto& immediate_range : {checker_variant_expr}.immediate_ranges) {{
              const auto immediate_range_check = check_immediate_range(
                  immediate_range, operands, context);
              if (!immediate_range_check) {{
                diagnostics.insert(diagnostics.end(), immediate_range_check.error().begin(),
                                   immediate_range_check.error().end());
              }}
            }}
"""
    if variant.immediate_multiple_of is not None:
        checks += f"""            const auto immediate_multiple_of_check = check_immediate_multiple_of(
                {checker_variant_expr}.immediate_multiple_of, operands, context);
            if (!immediate_multiple_of_check) {{
              diagnostics.insert(diagnostics.end(), immediate_multiple_of_check.error().begin(),
                                 immediate_multiple_of_check.error().end());
            }}
"""
    return checks


def _check_layout_lambda_name(
    variant: ResolvedVariant, layout: ResolvedOperandLayout
) -> str:
    return f"check_{variant.variant_id}_{layout.layout_id}_operands"


def _check_lambda_name(
    instruction: ResolvedInstruction, variant: ResolvedVariant
) -> str:
    variant_suffix = variant.variant_id.removeprefix(f"{instruction.opcode}_")
    return f"check_{variant_suffix}"


def _emit_check_modifier_view(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    field: ResolvedField,
) -> str:
    if field.storage is ResolvedFieldStorage.STATIC_CONSTANT:
        bool_value = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "bool" else "std::nullopt"
        )
        scalar_type = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "ScalarType"
            else "std::nullopt"
        )
        comparison_operator = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "ComparisonOperator" else "std::nullopt"
        )
        boolean_operator = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "BooleanOperator" else "std::nullopt"
        )
        vector_arity = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "VectorArity"
            else "std::nullopt"
        )
        memory_state_space = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "MemoryStateSpace"
            else "std::nullopt"
        )
        memory_consistency = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "MemoryConsistency" else "std::nullopt"
        )
        memory_scope = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "MemoryScope" else "std::nullopt"
        )
        cache_operator = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "CacheOperator" else "std::nullopt"
        )
        eviction_priority = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "EvictionPriority" else "std::nullopt"
        )
        locations = "std::span<const SourceRange>{}"
    else:
        bool_value = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "bool" else "std::nullopt"
        )
        scalar_type = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "ScalarType"
            else "std::nullopt"
        )
        comparison_operator = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "ComparisonOperator" else "std::nullopt"
        )
        boolean_operator = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "BooleanOperator" else "std::nullopt"
        )
        vector_arity = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "VectorArity"
            else "std::nullopt"
        )
        memory_state_space = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "MemoryStateSpace"
            else "std::nullopt"
        )
        memory_consistency = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "MemoryConsistency" else "std::nullopt"
        )
        memory_scope = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "MemoryScope" else "std::nullopt"
        )
        cache_operator = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "CacheOperator" else "std::nullopt"
        )
        eviction_priority = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "EvictionPriority" else "std::nullopt"
        )
        locations = f"selected.{field.name}.locs"
    return f"""              FieldView{{
                  .field_id = "{field.name}",
                  .bool_value = {bool_value},
                  .cache_operator = {cache_operator},
                  .eviction_priority = {eviction_priority},
                  .scalar_type = {scalar_type},
                  .comparison_operator = {comparison_operator},
                  .boolean_operator = {boolean_operator},
                  .vector_arity = {vector_arity},
                  .memory_state_space = {memory_state_space},
                  .memory_consistency = {memory_consistency},
                  .memory_scope = {memory_scope},
                  .locations = {locations},
              }}"""


def _emit_check_modifier_value_view(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    field: ResolvedField,
) -> str:
    if field.value_cpp_type == "ScalarType":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "ScalarType"
        )
        bool_value = "false"
        scalar_type = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
    elif field.value_cpp_type == "bool":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "bool"
        )
        bool_value = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
    elif field.value_cpp_type == "RoundingMode":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "RoundingMode"
        )
        bool_value = "false"
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
        memory_state_space = cpp_default(CppDomain.MEMORY_STATE_SPACES)
    elif field.value_cpp_type == "ComparisonOperator":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "ComparisonOperator"
        )
        bool_value = "false"
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
        comparison_operator = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
        memory_state_space = cpp_default(CppDomain.MEMORY_STATE_SPACES)
    elif field.value_cpp_type == "BooleanOperator":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "BooleanOperator"
        )
        bool_value = "false"
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
        comparison_operator = cpp_default(CppDomain.COMPARISON_OPERATORS)
        boolean_operator = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
        memory_state_space = cpp_default(CppDomain.MEMORY_STATE_SPACES)
    elif field.value_cpp_type == "CacheOperator":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "CacheOperator"
        )
        bool_value = "false"
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
        cache_operator = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
        memory_state_space = cpp_default(CppDomain.MEMORY_STATE_SPACES)
    elif field.value_cpp_type == "EvictionPriority":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "EvictionPriority"
        )
        bool_value = "false"
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        eviction_priority = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
        memory_state_space = cpp_default(CppDomain.MEMORY_STATE_SPACES)
    elif field.value_cpp_type == "VectorArity":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "VectorArity"
        )
        bool_value = "false"
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        vector_arity = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
        memory_state_space = cpp_default(CppDomain.MEMORY_STATE_SPACES)
    elif field.value_cpp_type == "MemoryStateSpace":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "MemoryStateSpace"
        )
        bool_value = "false"
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
        memory_state_space = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
    elif field.value_cpp_type == "MemoryConsistency":
        value_kind = cpp_value(
            CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "MemoryConsistency"
        )
        bool_value = "false"
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
        memory_state_space = cpp_default(CppDomain.MEMORY_STATE_SPACES)
        memory_consistency = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
    elif field.value_cpp_type == "MemoryScope":
        value_kind = cpp_value(CppDomain.CHECKER_MODIFIER_VALUE_KINDS, "MemoryScope")
        bool_value = "false"
        scalar_type = cpp_default(CppDomain.SCALAR_TYPES)
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
        memory_state_space = cpp_default(CppDomain.MEMORY_STATE_SPACES)
        memory_scope = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
    else:
        raise ValueError(
            f"modifier field {field.name!r}: unsupported availability view type "
            f"{field.value_cpp_type!r}"
        )

    locations = (
        "std::span<const SourceRange>{}"
        if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
        else f"selected.{field.name}.locs"
    )
    if field.storage is ResolvedFieldStorage.STATIC_CONSTANT:
        is_present = "true"
    else:
        is_present = f"!selected.{field.name}.locs.empty()"
    if field.value_cpp_type != "RoundingMode":
        rounding_mode = cpp_default(CppDomain.ROUNDING_MODES)
    if field.value_cpp_type != "ComparisonOperator":
        comparison_operator = cpp_default(CppDomain.COMPARISON_OPERATORS)
    if field.value_cpp_type != "BooleanOperator":
        boolean_operator = cpp_default(CppDomain.BOOLEAN_OPERATORS)
    if field.value_cpp_type != "CacheOperator":
        cache_operator = cpp_default(CppDomain.CACHE_OPERATORS)
    if field.value_cpp_type != "EvictionPriority":
        eviction_priority = cpp_default(CppDomain.EVICTION_PRIORITIES)
    if field.value_cpp_type != "VectorArity":
        vector_arity = cpp_default(CppDomain.VECTOR_ARITIES)
    if field.value_cpp_type != "MemoryStateSpace":
        memory_state_space = cpp_default(CppDomain.MEMORY_STATE_SPACES)
    if field.value_cpp_type != "MemoryConsistency":
        memory_consistency = cpp_default(CppDomain.MEMORY_CONSISTENCIES)
    if field.value_cpp_type != "MemoryScope":
        memory_scope = cpp_default(CppDomain.MEMORY_SCOPES)
    return f"""              ModifierValueView{{
                  .kind_id = "{field.source_name}",
                  .value_kind = {value_kind},
                  .bool_value = {bool_value},
                  .scalar_type = {scalar_type},
                  .rounding_mode = {rounding_mode},
                  .comparison_operator = {comparison_operator},
                  .boolean_operator = {boolean_operator},
                  .cache_operator = {cache_operator},
                  .eviction_priority = {eviction_priority},
                  .vector_arity = {vector_arity},
                  .memory_state_space = {memory_state_space},
                  .memory_consistency = {memory_consistency},
                  .memory_scope = {memory_scope},
                  .is_present = {is_present},
                  .locations = {locations},
              }}"""


def _emit_check_operand_view(field: ResolvedField, object_name: str) -> str:
    if field.value_cpp_type == "ResolvedFunctionRef":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "DirectCallTarget")},
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedIndirectCallee":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "IndirectCallee")},
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedCallParameterRef":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "CallReturnParameter")},
                  .register_type = {object_name}.{field.name}.value.declared_type,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedCallArguments":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "CallArguments")},
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedRegisterVector":
        return f"""              [&]() -> OperandView {{
                OperandView view{{
                    .field_id = "{field.name}",
                    .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Vector")},
                    .vector_arity = static_cast<uint8_t>(
                        {object_name}.{field.name}.value.elements.size()),
                    .locations = {object_name}.{field.name}.locs,
                }};
                size_t index = 0;
                for (const auto& element :
                     {object_name}.{field.name}.value.elements) {{
                  if (index >= view.vector_element_shapes.size())
                    break;
                  if (element) {{
                    view.vector_element_shapes[index] =
                        {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Register")};
                    view.vector_element_types[index] =
                        element->declared_type.value_or(ScalarType::Invalid);
                  }} else {{
                    ++view.vector_sink_count;
                  }}
                  ++index;
                }}
                return view;
              }}()"""
    if field.value_cpp_type == "ResolvedTensorCoordinate":
        return f"""              [&]() -> OperandView {{
                OperandView view{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Vector")},
                  .vector_arity = static_cast<uint8_t>(
                      {object_name}.{field.name}.value.elements.size()),
                  .locations = {object_name}.{field.name}.locs,
                }};
                size_t index = 0;
                for (const auto& element :
                     {object_name}.{field.name}.value.elements) {{
                  if (index >= view.vector_element_shapes.size())
                    break;
                  if (const auto* register_ref =
                          std::get_if<ResolvedRegisterRef>(&element)) {{
                    view.vector_element_shapes[index] =
                        {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Register")};
                    view.vector_element_types[index] =
                        register_ref->declared_type.value_or(ScalarType::Invalid);
                  }} else {{
                    const auto& immediate = std::get<ResolvedImmediate>(element);
                    view.vector_element_shapes[index] =
                        {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Immediate")};
                    view.vector_element_types[index] = immediate.type;
                  }}
                  ++index;
                }}
                return view;
              }}()"""
    if field.value_cpp_type == "ResolvedVectorRegisterRef":
        return f"""              [&]() -> OperandView {{
                const auto& register_ref =
                    {object_name}.{field.name}.value.register_ref;
                OperandView view{{
                    .field_id = "{field.name}",
                    .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Vector")},
                    .vector_arity = register_ref.vector_width.value_or(0),
                    .locations = {object_name}.{field.name}.locs,
                }};
                for (uint8_t index = 0; index < view.vector_arity; ++index)
                  view.vector_element_types[index] =
                      register_ref.declared_type.value_or(ScalarType::Invalid);
                return view;
              }}()"""
    if field.value_cpp_type == "ResolvedVectorSpecialRegisterRef":
        return f"""              [&]() -> OperandView {{
                const auto& special_register = {object_name}.{field.name}.value;
                const auto info = base::metadata(special_register.id);
                OperandView view{{
                    .field_id = "{field.name}",
                    .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Vector")},
                    .special_register_type = info.element_type,
                    .special_register_id = special_register.id,
                    .vector_arity = info.vector_width,
                    .value_availability = special_register_availability(info),
                    .value_name = special_register.spelling,
                    .locations = {object_name}.{field.name}.locs,
                }};
                for (uint8_t index = 0; index < view.vector_arity; ++index)
                  view.vector_element_types[index] = info.element_type;
                return view;
              }}()"""
    if field.value_cpp_type == "ResolvedRegisterRef":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Register")},
                  .immediate_type = std::nullopt,
                  .register_type = {object_name}.{field.name}.value.declared_type,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedShflSyncDestination":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "ShflDestination")},
                  .immediate_type = std::nullopt,
                  .register_type = {object_name}.{field.name}.value.data.declared_type,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedPredicatePair":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "PredicatePair")},
                  .immediate_type = std::nullopt,
                  .predicate_pair_types = {{{object_name}.{field.name}.value.first.register_ref.declared_type.value_or(ScalarType::Invalid), {object_name}.{field.name}.value.second.register_ref.declared_type.value_or(ScalarType::Invalid)}},
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedImmediate":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Immediate")},
                  .immediate_type = {object_name}.{field.name}.value.type,
                  .immediate_bits = {object_name}.{field.name}.value.bits,
                  .immediate_is_negative = {object_name}.{field.name}.value.is_negative,
                  .register_type = std::nullopt,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedPredicate":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Predicate")},
                  .immediate_type = std::nullopt,
                  .register_type = {object_name}.{field.name}.value.register_ref.declared_type,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedPredicateSource":
        return f"""              [&]() -> OperandView {{
                const auto& source = {object_name}.{field.name}.value;
                if (const auto* special =
                        std::get_if<ResolvedSpecialRegisterRef>(&source)) {{
                  const auto info = base::metadata(special->id);
                  return OperandView{{
                      .field_id = "{field.name}",
                      .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "SpecialRegister")},
                      .special_register_type = info.element_type,
                      .special_register_id = special->id,
                      .value_availability = special_register_availability(info),
                      .value_name = special->spelling,
                      .locations = {object_name}.{field.name}.locs,
                  }};
                }}
                const auto& predicate = std::get<ResolvedPredicate>(source);
                return OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Predicate")},
                  .immediate_type = std::nullopt,
                  .register_type = predicate.register_ref.declared_type,
                  .locations = {object_name}.{field.name}.locs,
                }};
              }}()"""
    if field.value_cpp_type == "ResolvedBranchTarget":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "BranchTarget")},
                  .immediate_type = std::nullopt,
                  .register_type = std::nullopt,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedBranchTargetSet":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "BranchTargetSet")},
                  .immediate_type = std::nullopt,
                  .register_type = std::nullopt,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedSpecialRegisterRef":
        return f"""              [&]() -> OperandView {{
                const auto info = base::metadata(
                    {object_name}.{field.name}.value.id);
                return OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "SpecialRegister")},
                  .immediate_type = std::nullopt,
                  .register_type = std::nullopt,
                  .special_register_type = info.element_type,
                  .special_register_id = {object_name}.{field.name}.value.id,
                  .value_availability = special_register_availability(info),
                  .value_name = {object_name}.{field.name}.value.spelling,
                  .locations = {object_name}.{field.name}.locs,
                }};
              }}()"""
    if field.value_cpp_type == "ResolvedSymbolRef":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Symbol")},
                  .immediate_type = std::nullopt,
                  .register_type = std::nullopt,
                  .value_availability = {object_name}.{field.name}.value.address_availability,
                  .value_name = {object_name}.{field.name}.value.spelling,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedAddress":
        return f"""              [&]() -> OperandView {{
                const auto* symbol = std::get_if<ResolvedSymbolRef>(
                    &{object_name}.{field.name}.value.base);
                std::optional<MemoryStateSpace> effective_state_space;
                ParameterDirection parameter_direction = ParameterDirection::None;
                if (symbol != nullptr && symbol->address_state_space) {{
                  // Preserve the declaration-derived effective space. In
                  // particular, device parameters may produce local rather
                  // than declaration-space addresses in other instructions.
                  switch (*symbol->address_state_space) {{
                    case syntax_ast::AstStateSpace::Global:
                      effective_state_space = MemoryStateSpace::Global;
                      break;
                    case syntax_ast::AstStateSpace::Shared:
                      effective_state_space = MemoryStateSpace::Shared;
                      break;
                    case syntax_ast::AstStateSpace::Local:
                      effective_state_space = MemoryStateSpace::Local;
                      break;
                    case syntax_ast::AstStateSpace::Parameter:
                      effective_state_space = MemoryStateSpace::Parameter;
                      break;
                    case syntax_ast::AstStateSpace::Constant:
                      effective_state_space = MemoryStateSpace::Constant;
                      break;
                    case syntax_ast::AstStateSpace::Register:
                      break;
                  }}
                }}
                if (symbol != nullptr && symbol->declaration_kind) {{
                  if (*symbol->declaration_kind ==
                      binding::SymbolKind::InputParameter) {{
                    parameter_direction = ParameterDirection::Input;
                  }} else if (*symbol->declaration_kind ==
                             binding::SymbolKind::ReturnParameter) {{
                    parameter_direction = ParameterDirection::Return;
                  }} else if (*symbol->declaration_kind ==
                             binding::SymbolKind::CallParameter) {{
                    parameter_direction = ParameterDirection::CallArgument;
                  }}
                }}
                std::optional<uint64_t> address_alignment;
                const auto low_bit = [](uint64_t value) {{
                  return value == 0 ? uint64_t{{0}} : value & (~value + 1);
                }};
                if (symbol != nullptr) {{
                  address_alignment = symbol->address_alignment;
                }} else if (const auto* immediate = std::get_if<ResolvedImmediate>(
                               &{object_name}.{field.name}.value.base)) {{
                  address_alignment = low_bit(immediate->bits);
                }}
                if (address_alignment && {object_name}.{field.name}.value.offset) {{
                  const uint64_t offset_alignment = low_bit(
                      {object_name}.{field.name}.value.offset->value.bits);
                  if (offset_alignment != 0 &&
                      (*address_alignment == 0 || offset_alignment < *address_alignment))
                    address_alignment = offset_alignment;
                }}
                // Register, immediate, and unresolved standalone address
                // bases remain unknown; spelling is not semantic evidence.
                return OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Address")},
                  .immediate_type = std::nullopt,
                  .register_type = std::nullopt,
                  .address_state_space = effective_state_space,
                  .address_alignment = address_alignment,
                  .enclosing_function_kind =
                      {object_name}.{field.name}.value.enclosing_function_kind,
                  .parameter_direction = parameter_direction,
                  .parameter_qualifier =
                      {object_name}.{field.name}.value.parameter_qualifier,
                  .locations = {object_name}.{field.name}.locs,
                }};
              }}()"""
    if field.value_cpp_type == "RegOrImm":
        return f"""              [&]() -> OperandView {{
                if (const auto* immediate =
                        std::get_if<ResolvedImmediate>(&{object_name}.{field.name}.value)) {{
                  return OperandView{{
                      .field_id = "{field.name}",
                      .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Immediate")},
                      .immediate_type = immediate->type,
                      .immediate_bits = immediate->bits,
                      .immediate_is_negative = immediate->is_negative,
                      .register_type = std::nullopt,
                      .locations = {object_name}.{field.name}.locs,
                  }};
                }}
                const auto& register_ref =
                    std::get<ResolvedRegisterRef>({object_name}.{field.name}.value);
                return OperandView{{
                    .field_id = "{field.name}",
                    .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Register")},
                    .immediate_type = std::nullopt,
                    .register_type = register_ref.declared_type,
                    .locations = {object_name}.{field.name}.locs,
                }};
              }}()"""
    if field.value_cpp_type == "ResolvedMovSource":
        return f"""              [&]() -> OperandView {{
                if (const auto* immediate =
                        std::get_if<ResolvedImmediate>(&{object_name}.{field.name}.value)) {{
                  return OperandView{{
                      .field_id = "{field.name}",
                      .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Immediate")},
                      .immediate_type = immediate->type,
                      .immediate_bits = immediate->bits,
                      .immediate_is_negative = immediate->is_negative,
                      .register_type = std::nullopt,
                      .locations = {object_name}.{field.name}.locs,
                  }};
                }}
                if (const auto* register_ref =
                        std::get_if<ResolvedRegisterRef>(&{object_name}.{field.name}.value)) {{
                  return OperandView{{
                      .field_id = "{field.name}",
                      .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Register")},
                      .immediate_type = std::nullopt,
                      .register_type = register_ref->declared_type,
                      .locations = {object_name}.{field.name}.locs,
                  }};
                }}
                if (const auto* special_register =
                        std::get_if<ResolvedSpecialRegisterRef>(
                            &{object_name}.{field.name}.value)) {{
                  const auto info =
                      base::metadata(special_register->id);
                  return OperandView{{
                      .field_id = "{field.name}",
                      .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "SpecialRegister")},
                      .immediate_type = std::nullopt,
                      .register_type = std::nullopt,
                      .special_register_type = info.element_type,
                      .special_register_id = special_register->id,
                      .value_availability = special_register_availability(info),
                      .value_name = special_register->spelling,
                      .locations = {object_name}.{field.name}.locs,
                  }};
                }}
                if (const auto* function = std::get_if<ResolvedFunctionRef>(
                        &{object_name}.{field.name}.value)) {{
                  return OperandView{{
                      .field_id = "{field.name}",
                      .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Symbol")},
                      .immediate_type = std::nullopt,
                      .register_type = std::nullopt,
                      .value_availability = function->address_availability,
                      .value_name = function->spelling,
                      .locations = {object_name}.{field.name}.locs,
                  }};
                }}
                if (const auto* symbol = std::get_if<ResolvedSymbolRef>(
                        &{object_name}.{field.name}.value)) {{
                  return OperandView{{
                      .field_id = "{field.name}",
                      .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Symbol")},
                      .immediate_type = std::nullopt,
                      .register_type = std::nullopt,
                      .value_availability = symbol->address_availability,
                      .value_name = symbol->spelling,
                      .locations = {object_name}.{field.name}.locs,
                  }};
                }}
                // An offset address keeps its value requirements on the
                // symbol base, so expose those requirements through the same
                // operand view used for a direct symbol source.
                const auto& address =
                    std::get<ResolvedAddress>({object_name}.{field.name}.value);
                const auto* symbol =
                    std::get_if<ResolvedSymbolRef>(&address.base);
                return OperandView{{
                    .field_id = "{field.name}",
                    .actual_shape = {cpp_value(CppDomain.RESOLVED_OPERAND_SHAPES, "Address")},
                    .immediate_type = std::nullopt,
                    .register_type = std::nullopt,
                    .value_availability =
                        symbol == nullptr ? std::nullopt
                                          : symbol->address_availability,
                    .value_name =
                        symbol == nullptr ? std::string_view{{}}
                                          : std::string_view{{symbol->spelling}},
                    .locations = {object_name}.{field.name}.locs,
                }};
              }}()"""
    raise ValueError(
        f"operand field {field.name!r}: unsupported checker view type "
        f"{field.value_cpp_type!r}"
    )


def _emit_resolve_field_initializer(field: ResolvedField) -> str:
    accessor = (
        "resolved_modifier"
        if field.origin.value == "modifier"
        else "resolved_operand"
    )
    return (
        f".{field.name} = {accessor}<{field.value_cpp_type}>(*fields, "
        f'"{field.name}"),'
    )


def _emit_resolved_variant_definition(variant: ResolvedVariant) -> str:
    modifier_fields = "\n".join(
        _emit_resolved_field(field) for field in variant.modifier_fields
    )
    if len(variant.operand_layouts) == 1:
        operand_fields = "\n".join(
            _emit_resolved_field(field) for field in variant.operand_layouts[0].fields
        )
        body = f"{modifier_fields}\n{operand_fields}"
    else:
        layout_structs = "\n\n".join(
            _emit_operand_layout_definition(layout)
            for layout in variant.operand_layouts
        )
        alternatives = ", ".join(
            f"{layout.cpp_name}Operands" for layout in variant.operand_layouts
        )
        body = f"""{modifier_fields}

{layout_structs}

    using Operands = std::variant<{alternatives}>;
    Operands operands;"""

    return f"""\
  // YAML: {variant.variant_id}
  struct {variant.cpp_name} {{
    ResolvedOperandLayoutTag operand_layout;
{body}
  }};"""


def _emit_operand_layout_definition(layout: ResolvedOperandLayout) -> str:
    fields = "\n".join(_emit_resolved_field(field) for field in layout.fields)
    return f"""    // YAML operand layout: {layout.layout_id}
    struct {layout.cpp_name}Operands {{
{fields}
    }};"""


def _emit_resolved_field(field: ResolvedField) -> str:
    if field.storage is ResolvedFieldStorage.STATIC_CONSTANT:
        return (
            f"    inline static constexpr {field.cpp_type} {field.name} = "
            f"{field.cpp_constant_expr};"
        )
    return f"    {field.cpp_type} {field.name};"


def _validate_unique_cpp_names(instructions: tuple[ResolvedInstruction, ...]) -> None:
    seen: set[str] = set()
    for instruction in instructions:
        if instruction.cpp_name in seen:
            raise ValueError(
                f"multiple resolved instructions map to C++ type "
                f"{instruction.cpp_name!r}"
            )
        seen.add(instruction.cpp_name)
