"""Generate C++ Resolved IR instruction definitions."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from code_gen.database import CodegenDatabase
from ir.resolved_ir import (
    ResolvedField,
    ResolvedInstruction,
    ResolvedVariant,
    from_instruction_spec,
)


def generate_resolved_ir_header(
    database: CodegenDatabase,
    *,
    output_path: Path,
) -> None:
    """Generate a self-contained public Resolved IR header.

    The generated header may be included directly.  It includes the resolved
    IR foundation header, which supplies ``WithLocs``, resolved operand
    primitives, and ``check_end`` descriptors, then declares the generated
    instruction types in ``ptx_frontend::resolved_ir``.
    """

    instructions = tuple(
        from_instruction_spec(instruction) for instruction in database.instructions
    )
    _validate_unique_cpp_names(instructions)

    definitions = "\n\n".join(
        emit_resolved_instruction_definition(instruction)
        for instruction in instructions
    )
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
// Generated at: {datetime.now(timezone.utc).isoformat()}
#pragma once

#include "ptx_ir/resolved/ptx_resolved_ir.hpp"

namespace ptx_frontend::resolved_ir {{

{definitions}

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def emit_resolved_instruction_definition(instruction: ResolvedInstruction) -> str:
    """Emit one opcode-level C++ resolved instruction struct."""

    variant_names = ", ".join(variant.cpp_name for variant in instruction.variants)
    variant_enum_values = "\n".join(
        f"    {variant.cpp_name}," for variant in instruction.variants
    )
    variant_definitions = "\n\n".join(
        _emit_resolved_variant_definition(variant) for variant in instruction.variants
    )

    return f"""\
struct {instruction.cpp_name} {{
  enum class VariantType {{
{variant_enum_values}
  }};

{variant_definitions}

  using Variant = std::variant<{variant_names}>;
  Variant variant;

  bool check();
  static const check_end::InstructionDescriptor& get_inst_descriptor() noexcept;
}};"""


def _emit_resolved_variant_definition(variant: ResolvedVariant) -> str:
    fields = "\n".join(_emit_resolved_field(field) for field in variant.fields)

    return f"""\
  // YAML: {variant.variant_id}
  struct {variant.cpp_name} {{
{fields}
  }};"""


def _emit_resolved_field(field: ResolvedField) -> str:
    return f"    {field.cpp_type} {field.name};"


def _validate_unique_cpp_names(instructions: tuple[ResolvedInstruction, ...]) -> None:
    seen: set[str] = set()
    for instruction in instructions:
        if instruction.cpp_name in seen:
            raise ValueError(
                f"multiple resolved instructions map to C++ type "
                f"{instruction.cpp_name!r}"
            )
        seen.add(instruction.cpp_name)
