"""Generate C++ Resolved IR instruction definitions."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from code_gen.database import CodegenDatabase
from ir.resolved_ir import (
    ResolvedField,
    ResolvedFieldStorage,
    ResolvedInstruction,
    ResolvedVariant,
    from_instruction_spec,
    ResolvedOperandLayout
)


def generate_resolved_ir_header(
    database: CodegenDatabase,
    *,
    output_path: Path,
) -> None:
    """Generate a self-contained public Resolved IR header.

    The generated header may be included directly.  It includes the resolved
    IR foundation header, which supplies ``WithLocs``, resolved operand
    primitives, and ``check_end`` descriptors, then declares the generated
    instruction types in ``ptx_frontend::resolved_ir``.
    """

    instructions = tuple(
        from_instruction_spec(instruction) for instruction in database.instructions
    )
    _validate_unique_cpp_names(instructions)

    definitions = "\n\n".join(
        emit_resolved_instruction_definition(instruction)
        for instruction in instructions
    )
    check_specializations = "\n\n".join(
        _emit_check_specialization(instruction) for instruction in instructions
    )
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
// Generated at: {datetime.now(timezone.utc).isoformat()}
#pragma once

#include "ptx_ir/resolved/ptx_resolved_ir.hpp"
#include "ptx_ir/ptx_resolved_ir_checker.hpp"

namespace ptx_frontend::resolved_ir {{

{definitions}

namespace checker {{

{check_specializations}

}}  // namespace checker

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def emit_resolved_instruction_definition(instruction: ResolvedInstruction) -> str:
    """Emit one opcode-level C++ resolved instruction struct."""

    variant_names = ", ".join(variant.cpp_name for variant in instruction.variants)
    variant_enum_values = "\n".join(
        f"    {variant.cpp_name}," for variant in instruction.variants
    )
    variant_definitions = "\n\n".join(
        _emit_resolved_variant_definition(variant) for variant in instruction.variants
    )

    definition = f"""\
struct {instruction.cpp_name} {{
  enum class VariantType {{
{variant_enum_values}
  }};

{variant_definitions}

  using Variant = std::variant<{variant_names}>;
  Variant variant;

  static const check_end::SyntaxInstructionDescriptor&
  get_syntax_descriptor() noexcept;
  static const check_end::ResolvedInstructionDescriptor&
  get_resolved_descriptor() noexcept;
  static const checker::InstructionDescriptor&
  get_checker_descriptor() noexcept;
}};"""
    return (
        f"{definition}\n\n{_emit_resolve_specialization(instruction)}"
    )


def _emit_resolve_specialization(instruction: ResolvedInstruction) -> str:
    variant_cases = "\n".join(
        _emit_resolve_variant_case(instruction, variant)
        for variant in instruction.variants
    )
    return f"""\
template <>
inline std::expected<{instruction.cpp_name}, ResolveDiagnostic>
resolve<{instruction.cpp_name}>(const syntax_ast::AstInstruction& ast) {{
  const auto selected_variant = selectVariant<{instruction.cpp_name}>(ast);
  if (!selected_variant)
    return std::unexpected(selected_variant.error());

  const auto fields = resolve_fields(
      ast, {instruction.cpp_name}::get_syntax_descriptor(),
      {instruction.cpp_name}::get_resolved_descriptor(),
      magic_enum::enum_name(*selected_variant));
  if (!fields)
    return std::unexpected(fields.error());

{variant_cases}

  throw ResolveException("Unknown {instruction.cpp_name} variant in resolved field table.");
}}"""


def _emit_resolve_variant_case(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
) -> str:
    if len(variant.operand_layouts) == 1:
        fields = "\n".join(
            "          " + _emit_resolve_field_initializer(field)
            for field in variant.modifier_fields + variant.operand_layouts[0].fields
            if field.storage is ResolvedFieldStorage.INSTANCE
        )
        return f"""\
  if (fields->variant_name == "{variant.cpp_name}") {{
    return {instruction.cpp_name}{{.variant = {instruction.cpp_name}::{variant.cpp_name}{{
                   .operand_layout = fields->operand_layout,
{fields}
    }}}};
  }}"""

    layout_cases = "\n".join(
        _emit_resolve_multi_layout_case(instruction, variant, index)
        for index, _ in enumerate(variant.operand_layouts)
    )
    fields = "\n".join(
        "          " + _emit_resolve_field_initializer(field)
        for field in variant.modifier_fields
        if field.storage is ResolvedFieldStorage.INSTANCE
    )
    return f"""\
  if (fields->variant_name == "{variant.cpp_name}") {{
{layout_cases}
    throw ResolveException("Unknown {instruction.cpp_name}::{variant.cpp_name} operand layout.");
  }}"""


def _emit_resolve_multi_layout_case(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    layout_index: int,
) -> str:
    layout = variant.operand_layouts[layout_index]
    modifier_fields = "\n".join(
        "              " + _emit_resolve_field_initializer(field)
        for field in variant.modifier_fields
        if field.storage is ResolvedFieldStorage.INSTANCE
    )
    operand_fields = "\n".join(
        "                  " + _emit_resolve_field_initializer(field)
        for field in layout.fields
        if field.storage is ResolvedFieldStorage.INSTANCE
    )
    return f"""    if (fields->operand_layout.value == {layout_index}) {{
      return {instruction.cpp_name}{{.variant = {instruction.cpp_name}::{variant.cpp_name}{{
              .operand_layout = fields->operand_layout,
{modifier_fields}
              .operands = {instruction.cpp_name}::{variant.cpp_name}::Operands{{
                  {instruction.cpp_name}::{variant.cpp_name}::{layout.cpp_name}Operands{{
{operand_fields}
                  }},
              }},
          }}}};
    }}"""


def _emit_check_specialization(instruction: ResolvedInstruction) -> str:
    variant_lambdas = "\n\n".join(
        _emit_check_variant_lambda(instruction, index, variant)
        for index, variant in enumerate(instruction.variants)
    )
    visitor_lambdas = ", ".join(
        _check_lambda_name(instruction, variant) for variant in instruction.variants
    )
    return f"""\
template <>
inline CheckResult check<{instruction.cpp_name}>(
    const {instruction.cpp_name}& instruction, const Context& context) {{
{variant_lambdas}

  return std::visit(detail::Overloaded{{{visitor_lambdas}}}, instruction.variant);
}}"""


def _emit_check_variant_lambda(
    instruction: ResolvedInstruction,
    variant_index: int,
    variant: ResolvedVariant,
) -> str:
    modifier_fields = [
        field for field in variant.modifier_fields if field.origin.value == "modifier"
    ]
    modifier_views = ",\n".join(
        _emit_check_modifier_view(instruction, variant, field)
        for field in modifier_fields
    )
    modifier_value_views = ",\n".join(
        _emit_check_modifier_value_view(instruction, variant, field)
        for field in modifier_fields
    )
    operand_check = _emit_check_operand_dispatch(
        instruction, variant, variant_index, modifier_fields
    )
    lambda_name = _check_lambda_name(instruction, variant)
    return f"""  const auto {lambda_name} =
      [&](const {instruction.cpp_name}::{variant.cpp_name}& selected) -> CheckResult {{
          const std::array<FieldView, {len(modifier_fields)}> fields = {{{{
{modifier_views}
          }}}};
          const std::array<ModifierValueView, {len(modifier_fields)}> modifier_values = {{{{
{modifier_value_views}
          }}}};
          CheckDiagnostics diagnostics;
          const auto common = check_common(
              {instruction.cpp_name}::get_checker_descriptor(), "{variant.cpp_name}",
              context);
          if (!common) {{
            diagnostics.insert(diagnostics.end(), common.error().begin(),
                               common.error().end());
          }}
          const auto modifier_availability = check_modifier_value_availability(
              {instruction.cpp_name}::get_checker_descriptor().variants[{variant_index}]
                  .modifier_value_availabilities,
              modifier_values, context);
          if (!modifier_availability) {{
            diagnostics.insert(diagnostics.end(),
                               modifier_availability.error().begin(),
                               modifier_availability.error().end());
          }}
{operand_check}
          if (diagnostics.empty())
            return CheckResult{{}};
          return std::unexpected(std::move(diagnostics));
      }};
  static_assert(detail::VariantCheckFunction<
      decltype({lambda_name}), {instruction.cpp_name}::{variant.cpp_name}>);"""


def _emit_check_operand_dispatch(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    variant_index: int,
    modifier_fields: list[ResolvedField],
) -> str:
    layouts_expr = (
        f"{instruction.cpp_name}::get_resolved_descriptor().variants[{variant_index}]"
        ".operand_layouts"
    )
    checker_variant_expr = (
        f"{instruction.cpp_name}::get_checker_descriptor().variants[{variant_index}]"
    )
    if len(variant.operand_layouts) == 1:
        operand_views = ",\n".join(
            _emit_check_operand_view(field, "selected")
            for field in variant.operand_layouts[0].fields
        )
        return f"""          const std::array<OperandView, {len(variant.operand_layouts[0].fields)}> operands = {{{{
{operand_views}
          }}}};
          const auto& layouts = {layouts_expr};
          const auto layout_check = check_operand_layout_tag(
              "{variant.cpp_name}", selected.operand_layout.value, layouts.size(),
              context);
          if (!layout_check) {{
            diagnostics.insert(diagnostics.end(), layout_check.error().begin(),
                               layout_check.error().end());
          }} else {{
            const auto availability_check = check_operand_layout_availability(
                {checker_variant_expr}, selected.operand_layout.value, context);
            if (!availability_check) {{
              diagnostics.insert(diagnostics.end(), availability_check.error().begin(),
                                 availability_check.error().end());
            }}
            const auto operand_check = check_operands(
                layouts[selected.operand_layout.value].bindings, fields, operands,
                context);
            if (!operand_check) {{
              diagnostics.insert(diagnostics.end(), operand_check.error().begin(),
                                 operand_check.error().end());
            }}
          }}"""

    layout_lambdas = "\n\n".join(
        _emit_check_multi_layout_lambda(
            instruction, variant, variant_index, layout_index, modifier_fields
        )
        for layout_index, _ in enumerate(variant.operand_layouts)
    )
    visitor_lambdas = ", ".join(
        _check_layout_lambda_name(variant, layout) for layout in variant.operand_layouts
    )
    return f"""{layout_lambdas}

          const auto& layouts = {layouts_expr};
          const auto layout_check = check_operand_layout_tag(
              "{variant.cpp_name}", selected.operand_layout.value, layouts.size(),
              context);
          if (!layout_check) {{
            diagnostics.insert(diagnostics.end(), layout_check.error().begin(),
                               layout_check.error().end());
          }} else {{
            const auto availability_check = check_operand_layout_availability(
                {checker_variant_expr}, selected.operand_layout.value, context);
            if (!availability_check) {{
              diagnostics.insert(diagnostics.end(), availability_check.error().begin(),
                                 availability_check.error().end());
            }}
            const auto payload_check = std::visit(
                detail::Overloaded{{{visitor_lambdas}}}, selected.operands);
            if (!payload_check) {{
              diagnostics.insert(diagnostics.end(), payload_check.error().begin(),
                                 payload_check.error().end());
            }}
          }}"""


def _emit_check_multi_layout_lambda(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    variant_index: int,
    layout_index: int,
    modifier_fields: list[ResolvedField],
) -> str:
    layout = variant.operand_layouts[layout_index]
    lambda_name = _check_layout_lambda_name(variant, layout)
    operand_views = ",\n".join(
        _emit_check_operand_view(field, "payload") for field in layout.fields
    )
    return f"""          const auto {lambda_name} =
              [&](const {instruction.cpp_name}::{variant.cpp_name}::{layout.cpp_name}Operands& payload)
                  -> CheckResult {{
            if (selected.operand_layout.value != {layout_index}) {{
              return std::unexpected(CheckDiagnostics{{CheckDiagnostic{{
                  .kind = CheckDiagnosticKind::OperandLayoutPayloadMismatch,
                  .range = context.instruction_range,
                  .message = "Resolved operand-layout tag and payload alternative disagree.",
              }}}});
            }}
            const std::array<OperandView, {len(layout.fields)}> operands = {{{{
{operand_views}
            }}}};
            return check_operands(
                {instruction.cpp_name}::get_resolved_descriptor().variants[{variant_index}]
                    .operand_layouts[{layout_index}]
                    .bindings,
                fields, operands, context);
          }};
          static_assert(detail::VariantCheckFunction<
              decltype({lambda_name}),
              {instruction.cpp_name}::{variant.cpp_name}::{layout.cpp_name}Operands>);"""


def _check_layout_lambda_name(
    variant: ResolvedVariant, layout: ResolvedOperandLayout
) -> str:
    return f"check_{variant.variant_id}_{layout.layout_id}_operands"


def _check_lambda_name(
    instruction: ResolvedInstruction, variant: ResolvedVariant
) -> str:
    variant_suffix = variant.variant_id.removeprefix(f"{instruction.opcode}_")
    return f"check_{variant_suffix}"


def _emit_check_modifier_view(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    field: ResolvedField,
) -> str:
    if field.storage is ResolvedFieldStorage.STATIC_CONSTANT:
        scalar_type = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.value_cpp_type == "ScalarType"
            else "std::nullopt"
        )
        locations = "std::span<const SourceRange>{}"
    else:
        scalar_type = (
            f"selected.{field.name}.value"
            if field.value_cpp_type == "ScalarType"
            else "std::nullopt"
        )
        locations = f"selected.{field.name}.locs"
    return f"""              FieldView{{
                  .field_id = "{field.name}",
                  .scalar_type = {scalar_type},
                  .locations = {locations},
              }}"""


def _emit_check_modifier_value_view(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    field: ResolvedField,
) -> str:
    if field.value_cpp_type == "ScalarType":
        value_kind = "ModifierValueKind::ScalarType"
        bool_value = "false"
        scalar_type = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
    elif field.value_cpp_type == "bool":
        value_kind = "ModifierValueKind::Bool"
        bool_value = (
            f"{instruction.cpp_name}::{variant.cpp_name}::{field.name}"
            if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
            else f"selected.{field.name}.value"
        )
        scalar_type = "ScalarType::Invalid"
    else:
        raise ValueError(
            f"modifier field {field.name!r}: unsupported availability view type "
            f"{field.value_cpp_type!r}"
        )

    locations = (
        "std::span<const SourceRange>{}"
        if field.storage is ResolvedFieldStorage.STATIC_CONSTANT
        else f"selected.{field.name}.locs"
    )
    return f"""              ModifierValueView{{
                  .kind_id = "{field.source_name}",
                  .value_kind = {value_kind},
                  .bool_value = {bool_value},
                  .scalar_type = {scalar_type},
                  .is_present = true,
                  .locations = {locations},
              }}"""


def _emit_check_operand_view(field: ResolvedField, object_name: str) -> str:
    if field.value_cpp_type == "ResolvedRegisterRef":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = OperandShape::Register,
                  .immediate_type = std::nullopt,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedImmediate":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = OperandShape::Immediate,
                  .immediate_type = {object_name}.{field.name}.value.type,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "ResolvedPredicate":
        return f"""              OperandView{{
                  .field_id = "{field.name}",
                  .actual_shape = OperandShape::Predicate,
                  .immediate_type = std::nullopt,
                  .locations = {object_name}.{field.name}.locs,
              }}"""
    if field.value_cpp_type == "RegOrImm":
        return f"""              [&]() -> OperandView {{
                if (const auto* immediate =
                        std::get_if<ResolvedImmediate>(&{object_name}.{field.name}.value)) {{
                  return OperandView{{
                      .field_id = "{field.name}",
                      .actual_shape = OperandShape::Immediate,
                      .immediate_type = immediate->type,
                      .locations = {object_name}.{field.name}.locs,
                  }};
                }}
                return OperandView{{
                    .field_id = "{field.name}",
                    .actual_shape = OperandShape::Register,
                    .immediate_type = std::nullopt,
                    .locations = {object_name}.{field.name}.locs,
                }};
              }}()"""
    raise ValueError(
        f"operand field {field.name!r}: unsupported checker view type "
        f"{field.value_cpp_type!r}"
    )


def _emit_resolve_field_initializer(field: ResolvedField) -> str:
    accessor = (
        "resolved_modifier"
        if field.origin.value == "modifier"
        else "resolved_operand"
    )
    return (
        f".{field.name} = {accessor}<{field.value_cpp_type}>(*fields, "
        f'"{field.name}"),'
    )


def _emit_resolved_variant_definition(variant: ResolvedVariant) -> str:
    modifier_fields = "\n".join(
        _emit_resolved_field(field) for field in variant.modifier_fields
    )
    if len(variant.operand_layouts) == 1:
        operand_fields = "\n".join(
            _emit_resolved_field(field) for field in variant.operand_layouts[0].fields
        )
        body = f"{modifier_fields}\n{operand_fields}"
    else:
        layout_structs = "\n\n".join(
            _emit_operand_layout_definition(layout)
            for layout in variant.operand_layouts
        )
        alternatives = ", ".join(
            f"{layout.cpp_name}Operands" for layout in variant.operand_layouts
        )
        body = f"""{modifier_fields}

{layout_structs}

    using Operands = std::variant<{alternatives}>;
    Operands operands;"""

    return f"""\
  // YAML: {variant.variant_id}
  struct {variant.cpp_name} {{
    ResolvedOperandLayoutTag operand_layout;
{body}
  }};"""


def _emit_operand_layout_definition(layout: ResolvedOperandLayout) -> str:
    fields = "\n".join(_emit_resolved_field(field) for field in layout.fields)
    return f"""    // YAML operand layout: {layout.layout_id}
    struct {layout.cpp_name}Operands {{
{fields}
    }};"""


def _emit_resolved_field(field: ResolvedField) -> str:
    if field.storage is ResolvedFieldStorage.STATIC_CONSTANT:
        return (
            f"    inline static constexpr {field.cpp_type} {field.name} = "
            f"{field.cpp_constant_expr};"
        )
    return f"    {field.cpp_type} {field.name};"


def _validate_unique_cpp_names(instructions: tuple[ResolvedInstruction, ...]) -> None:
    seen: set[str] = set()
    for instruction in instructions:
        if instruction.cpp_name in seen:
            raise ValueError(
                f"multiple resolved instructions map to C++ type "
                f"{instruction.cpp_name!r}"
            )
        seen.add(instruction.cpp_name)
