"""Emit checker descriptor storage derived from resolved-IR YAML metadata."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from code_gen.database import CodegenDatabase
from ir.resolved_ir import ResolvedInstruction, ResolvedVariant, from_instruction_spec


def generate_resolved_checker_descriptor_source(
    database: CodegenDatabase,
    *,
    output_path: Path,
) -> None:
    """Generate private checker descriptor storage and instruction getters."""

    instructions = tuple(
        from_instruction_spec(instruction) for instruction in database.instructions
    )
    _validate_unique_cpp_names(instructions)
    implementations = "\n\n".join(
        _emit_instruction_descriptor(instruction) for instruction in instructions
    )
    content = f"""// Generated by python/scripts/gen_all.py. Do not edit.
// Generated at: {datetime.now(timezone.utc).isoformat()}

#include "ptx_ir/ptx_resolved_ir_checker.hpp"
#include "ptx_ir/resolved/ptx_resolved_ir.hpp"

namespace ptx_frontend::resolved_ir {{

{implementations}

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def _emit_instruction_descriptor(instruction: ResolvedInstruction) -> str:
    storage_name = f"{instruction.cpp_name}CheckerDescriptorStorage"
    variants = ",\n".join(
        _emit_variant_descriptor(variant) for variant in instruction.variants
    )
    return f"""namespace generated_detail {{

struct {storage_name} {{
  static constexpr std::array<checker::VariantDescriptor, {len(instruction.variants)}>
      variants = {{
{variants}
      }};

  static constexpr checker::InstructionDescriptor descriptor{{
      .opcode_name = "{instruction.opcode}",
      .variants = variants,
  }};
}};

}}  // namespace generated_detail

const checker::InstructionDescriptor&
{instruction.cpp_name}::get_checker_descriptor() noexcept {{
  return generated_detail::{storage_name}::descriptor;
}}"""


def _emit_variant_descriptor(variant: ResolvedVariant) -> str:
    availability = dict(variant.availability)
    minimum_ptx = _parse_ptx_version(availability.get("ptx", "0.0"))
    minimum_sm = int(availability.get("sm", 0))
    family = str(availability.get("family", ""))
    rule_id = variant.rule or ""
    return f"""          checker::VariantDescriptor{{
              .variant_name = "{variant.cpp_name}",
              .availability = {{
                  .minimum_ptx_version = {{{minimum_ptx[0]}, {minimum_ptx[1]}}},
                  .minimum_sm_version = {minimum_sm},
                  .required_family = "{family}",
              }},
              .rule_id = "{rule_id}",
          }}"""


def _parse_ptx_version(value: object) -> tuple[int, int]:
    text = str(value)
    pieces = text.split(".")
    if len(pieces) != 2 or not all(piece.isdecimal() for piece in pieces):
        raise ValueError(f"invalid PTX availability version {value!r}")
    major, minor = (int(piece) for piece in pieces)
    if not (0 <= major <= 0xFFFF and 0 <= minor <= 0xFFFF):
        raise ValueError(f"PTX availability version is out of range: {value!r}")
    return major, minor


def _validate_unique_cpp_names(instructions: tuple[ResolvedInstruction, ...]) -> None:
    seen: set[str] = set()
    for instruction in instructions:
        if instruction.cpp_name in seen:
            raise ValueError(
                f"multiple resolved instructions map to C++ type "
                f"{instruction.cpp_name!r}"
            )
        seen.add(instruction.cpp_name)
