from __future__ import annotations

from pathlib import Path
import sys
import tempfile
import unittest


REPO_ROOT = Path(__file__).resolve().parents[3]
PYTHON_ROOT = REPO_ROOT / "python"

if str(PYTHON_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_ROOT))


from code_gen.database import load_codegen_database
from code_gen.gen_resolved_ir import generate_resolved_ir_header
from ir.resolved_ir import ResolvedFieldOrigin, from_instruction_spec


class ResolvedIrBuildTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        database = load_codegen_database(
            spec_dir=REPO_ROOT / "instructions/ptx_spec",
        )
        add = next(
            instruction
            for instruction in database.instructions
            if instruction.opcode == "add"
        )
        cls.instruction = from_instruction_spec(add)

    def test_add_variant_names(self) -> None:
        self.assertEqual(self.instruction.opcode, "add")
        self.assertEqual(self.instruction.cpp_name, "Add")
        self.assertEqual(
            [variant.cpp_name for variant in self.instruction.variants],
            [
                "IntegerNoSat",
                "SatS32",
                "SimdNoSatSm90",
                "PackedOptionalSatSm120",
                "SatSm120",
            ],
        )

    def test_add_resolved_variant_fields(self) -> None:
        variants = {variant.cpp_name: variant for variant in self.instruction.variants}

        self.assertEqual(
            [
                (field.name, field.cpp_type, field.origin, field.type_expr)
                for field in variants["IntegerNoSat"].fields
            ],
            [
                ("type", "WithLocs<ScalarType>", ResolvedFieldOrigin.MODIFIER, None),
                ("dst", "WithLocs<ResolvedRegisterId>", ResolvedFieldOrigin.OPERAND, "$type"),
                ("src1", "WithLocs<RegOrImm>", ResolvedFieldOrigin.OPERAND, "$type"),
                ("src2", "WithLocs<RegOrImm>", ResolvedFieldOrigin.OPERAND, "$type"),
            ],
        )
        self.assertEqual(
            [field.name for field in variants["SatS32"].fields],
            ["dst", "src1", "src2"],
        )
        self.assertEqual(
            [
                (field.name, field.cpp_type, field.origin)
                for field in variants["PackedOptionalSatSm120"].fields
            ],
            [
                ("saturate", "WithLocs<bool>", ResolvedFieldOrigin.MODIFIER),
                ("type", "WithLocs<ScalarType>", ResolvedFieldOrigin.MODIFIER),
                ("dst", "WithLocs<ResolvedRegisterId>", ResolvedFieldOrigin.OPERAND),
                ("src1", "WithLocs<RegOrImm>", ResolvedFieldOrigin.OPERAND),
                ("src2", "WithLocs<RegOrImm>", ResolvedFieldOrigin.OPERAND),
            ],
        )

    def test_generate_resolved_ir_header(self) -> None:
        database = load_codegen_database(
            spec_dir=REPO_ROOT / "instructions/ptx_spec",
        )

        with tempfile.TemporaryDirectory() as directory:
            output_path = Path(directory) / "resolved_ir.gen.hpp"
            generate_resolved_ir_header(database, output_path=output_path)
            source = output_path.read_text(encoding="utf-8")

        self.assertTrue(
            source.startswith("// Generated by python/scripts/gen_all.py. Do not edit.")
        )
        self.assertIn("// Generated at: ", source)
        self.assertIn("#pragma once", source)
        self.assertIn('#include "ptx_ir/resolved/ptx_resolved_ir.hpp"', source)
        self.assertIn("namespace ptx_frontend::resolved_ir {", source)
        self.assertIn("struct Add {", source)
        self.assertIn("enum class VariantType {", source)
        self.assertIn("struct IntegerNoSat {", source)
        self.assertIn("WithLocs<ScalarType> type;", source)
        self.assertIn("WithLocs<bool> saturate;", source)
        self.assertIn("using Variant = std::variant<", source)
        self.assertIn(
            "static const check_end::InstructionDescriptor& "
            "get_inst_descriptor() noexcept;",
            source,
        )
        self.assertIn(
            "template <>\nstd::expected<Add, ResolveDiagnostic>\n"
            "resolve<Add>(const syntax_ast::AstInstruction& ast);",
            source,
        )
        self.assertIn("inline std::expected<Add, ResolveDiagnostic>", source)
        self.assertIn("resolve_fields(", source)
        self.assertIn("resolved_operand<RegOrImm>(*fields, \"src1\")", source)
        self.assertIn("}  // namespace ptx_frontend::resolved_ir", source)


if __name__ == "__main__":
    unittest.main()
