"""Semantic value categories used by resolved PTX fields."""

from enum import Enum


class ResolvedValueKind(Enum):
    """Semantic runtime value category produced for one resolved field."""

    BOOL = "Bool"
    SCALAR_TYPE = "ScalarType"
    ROUNDING_MODE = "RoundingMode"
    COMPARISON_OPERATOR = "ComparisonOperator"
    TEST_PROPERTY = "TestProperty"
    BOOLEAN_OPERATOR = "BooleanOperator"
    CACHE_OPERATOR = "CacheOperator"
    EVICTION_PRIORITY = "EvictionPriority"
    PREFETCH_SIZE = "PrefetchSize"
    MEMORY_CONSISTENCY = "MemoryConsistency"
    MEMORY_SCOPE = "MemoryScope"
    VECTOR_ARITY = "VectorArity"
    MEMORY_STATE_SPACE = "MemoryStateSpace"
    MBARRIER_PHASE_TYPE = "MbarrierPhaseType"
    MBARRIER_LAYOUT = "MbarrierLayout"
    ASYNC_PROXY_KIND = "AsyncProxyKind"
    PROXY_KIND_PAIR = "ProxyKindPair"

    REGISTER = "Register"
    PREDICATE = "Predicate"
    PREDICATE_OR_SINK = "PredicateOrSink"
    PREDICATE_SOURCE = "PredicateSource"
    IMMEDIATE = "Immediate"
    REG_OR_IMM = "RegOrImm"
    REGISTER_OR_SINK = "RegisterOrSink"
    MOV_SOURCE = "MovSource"
    VECTOR_REGISTER = "VectorRegister"
    VECTOR_SPECIAL_REGISTER = "VectorSpecialRegister"
    BRANCH_TARGET = "BranchTarget"
    SPECIAL_REGISTER = "SpecialRegister"
    SYMBOL = "Symbol"
    ADDRESS = "Address"
    REGISTER_VECTOR = "RegisterVector"
    TENSOR_COORDINATE = "TensorCoordinate"
    DIRECT_CALL_TARGET = "DirectCallTarget"
    INDIRECT_CALLEE = "IndirectCallee"
    BRANCH_TARGET_SET = "BranchTargetSet"
    CALL_RETURN_PARAMETER = "CallReturnParameter"
    CALL_ARGUMENTS = "CallArguments"
    SHFL_DESTINATION = "ShflDestination"
    PREDICATE_PAIR = "PredicatePair"
    PREDICATE_PAIR_OR_SINK = "PredicatePairOrSink"
    MBARRIER_STATE_TOKEN = "MbarrierStateToken"
