"""Emit one private implementation source for each resolved opcode."""

from __future__ import annotations

from pathlib import Path

from ptx_frontend.base.utils import generated_at_comment
from ptx_frontend.code_gen.context import GenerationContext
from ptx_frontend.ir.syntax_ast import from_InstructionSpec

from .checker_descriptors import (
    _emit_instruction_descriptor_getter as emit_checker_getter,
    _emit_instruction_descriptor_storage as emit_checker_storage,
)
from .resolved_checker import emit_check_specialization
from .resolved_descriptors import (
    _emit_resolved_descriptor_getter as emit_resolved_getter,
    _emit_resolved_descriptor_storage as emit_resolved_storage,
)
from .resolved_resolver import emit_resolve_specialization
from .syntax_descriptors import (
    _emit_instruction_descriptor_getter as emit_syntax_getter,
    _emit_instruction_descriptor_storage as emit_syntax_storage,
)


def emit_owned_bridge(cpp_name: str, opcode: str) -> str:
    """Emit the exact-type owner table and resolver beside the opcode definitions."""
    return f"""\\
/** Box a typed {opcode} payload without materializing the outer instruction union. */
OwnedInstruction box_instruction({cpp_name} value) {{
  static const detail::OwnedInstructionOps ops{{
      .type = typeid({cpp_name}),
      .destroy = [](void* payload) noexcept {{ delete static_cast<{cpp_name}*>(payload); }},
      .clone = [](const void* payload) -> void* {{
        return new {cpp_name}(*static_cast<const {cpp_name}*>(payload));
      }},
      .opcode = "{opcode}",
      .check = [](const void* payload, const checker::Context& context) {{
        return checker::check(*static_cast<const {cpp_name}*>(payload), context);
      }},
      .references = [](const void* payload, detail::OwnedReferenceSink sink) {{
        detail::visit_instruction_references(
            *static_cast<const {cpp_name}*>(payload),
            [&](const auto& value, std::span<const SourceRange> locations,
                checker::AddressSymbolResolutionPolicy policy) {{
              static_assert(detail::OwnedReferencePayload<
                  std::remove_cvref_t<decltype(value)>>);
              sink.accept(sink.state, detail::OwnedReferenceView{{
                  .type = typeid(value),
                  .payload = &value,
                  .locations = locations,
                  .address_policy = policy,
              }});
            }});
      }},
  }};
  return detail::OwnerAccess::adopt(new {cpp_name}(std::move(value)), &ops);
}}

/** Resolve {opcode} using the existing typed resolver and retain its payload. */
std::expected<OwnedInstruction, ResolveDiagnostic> resolve_owned_{cpp_name}(
    const syntax_ast::AstInstruction& ast, const ResolveContext* context) {{
  auto resolved = resolve<{cpp_name}>(ast, context);
  if (!resolved)
    return std::unexpected(std::move(resolved.error()));
  return box_instruction(std::move(*resolved));
}}
"""


def generate_resolved_ir_opcode_source(
    context: GenerationContext,
    *,
    category: str,
    opcode: str,
    output_path: Path,
) -> None:
    """Write an opcode's three descriptors and resolver/checker definitions."""

    entries = tuple(
        entry for entry in context.entries
        if entry.specification.codegen_category == category
        and entry.specification.opcode == opcode
    )
    if len(entries) != 1:
        raise ValueError(f"expected one opcode {opcode!r} in category {category!r}")
    entry = entries[0]
    instruction = entry.resolved
    backend = context.backend
    syntax_descriptor = from_InstructionSpec(entry.specification)
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include <ptx_frontend/resolved_ir/model/{category}/{opcode}.gen.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_resolution_detail.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_checker_support.hpp>
#include <ptx_frontend/resolved_ir/ptx_owned_instruction.hpp>
#include <typeinfo>
#include <utility>

namespace ptx_frontend::resolved_ir {{

namespace {{

{emit_syntax_storage(syntax_descriptor, backend, cpp_name=entry.cpp_name)}

}}  // namespace

{emit_syntax_getter(cpp_name=entry.cpp_name)}

namespace generated_detail {{

{emit_resolved_storage(instruction, backend)}

{emit_checker_storage(instruction, backend)}

}}  // namespace generated_detail

{emit_resolved_getter(instruction)}

{emit_checker_getter(instruction)}

{emit_resolve_specialization(instruction, backend)}

namespace checker {{

{emit_check_specialization(instruction, backend)}

}}  // namespace checker

{emit_owned_bridge(instruction.cpp_name, instruction.opcode)}

}}  // namespace ptx_frontend::resolved_ir
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def generate_resolved_ir_category_source(
    context: GenerationContext,
    *,
    category: str,
    output_path: Path,
) -> None:
    """Render a category-wide definition view for existing emitter checks."""

    instructions = tuple(
        entry.resolved for entry in context.entries
        if entry.specification.codegen_category == category
    )
    if not instructions:
        raise ValueError(f"instruction category {category!r} is empty")
    resolve_definitions = "\n\n".join(
        emit_resolve_specialization(instruction, context.backend)
        for instruction in instructions
    )
    check_definitions = "\n\n".join(
        emit_check_specialization(instruction, context.backend)
        for instruction in instructions
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include <ptx_frontend/resolved_ir/ptx_resolved_ir_resolution_detail.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_checker_support.hpp>
#include <ptx_frontend/resolved_ir/checker/{category}.gen.hpp>

namespace ptx_frontend::resolved_ir {{

{resolve_definitions}

namespace checker {{

{check_definitions}

}}  // namespace checker

}}  // namespace ptx_frontend::resolved_ir
""",
        encoding="utf-8",
    )
