"""Emit category-partitioned resolver and checker specialization sources."""

from __future__ import annotations

from pathlib import Path

from ptx_frontend.base.utils import generated_at_comment
from ptx_frontend.code_gen.context import GenerationContext
from ptx_frontend.ir.resolved_ir import ResolvedInstruction

from .resolved_checker import emit_check_specialization
from .resolved_resolver import emit_resolve_specialization


def generate_resolved_ir_category_source(
    context: GenerationContext,
    *,
    category: str,
    output_path: Path,
) -> None:
    """Generate all resolver and checker specializations for one category."""

    instructions = tuple(
        entry.resolved
        for entry in context.entries
        if entry.specification.codegen_category == category
    )
    if not instructions:
        raise ValueError(f"instruction category {category!r} is empty")

    _write_resolved_ir_source(
        context,
        category=category,
        instructions=instructions,
        output_path=output_path,
        opcodes=None,
    )


def generate_resolved_ir_group_source(
    context: GenerationContext,
    *,
    category: str,
    opcodes: tuple[str, ...],
    output_path: Path,
) -> None:
    """Generate one stable source group with only its member opcode leaves."""

    by_opcode = {
        entry.specification.opcode: entry.resolved
        for entry in context.entries
        if entry.specification.codegen_category == category
    }
    if len(opcodes) != len(set(opcodes)) or any(
        opcode not in by_opcode for opcode in opcodes
    ):
        raise ValueError(
            f"invalid opcode group for instruction category {category!r}"
        )

    _write_resolved_ir_source(
        context,
        category=category,
        instructions=tuple(by_opcode[opcode] for opcode in opcodes),
        output_path=output_path,
        opcodes=opcodes,
    )


def _write_resolved_ir_source(
    context: GenerationContext,
    *,
    category: str,
    instructions: tuple[ResolvedInstruction, ...],
    output_path: Path,
    opcodes: tuple[str, ...] | None,
) -> None:
    """Write one source with matching declaration headers and definitions."""

    resolve_definitions = "\n\n".join(
        emit_resolve_specialization(instruction, context.backend)
        for instruction in instructions
    )
    check_definitions = "\n\n".join(
        emit_check_specialization(instruction, context.backend)
        for instruction in instructions
    )
    if opcodes is None:
        declaration_includes = (
            f"#include <ptx_frontend/resolved_ir/checker/{category}.gen.hpp>\n"
            f"#include <ptx_frontend/resolved_ir/resolution/{category}.gen.hpp>"
        )
    else:
        declaration_includes = "\n".join(
            f"#include <ptx_frontend/resolved_ir/model/{category}/{opcode}/{kind}.gen.hpp>"
            for opcode in opcodes
            for kind in ("checker", "resolution")
        )
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include <ptx_frontend/resolved_ir/ptx_resolved_ir_checker_support.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_resolution_detail.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_resolution_support.hpp>
{declaration_includes}

namespace ptx_frontend::resolved_ir {{

{resolve_definitions}

namespace checker {{

{check_definitions}

}}  // namespace checker

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
