"""Emit resolution dispatch and shared instruction-reference helpers."""

from __future__ import annotations

from .resolved_validation import validate_unique_cpp_names

from pathlib import Path

from ptx_frontend.base.utils import generated_at_comment
from ptx_frontend.code_gen.context import GenerationContext
from ptx_frontend.code_gen.resolved_field_names import field_value_cpp_type
from ptx_frontend.ir.resolved_ir import ResolvedField, ResolvedInstruction, ResolvedValueKind
from ptx_frontend.spec.model import CodegenUnit

_REFERENCE_VALUE_KINDS = frozenset(
    {
        ResolvedValueKind.REGISTER,
        ResolvedValueKind.MBARRIER_STATE_TOKEN,
        ResolvedValueKind.REGISTER_OR_SINK,
        ResolvedValueKind.REG_OR_IMM,
        ResolvedValueKind.SHFL_DESTINATION,
        ResolvedValueKind.PREDICATE_PAIR,
        ResolvedValueKind.PREDICATE_PAIR_OR_SINK,
        ResolvedValueKind.PREDICATE_OR_SINK,
        ResolvedValueKind.MOV_SOURCE,
        ResolvedValueKind.PREDICATE,
        ResolvedValueKind.PREDICATE_SOURCE,
        ResolvedValueKind.BRANCH_TARGET,
        ResolvedValueKind.BRANCH_TARGET_SET,
        ResolvedValueKind.VECTOR_REGISTER,
        ResolvedValueKind.SYMBOL,
        ResolvedValueKind.ADDRESS,
        ResolvedValueKind.REGISTER_VECTOR,
        ResolvedValueKind.TENSOR_COORDINATE,
        ResolvedValueKind.DIRECT_CALL_TARGET,
        ResolvedValueKind.INDIRECT_CALLEE,
        ResolvedValueKind.CALL_RETURN_PARAMETER,
        ResolvedValueKind.CALL_ARGUMENTS,
    }
)

_REFERENCE_FREE_VALUE_KINDS = frozenset(
    {
        ResolvedValueKind.BOOL,
        ResolvedValueKind.SCALAR_TYPE,
        ResolvedValueKind.ROUNDING_MODE,
        ResolvedValueKind.COMPARISON_OPERATOR,
        ResolvedValueKind.BOOLEAN_OPERATOR,
        ResolvedValueKind.CACHE_OPERATOR,
        ResolvedValueKind.EVICTION_PRIORITY,
        ResolvedValueKind.PREFETCH_SIZE,
        ResolvedValueKind.MEMORY_CONSISTENCY,
        ResolvedValueKind.MEMORY_SCOPE,
        ResolvedValueKind.VECTOR_ARITY,
        ResolvedValueKind.MEMORY_STATE_SPACE,
        ResolvedValueKind.MBARRIER_PHASE_TYPE,
        ResolvedValueKind.MBARRIER_LAYOUT,
        ResolvedValueKind.ASYNC_PROXY_KIND,
        ResolvedValueKind.PROXY_KIND_PAIR,
        ResolvedValueKind.IMMEDIATE,
        ResolvedValueKind.SPECIAL_REGISTER,
        ResolvedValueKind.VECTOR_SPECIAL_REGISTER,
    }
)


def generate_resolved_dispatch_source(
    context: GenerationContext,
    *,
    output_path: Path,
) -> None:
    """Generate opcode-independent instruction resolution dispatch."""


    instructions = context.instructions
    validate_unique_cpp_names(instructions)
    branches = "\n\n".join(
        emit_resolved_dispatch_branch(instruction) for instruction in instructions
    )
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include <ptx_frontend/resolved_ir/ptx_resolved_ir.hpp>

#include <utility>

namespace ptx_frontend::resolved_ir {{

namespace {{

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolve_instruction(const syntax_ast::AstInstruction& ast,
                    const ResolveContext* context) {{
{branches}

  return std::unexpected(ResolveDiagnostic{{
      .range = ast.opcode.syntax.range,
      .message = "Unknown PTX opcode '" + ast.opcode.syntax.text + "'.",
  }});
}}

}}  // namespace

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolveInstruction(const syntax_ast::AstInstruction& ast) {{
  return resolve_instruction(ast, nullptr);
}}

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolveInstruction(const syntax_ast::AstInstruction& ast,
                   const ResolveContext& context) {{
  return resolve_instruction(ast, &context);
}}

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def emit_resolved_instruction_union(
    instructions: tuple[ResolvedInstruction, ...],
) -> str:
    """Emit the specification-derived instruction alternative union."""
    alternatives = ", ".join(instruction.cpp_name for instruction in instructions)
    return f"""\
using ResolvedInstruction = std::variant<{alternatives}>;
"""


def validate_reference_field_types(
    instructions: tuple[ResolvedInstruction, ...],
) -> None:
    """Require an explicit module-reference policy for every operand payload."""

    known = _REFERENCE_VALUE_KINDS | _REFERENCE_FREE_VALUE_KINDS
    for instruction in instructions:
        for variant in instruction.variants:
            for layout in variant.operand_layouts:
                for field in layout.fields:
                    if field.value_kind not in known:
                        raise ValueError(
                            "Resolved operand value kind needs an explicit "
                            f"module-reference policy: {field.value_kind!r}"
                        )


def _emit_reference_fields(
    fields: tuple[ResolvedField, ...],
    object_name: str,
) -> str:
    """Emit callbacks for only explicitly reference-bearing operand payloads."""

    return "\n".join(
        f"      visitor({object_name}.{field.name}.value, "
        f"{object_name}.{field.name}.locs);"
        for field in fields
        if field.value_kind in _REFERENCE_VALUE_KINDS
    )


def _reference_payload_types(
    instruction: ResolvedInstruction, backend: CodegenUnit
) -> tuple[str, ...]:
    """Return reference-bearing payload types in deterministic visitor order."""

    payloads = ["ResolvedPredicate"]

    for variant in instruction.variants:
        for layout in variant.operand_layouts:
            for field in layout.fields:
                if (
                    field.value_kind in _REFERENCE_VALUE_KINDS
                    and field_value_cpp_type(field, backend=backend) not in payloads
                ):
                    payloads.append(field_value_cpp_type(field, backend=backend))

    return tuple(payloads)


def emit_reference_visitor(instruction: ResolvedInstruction, backend: CodegenUnit) -> str:
    """Emit typed operand visitation without a hand-maintained opcode switch."""
    variant_cases: list[str] = []
    for variant in instruction.variants:
        if len(variant.operand_layouts) == 1:
            body = _emit_reference_fields(variant.operand_layouts[0].fields, "selected")
        else:
            layouts = "\n".join(
                f"        if constexpr (std::same_as<Payload, {instruction.cpp_name}::{variant.cpp_name}::{layout.cpp_name}Operands>) {{\n"
                f"{_emit_reference_fields(layout.fields, 'payload')}\n        }}"
                for layout in variant.operand_layouts
            )
            body = f"""      std::visit([&]<typename Payload>(const Payload& payload) {{
{layouts}
      }}, selected.operands);"""
        variant_cases.append(
            f"    if constexpr (std::same_as<Variant, {instruction.cpp_name}::{variant.cpp_name}>) {{\n{body}\n    }}"
        )
    visitor_requirements = " &&\n         ".join(
        "std::invocable<Visitor&, const " f"{payload}&, std::span<const SourceRange>>"
        for payload in _reference_payload_types(instruction, backend)
    )
    return f"""/**
 * Visit every binding-bearing operand selected by this resolved instruction.
 *
 * ``Visitor`` accepts every generated payload listed in the corresponding
 * operand layouts as ``(const Payload&, std::span<const SourceRange>)``.
 */
template <typename Visitor>
  requires ({visitor_requirements})
void visit_instruction_references(const {instruction.cpp_name}& instruction,
                                  Visitor&& visitor) {{
  if (instruction.execution_predicate)
    visitor(instruction.execution_predicate->value, instruction.execution_predicate->locs);
  std::visit([&]<typename Variant>(const Variant& selected) {{
{" else ".join(variant_cases)}
  }}, instruction.variant);
}}"""


def emit_resolved_dispatch_branch(instruction: ResolvedInstruction) -> str:
    return f"""\
  if (ast.opcode.syntax.text == "{instruction.opcode}") {{
    auto resolved = resolve<{instruction.cpp_name}>(ast, context);
    if (!resolved)
      return std::unexpected(resolved.error());
    return ResolvedInstruction{{std::in_place_type<{instruction.cpp_name}>,
                               std::move(*resolved)}};
  }}"""
