"""Emit resolved instruction model declarations."""

from __future__ import annotations


from pathlib import Path

from ptx_frontend.base.utils import file_stem_to_pascal_case, generated_at_comment
from ptx_frontend.code_gen.context import GenerationContext
from ptx_frontend.ir.resolved_ir import (
    ResolvedField, ResolvedFieldStorage, ResolvedInstruction,
    ResolvedOperandLayout, ResolvedVariant,
)
from ptx_frontend.ir.tensor_reduction import (
    TENSOR_REDUCTION_ELEMENT_TYPES, TensorReductionOp,
)
from ptx_frontend.spec.model import CodegenUnit
from ptx_frontend.code_gen.resolved_field_names import (
    condition_code_cpp_value, field_cpp_constant_expr, field_cpp_type,
)
from .references import emit_reference_visitor
from .resolved_resolver import _emit_resolve_specialization_declaration
from .resolved_checker import emit_check_specialization_declaration

def generate_resolved_ir_category_header(
    context: GenerationContext,
    *,
    category: str,
    output_path: Path,
) -> None:
    """Generate an ordered, include-only category compatibility header."""

    opcodes = tuple(
        entry.specification.opcode
        for entry in context.entries
        if entry.specification.codegen_category == category
    )
    if not opcodes:
        raise ValueError(f"instruction category {category!r} is empty")

    includes = "\n".join(
        f"#include <ptx_frontend/resolved_ir/model/{category}/{opcode}.gen.hpp>"
        for opcode in opcodes
    )
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

{includes}
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def generate_resolved_ir_category_model_header(
    context: GenerationContext,
    *,
    category: str,
    output_path: Path,
) -> None:
    """Aggregate narrow model leaves without completing the syntax AST."""

    opcodes = tuple(
        entry.specification.opcode
        for entry in context.entries
        if entry.specification.codegen_category == category
    )
    if not opcodes:
        raise ValueError(f"instruction category {category!r} is empty")
    includes = "\n".join(
        f"#include <ptx_frontend/resolved_ir/model/{category}/{opcode}/model.gen.hpp>"
        for opcode in opcodes
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

{includes}
""",
        encoding="utf-8",
    )


def generate_resolved_ir_opcode_header(
    context: GenerationContext,
    *,
    category: str,
    opcode: str,
    output_path: Path,
) -> None:
    """Generate one self-contained model and reference visitor leaf header."""

    instructions = tuple(
        entry.resolved
        for entry in context.entries
        if entry.specification.codegen_category == category
        and entry.specification.opcode == opcode
    )
    if len(instructions) != 1:
        raise ValueError(f"expected one opcode {opcode!r} in category {category!r}")
    instruction = instructions[0]
    definition = emit_resolved_instruction_definition(instruction, context.backend)
    reference_visitor = emit_reference_visitor(instruction, context.backend)
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

#include <concepts>
#include <array>
#include <cstddef>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <variant>
#include <vector>

#include <ptx_frontend/resolved_ir/ptx_resolved_ir_foundation.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_descriptors.hpp>

namespace ptx_frontend::resolved_ir {{

{definition}

namespace detail {{

{reference_visitor}

}}  // namespace detail

class OwnedInstruction;
/** Box this exact opcode record through its generated ownership bridge. */
OwnedInstruction box_instruction({instruction.cpp_name} value);

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def generate_resolved_ir_opcode_full_header(
    context: GenerationContext,
    *,
    category: str,
    opcode: str,
    output_path: Path,
) -> None:
    """Emit one opcode's model, selection, resolver, and checker public API."""

    entries = tuple(
        entry for entry in context.entries
        if entry.specification.codegen_category == category
        and entry.specification.opcode == opcode
    )
    if len(entries) != 1:
        raise ValueError(f"expected one opcode {opcode!r} in category {category!r}")
    instruction = entries[0].resolved
    resolve_declaration = _emit_resolve_specialization_declaration(instruction)
    check_declaration = emit_check_specialization_declaration(instruction)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

#include <ptx_frontend/resolved_ir/model/{category}/{opcode}/model.gen.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_selection.hpp>

namespace ptx_frontend::resolved_ir {{

{resolve_declaration}

}}  // namespace ptx_frontend::resolved_ir

namespace ptx_frontend::resolved_ir::checker {{

{check_declaration}

}}  // namespace ptx_frontend::resolved_ir::checker
""",
        encoding="utf-8",
    )


def generate_resolved_instruction_union_header(
    context: GenerationContext,
    *,
    output_path: Path,
) -> None:
    """Generate the aggregate instruction union in canonical context order."""

    category_headers = tuple(sorted({
        entry.specification.codegen_category for entry in context.entries
    }))
    includes = "\n".join(
        f'#include <ptx_frontend/resolved_ir/model/{category}/model.gen.hpp>'
        for category in category_headers
    )
    content = f"""\\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

#include <variant>

{includes}

namespace ptx_frontend::resolved_ir {{

{_emit_resolved_instruction_union(context.instructions)}

}}  // namespace ptx_frontend::resolved_ir
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def generate_resolved_ir_header(
    context: GenerationContext,
    *,
    output_path: Path,
) -> None:
    """Generate the aggregate compatibility model header."""

    category_headers = tuple(sorted({
        entry.specification.codegen_category for entry in context.entries
    }))

    includes = "\n".join(
        f'#include <ptx_frontend/resolved_ir/model/{category}/model.gen.hpp>'
        for category in category_headers
    )
    content = f"""\\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

{includes}
#include <ptx_frontend/resolved_ir/resolved_instruction_union.gen.hpp>
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def _emit_resolved_instruction_union(
    instructions: tuple[ResolvedInstruction, ...],
) -> str:
    """Emit the model-owned resolved instruction alternative union."""

    alternatives = ", ".join(instruction.cpp_name for instruction in instructions)
    return f"""\
using InstructionUnion = std::variant<{alternatives}>;
"""


def emit_resolved_instruction_definition(instruction: ResolvedInstruction, backend: CodegenUnit) -> str:
    """Emit one opcode-level C++ resolved instruction struct."""

    has_tensor_reduction = any(
        variant.tensor_reduction_op is not None for variant in instruction.variants
    )
    reduction_domain = (
        _emit_tensor_reduction_domain() if has_tensor_reduction else ""
    )
    variant_names = ", ".join(variant.cpp_name for variant in instruction.variants)
    variant_enum_values = "\n".join(
        f"    {variant.cpp_name}," for variant in instruction.variants
    )
    variant_name_entries = "\n".join(
        f'      {{VariantType::{variant.cpp_name}, "{variant.cpp_name}"}},'
        for variant in instruction.variants
    )
    variant_definitions = "\n\n".join(
        _emit_resolved_variant_definition(variant, backend, has_tensor_reduction)
        for variant in instruction.variants
    )

    atomic_qualifier = (
        "  /** Written address suffix, distinct from address provenance. */\n"
        "  WithLocs<AtomicAddressQualifier> address_qualifier;\n"
        if instruction.atomic_address_qualifier is not None else ""
    )
    definition = f"""\
{reduction_domain}
struct {instruction.cpp_name} {{
  enum class VariantType {{
{variant_enum_values}
  }};

  /** Exact generated enum/name pairs, independent of reflection scan limits. */
  inline static constexpr std::array<
      std::pair<VariantType, std::string_view>, {len(instruction.variants)}>
      variant_name_map{{{{
{variant_name_entries}
      }}}};

  /** Find the generated enumerator for a descriptor name. */
  static constexpr std::optional<VariantType> variant_type_from_name(
      std::string_view name) noexcept {{
    for (const auto& [variant, spelling] : variant_name_map) {{
      if (spelling == name)
        return variant;
    }}
    return std::nullopt;
  }}

  /** Return the descriptor name of a generated enumerator, or empty if invalid. */
  static constexpr std::string_view variant_type_name(
      VariantType value) noexcept {{
    for (const auto& [variant, spelling] : variant_name_map) {{
      if (variant == value)
        return spelling;
    }}
    return {{}};
  }}

{variant_definitions}

  using Variant = std::variant<{variant_names}>;
  std::optional<WithLocs<ResolvedPredicate>> execution_predicate;
{atomic_qualifier}\
  Variant variant;

  static const check_end::SyntaxInstructionDescriptor&
  get_syntax_descriptor() noexcept;
  static const check_end::ResolvedInstructionDescriptor&
  get_resolved_descriptor() noexcept;
  static const checker::InstructionDescriptor&
  get_checker_descriptor() noexcept;
}};"""
    return definition


def _emit_tensor_reduction_domain() -> str:
    """Emit the closed operation and conditional descriptor-type query once."""

    enum_members = "\n".join(
        f"  {file_stem_to_pascal_case(op.value)}," for op in TensorReductionOp
    )
    cases = "\n".join(
        "    case TensorReductionOp::"
        f"{file_stem_to_pascal_case(op.value)}:\n"
        "      switch (element_type) {\n"
        + "\n".join(
            f"        case base::ScalarType::{scalar.upper()}:"
            for scalar in TENSOR_REDUCTION_ELEMENT_TYPES[op]
        )
        + "\n          return true;\n"
        "        default:\n          return false;\n      }"
        for op in TensorReductionOp
    )
    return f"""\
/** Encoded tiled tensor-reduction operation; descriptor contents remain opaque. */
enum class TensorReductionOp : uint8_t {{
{enum_members}
}};

/** Whether an operation permits a descriptor element type if that type is known.
 * This does not inspect or validate a tensor-map descriptor instance.
 */
constexpr bool tensor_reduction_accepts_element_type(
    TensorReductionOp operation, base::ScalarType element_type) noexcept {{
  switch (operation) {{
{cases}
    default:
      return false;
  }}
}}
"""


def _emit_resolved_variant_definition(
    variant: ResolvedVariant, backend: CodegenUnit,
    has_tensor_reduction: bool = False,
) -> str:
    modifier_fields = "\n".join(
        _emit_resolved_field(field, backend) for field in variant.modifier_fields
    )
    if len(variant.operand_layouts) == 1:
        operand_fields = "\n".join(
            _emit_resolved_field(field, backend) for field in variant.operand_layouts[0].fields
        )
        body = f"{modifier_fields}\n{operand_fields}"
    else:
        layout_structs = "\n\n".join(
            _emit_operand_layout_definition(layout, backend)
            for layout in variant.operand_layouts
        )
        alternatives = ", ".join(
            f"{layout.cpp_name}Operands" for layout in variant.operand_layouts
        )
        body = f"""{modifier_fields}

{layout_structs}

    using Operands = std::variant<{alternatives}>;
    Operands operands;"""

    tensor_map_projection = _emit_tensor_map_replace_projection(variant)
    reduction_identity = ""
    if has_tensor_reduction:
        value = (
            f"TensorReductionOp::{file_stem_to_pascal_case(variant.tensor_reduction_op.value)}"
            if variant.tensor_reduction_op is not None else "std::nullopt"
        )
        reduction_identity = (
            "    /** Static tiled reduction operation, absent on other Cp forms. */\n"
            "    inline static constexpr std::optional<TensorReductionOp> "
            f"tensor_reduction_op = {value};\n"
        )
    return f"""\
  // YAML: {variant.variant_id}
  struct {variant.cpp_name} {{
    /** Implicit CC.CF effect, gated by the enclosing execution predicate. */
    inline static constexpr ConditionCodeEffect condition_code_effect =
        {condition_code_cpp_value(variant.condition_code_effect)};
    /** Instruction-local completion identity; no runtime group state is implied. */
    inline static constexpr base::AsyncCompletionKind completion_kind =
        base::AsyncCompletionKind::{''.join(part.title() for part in variant.completion_kind.value.split('_'))};
{reduction_identity}\
    ResolvedOperandLayoutTag operand_layout;
{body}
{tensor_map_projection}
  }};"""


def _emit_tensor_map_replace_projection(variant: ResolvedVariant) -> str:
    """Emit a field-typed projection from canonical fixed-field metadata."""

    fields = [
        field.source_name.removeprefix("field_")
        for field in variant.modifier_fields
        if field.source_name.startswith("field_")
    ]
    if not fields:
        return ""
    if len(fields) != 1:
        raise ValueError("a tensor-map replacement needs exactly one fixed field")
    field = fields[0]
    enum_name = file_stem_to_pascal_case(field)
    result = (
        "    /** Closed identity of the encoded tensor-map field. */\n"
        "    inline static constexpr TensorMapReplaceField replacement_field = "
        f"TensorMapReplaceField::{enum_name};\n"
        "    /** Own an opaque descriptor reference when source locations exist; "
        "the checker validates its address. */\n"
        "    std::optional<ResolvedTensorMapRef> tensor_map_ref() const {\n"
        "      if (tensor_map.locs.empty())\n"
        "        return std::nullopt;\n"
        "      return ResolvedTensorMapRef{tensor_map.value, tensor_map.locs.front()};\n"
        "    }"
    )
    encoded_types = {
        "elemtype": "TensorMapElementType",
        "interleave_layout": "TensorMapInterleaveLayout",
        "swizzle_mode": "TensorMapSwizzleMode",
        "swizzle_atomicity": "TensorMapSwizzleAtomicity",
        "fill_mode": "TensorMapFillMode",
    }
    if field in encoded_types:
        value_type = encoded_types[field]
        result += (
            "\n    /** Decode the original Table 33 code after owned-value consistency checks. */\n"
            f"    std::optional<{value_type}> encoded_value() const noexcept {{\n"
            f"      return project_tensor_map_encoded_value<{value_type}>(\n"
            "          replacement_field, new_val.value);\n"
            "    }"
        )
    return result


def _emit_operand_layout_definition(layout: ResolvedOperandLayout, backend: CodegenUnit) -> str:
    fields = "\n".join(_emit_resolved_field(field, backend) for field in layout.fields)
    return f"""    // YAML operand layout: {layout.layout_id}
    struct {layout.cpp_name}Operands {{
{fields}
    }};"""


def _emit_resolved_field(field: ResolvedField, backend: CodegenUnit) -> str:
    if field.storage is ResolvedFieldStorage.STATIC_CONSTANT:
        return (
            f"    inline static constexpr {field_cpp_type(field, backend=backend)} {field.name} = "
            f"{field_cpp_constant_expr(field, backend=backend)};"
        )
    return f"    {field_cpp_type(field, backend=backend)} {field.name};"
