"""Emit resolved-instruction resolver declarations and definitions."""

from __future__ import annotations


from pathlib import Path

from ptx_frontend.base.utils import generated_at_comment
from ptx_frontend.code_gen.context import GenerationContext
from ptx_frontend.spec.model import CodegenUnit
from ptx_frontend.ir.resolved_ir import (
    ResolvedField, ResolvedFieldOrigin, ResolvedFieldStorage,
    ResolvedInstruction, ResolvedVariant,
)
from ptx_frontend.code_gen.resolved_field_names import field_value_cpp_type

def generate_resolved_ir_resolution_category_declarations_header(
    context: GenerationContext, *, category: str, output_path: Path
) -> None:
    """Generate one public resolver specialization declaration category."""


    instructions = tuple(
        entry.resolved
        for entry in context.entries
        if entry.specification.codegen_category == category
    )
    if not instructions:
        raise ValueError(f"instruction category {category!r} is empty")
    declarations = "\n\n".join(
        _emit_resolve_specialization_declaration(instruction)
        for instruction in instructions
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""\\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

#include <ptx_frontend/resolved_ir/ptx_resolved_ir_resolution_support.hpp>
#include <ptx_frontend/resolved_ir/model/{category}.gen.hpp>

namespace ptx_frontend::resolved_ir {{

{declarations}

}}  // namespace ptx_frontend::resolved_ir
""",
        encoding="utf-8",
    )


def generate_resolved_ir_resolution_declarations_header(
    context: GenerationContext,
    *,
    output_path: Path,
) -> None:
    """Generate the aggregate resolver declaration compatibility header."""

    category_headers = tuple(sorted({
        entry.specification.codegen_category for entry in context.entries
    }))

    includes = "\n".join(
        f'#include <ptx_frontend/resolved_ir/resolution/{category}.gen.hpp>'
        for category in category_headers
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""\\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

{includes}
""",
        encoding="utf-8",
    )
def _emit_resolve_specialization_declaration(
    instruction: ResolvedInstruction,
) -> str:
    return f"""\
template <>
std::expected<{instruction.cpp_name}, ResolveDiagnostic>
resolve<{instruction.cpp_name}>(const syntax_ast::AstInstruction& ast,
    const ResolveContext* context);"""


def emit_resolve_specialization(instruction: ResolvedInstruction, backend: CodegenUnit) -> str:
    """Emit one resolver specialization definition for category composition."""

    variant_cases = "\n".join(
        _emit_resolve_variant_case(instruction, variant, backend)
        for variant in instruction.variants
    )
    return f"""\
template <>
std::expected<{instruction.cpp_name}, ResolveDiagnostic>
resolve<{instruction.cpp_name}>(const syntax_ast::AstInstruction& ast,
    const ResolveContext* context) {{
  const auto selected_variant = selectVariant<{instruction.cpp_name}>(ast);
  if (!selected_variant)
    return std::unexpected(selected_variant.error());

  auto fields = resolve_fields(
      ast, {instruction.cpp_name}::get_syntax_descriptor(),
      {instruction.cpp_name}::get_resolved_descriptor(),
      magic_enum::enum_name(*selected_variant), context);
  if (!fields)
    return std::unexpected(fields.error());

{variant_cases}

  throw ResolveException("Unknown {instruction.cpp_name} variant in resolved field table.");
}}"""


def _emit_resolve_variant_case(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    backend: CodegenUnit,
) -> str:
    atomic_qualifier = (
        ".address_qualifier = atomic_address_qualifier_from_ast(ast),\n        "
        if instruction.opcode in {"atom", "red"} else ""
    )
    if len(variant.operand_layouts) == 1:
        fields = "\n".join(
            "          " + _emit_resolve_field_initializer(field, backend)
            for field in variant.modifier_fields + variant.operand_layouts[0].fields
            if field.storage is ResolvedFieldStorage.INSTANCE
        )
        return f"""\
  if (fields->variant_name == "{variant.cpp_name}") {{
    return {instruction.cpp_name}{{
        .execution_predicate = std::move(fields->execution_predicate),
        {atomic_qualifier}\
        .variant = {instruction.cpp_name}::{variant.cpp_name}{{
                   .operand_layout = fields->operand_layout,
{fields}
    }}}};
  }}"""

    layout_cases = "\n".join(
        _emit_resolve_multi_layout_case(instruction, variant, index, backend)
        for index, _ in enumerate(variant.operand_layouts)
    )
    fields = "\n".join(
        "          " + _emit_resolve_field_initializer(field, backend)
        for field in variant.modifier_fields
        if field.storage is ResolvedFieldStorage.INSTANCE
    )
    return f"""\
  if (fields->variant_name == "{variant.cpp_name}") {{
{layout_cases}
    throw ResolveException("Unknown {instruction.cpp_name}::{variant.cpp_name} operand layout.");
  }}"""


def _emit_resolve_multi_layout_case(
    instruction: ResolvedInstruction,
    variant: ResolvedVariant,
    layout_index: int,
    backend: CodegenUnit,
) -> str:
    layout = variant.operand_layouts[layout_index]
    atomic_qualifier = (
        ".address_qualifier = atomic_address_qualifier_from_ast(ast),\n          "
        if instruction.opcode in {"atom", "red"} else ""
    )
    modifier_fields = "\n".join(
        "              " + _emit_resolve_field_initializer(field, backend)
        for field in variant.modifier_fields
        if field.storage is ResolvedFieldStorage.INSTANCE
    )
    operand_fields = "\n".join(
        "                  " + _emit_resolve_field_initializer(field, backend)
        for field in layout.fields
        if field.storage is ResolvedFieldStorage.INSTANCE
    )
    return f"""    if (fields->operand_layout.value == {layout_index}) {{
      return {instruction.cpp_name}{{
          .execution_predicate = std::move(fields->execution_predicate),
          {atomic_qualifier}\
          .variant = {instruction.cpp_name}::{variant.cpp_name}{{
              .operand_layout = fields->operand_layout,
{modifier_fields}
              .operands = {instruction.cpp_name}::{variant.cpp_name}::Operands{{
                  {instruction.cpp_name}::{variant.cpp_name}::{layout.cpp_name}Operands{{
{operand_fields}
                  }},
              }},
          }}}};
    }}"""


def _emit_resolve_field_initializer(field: ResolvedField, backend: CodegenUnit) -> str:
    accessor = (
        "resolved_modifier"
        if field.origin is ResolvedFieldOrigin.MODIFIER
        else "resolved_operand"
    )
    return (
        f".{field.name} = {accessor}<{field_value_cpp_type(field, backend=backend)}>(*fields, "
        f'"{field.name}"),'
    )
