"""Emit resolved instruction model declarations."""

from __future__ import annotations

from .resolved_validation import validate_unique_cpp_names

from pathlib import Path

from ptx_frontend.base.utils import generated_at_comment
from ptx_frontend.code_gen.context import GenerationContext
from ptx_frontend.ir.resolved_ir import (
    ResolvedField, ResolvedFieldStorage, ResolvedInstruction,
    ResolvedOperandLayout, ResolvedVariant,
)
from ptx_frontend.spec.model import CodegenUnit
from ptx_frontend.code_gen.resolved_field_names import (
    condition_code_cpp_value, field_cpp_constant_expr, field_cpp_type,
)
from .references import emit_reference_visitor, validate_reference_field_types

def generate_resolved_ir_header(
    context: GenerationContext,
    *,
    output_path: Path,
) -> None:
    """Generate a self-contained public Resolved IR header.

    The generated header may be included directly.  It includes the resolved
    IR foundation header, which supplies ``WithLocs``, resolved operand
    primitives, and ``check_end`` descriptors, then declares the generated
    instruction types in ``ptx_frontend::resolved_ir``.
    """


    instructions = context.instructions
    validate_unique_cpp_names(instructions)
    validate_reference_field_types(instructions)

    definitions = "\n\n".join(
        emit_resolved_instruction_definition(instruction, context.backend)
        for instruction in instructions
    )
    instruction_union = _emit_resolved_instruction_union(instructions)
    reference_visitors = "\n\n".join(
        emit_reference_visitor(instruction, context.backend) for instruction in instructions
    )
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}
#pragma once

#include <concepts>
#include <cstddef>
#include <optional>
#include <span>
#include <string>
#include <variant>
#include <vector>

#include <ptx_frontend/resolved_ir/ptx_resolved_ir_foundation.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_descriptors.hpp>

namespace ptx_frontend::resolved_ir {{

{definitions}

{instruction_union}

namespace detail {{

{reference_visitors}

}}  // namespace detail

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def _emit_resolved_instruction_union(
    instructions: tuple[ResolvedInstruction, ...],
) -> str:
    """Emit the model-owned resolved instruction alternative union."""

    alternatives = ", ".join(instruction.cpp_name for instruction in instructions)
    return f"""\
using ResolvedInstruction = std::variant<{alternatives}>;
"""


def emit_resolved_instruction_definition(instruction: ResolvedInstruction, backend: CodegenUnit) -> str:
    """Emit one opcode-level C++ resolved instruction struct."""

    variant_names = ", ".join(variant.cpp_name for variant in instruction.variants)
    variant_enum_values = "\n".join(
        f"    {variant.cpp_name}," for variant in instruction.variants
    )
    variant_definitions = "\n\n".join(
        _emit_resolved_variant_definition(variant, backend) for variant in instruction.variants
    )

    definition = f"""\
struct {instruction.cpp_name} {{
  enum class VariantType {{
{variant_enum_values}
  }};

{variant_definitions}

  using Variant = std::variant<{variant_names}>;
  std::optional<WithLocs<ResolvedPredicate>> execution_predicate;
  Variant variant;

  static const check_end::SyntaxInstructionDescriptor&
  get_syntax_descriptor() noexcept;
  static const check_end::ResolvedInstructionDescriptor&
  get_resolved_descriptor() noexcept;
  static const checker::InstructionDescriptor&
  get_checker_descriptor() noexcept;
}};"""
    return definition


def _emit_resolved_variant_definition(variant: ResolvedVariant, backend: CodegenUnit) -> str:
    modifier_fields = "\n".join(
        _emit_resolved_field(field, backend) for field in variant.modifier_fields
    )
    if len(variant.operand_layouts) == 1:
        operand_fields = "\n".join(
            _emit_resolved_field(field, backend) for field in variant.operand_layouts[0].fields
        )
        body = f"{modifier_fields}\n{operand_fields}"
    else:
        layout_structs = "\n\n".join(
            _emit_operand_layout_definition(layout, backend)
            for layout in variant.operand_layouts
        )
        alternatives = ", ".join(
            f"{layout.cpp_name}Operands" for layout in variant.operand_layouts
        )
        body = f"""{modifier_fields}

{layout_structs}

    using Operands = std::variant<{alternatives}>;
    Operands operands;"""

    return f"""\
  // YAML: {variant.variant_id}
  struct {variant.cpp_name} {{
    /** Implicit CC.CF effect, gated by the enclosing execution predicate. */
    inline static constexpr ConditionCodeEffect condition_code_effect =
        {condition_code_cpp_value(variant.condition_code_effect)};
    ResolvedOperandLayoutTag operand_layout;
{body}
  }};"""


def _emit_operand_layout_definition(layout: ResolvedOperandLayout, backend: CodegenUnit) -> str:
    fields = "\n".join(_emit_resolved_field(field, backend) for field in layout.fields)
    return f"""    // YAML operand layout: {layout.layout_id}
    struct {layout.cpp_name}Operands {{
{fields}
    }};"""


def _emit_resolved_field(field: ResolvedField, backend: CodegenUnit) -> str:
    if field.storage is ResolvedFieldStorage.STATIC_CONSTANT:
        return (
            f"    inline static constexpr {field_cpp_type(field, backend=backend)} {field.name} = "
            f"{field_cpp_constant_expr(field, backend=backend)};"
        )
    return f"    {field_cpp_type(field, backend=backend)} {field.name};"
