"""Emit opcode-to-resolver dispatch."""

from __future__ import annotations


from pathlib import Path

from ptx_frontend.base.utils import generated_at_comment
from ptx_frontend.code_gen.context import GenerationContext
from ptx_frontend.ir.resolved_ir import ResolvedInstruction


def generate_resolved_dispatch_source(
    context: GenerationContext,
    *,
    output_path: Path,
) -> None:
    """Generate opcode-independent instruction resolution dispatch."""


    instructions = context.instructions
    branches = "\n\n".join(
        emit_resolved_dispatch_branch(instruction) for instruction in instructions
    )
    content = f"""\
// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include <ptx_frontend/resolved_ir/ptx_resolved_ir.hpp>

#include <utility>

namespace ptx_frontend::resolved_ir {{

namespace {{

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolve_instruction(const syntax_ast::AstInstruction& ast,
                    const ResolveContext* context) {{
{branches}

  return std::unexpected(ResolveDiagnostic{{
      .range = ast.opcode.syntax.range,
      .message = "Unknown PTX opcode '" + ast.opcode.syntax.text + "'.",
  }});
}}

}}  // namespace

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolveInstruction(const syntax_ast::AstInstruction& ast) {{
  return resolve_instruction(ast, nullptr);
}}

std::expected<ResolvedInstruction, ResolveDiagnostic>
resolveInstruction(const syntax_ast::AstInstruction& ast,
                   const ResolveContext& context) {{
  return resolve_instruction(ast, &context);
}}

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def emit_resolved_dispatch_branch(instruction: ResolvedInstruction) -> str:
    return f"""\
  if (ast.opcode.syntax.text == "{instruction.opcode}") {{
    auto resolved = resolve<{instruction.cpp_name}>(ast, context);
    if (!resolved)
      return std::unexpected(resolved.error());
    return ResolvedInstruction{{std::in_place_type<{instruction.cpp_name}>,
                               std::move(*resolved)}};
  }}"""
