"""Emit the global direct-class identity and resolver dispatch."""

from __future__ import annotations

from pathlib import Path

from ptx_frontend.code_gen.context import GenerationContext
from ptx_frontend.code_gen.emit.resolved_model import INCLUDE_ROOT, form_name


def generate_resolved_dispatch_source(
    context: GenerationContext, *, output_path: Path
) -> None:
    """Emit exact form-to-family mapping and opcode syntax dispatch."""

    kind_cases = "\n".join(
        f"    case InstructionKind::{form_name(entry, variant)}:\n"
        f"      return Opcode::{entry.cpp_name};"
        for entry in context.entries for variant in entry.resolved.variants
    )
    name_cases = "\n".join(
        f'    case Opcode::{entry.cpp_name}: return "{entry.specification.opcode}";'
        for entry in context.entries
    )
    dispatch = "\n".join(
        f'  if (ast.opcode.syntax.text == "{entry.specification.opcode}")\n'
        f'    return resolve{entry.cpp_name}(ast, context);'
        for entry in context.entries
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(f"""// Generated by ptx_frontend resolved IR code generation. Do not edit.
#include <{INCLUDE_ROOT}/ptx_resolved_ir.hpp>
#include <utility>

namespace ptx_frontend::resolved_ir {{

/** Destroy an exact concrete instruction through the base interface. */
Instruction::~Instruction() = default;

/** Map exact semantic identity to its opcode family. */
Opcode Instruction::opcode_kind() const noexcept {{
  switch (instruction_kind()) {{
{kind_cases}
  }}
  std::unreachable();
}}

/** Map an opcode family to its canonical mnemonic. */
std::string_view Instruction::opcode_name() const noexcept {{
  switch (opcode_kind()) {{
{name_cases}
  }}
  std::unreachable();
}}

namespace {{
/** Resolve one syntax opcode using the optional bound declaration context. */
std::expected<std::unique_ptr<Instruction>, ResolveDiagnostic> resolve_instruction(
    const syntax_ast::AstInstruction& ast, const ResolveContext* context) {{
{dispatch}
  return std::unexpected(ResolveDiagnostic{{
      .range = ast.opcode.syntax.range,
      .message = "Unknown PTX opcode '" + ast.opcode.syntax.text + "'.",
  }});
}}
}}  // namespace

/** Resolve an unbound instruction to an exact final class. */
std::expected<std::unique_ptr<Instruction>, ResolveDiagnostic> resolveInstruction(
    const syntax_ast::AstInstruction& ast) {{
  return resolve_instruction(ast, nullptr);
}}

/** Resolve a bound instruction to an exact final class. */
std::expected<std::unique_ptr<Instruction>, ResolveDiagnostic> resolveInstruction(
    const syntax_ast::AstInstruction& ast, const ResolveContext& context) {{
  return resolve_instruction(ast, &context);
}}

}}  // namespace ptx_frontend::resolved_ir
""", encoding="utf-8")
