"""Generate immutable dense f16 MMA operational rows.

The global artifact plan registers these outputs. This emitter contains no
descriptor bit-field map and no source grammar.
"""

from __future__ import annotations

from pathlib import Path

from ptx_frontend.spec import tcgen_mma_operations as operations


HEADER_NAME = "tcgen_mma_operations.gen.hpp"
SOURCE_NAME = "resolved_ir_tcgen_mma_operations.gen.cpp"


def render_tcgen_mma_header() -> str:
    """Render public declarations backed by immutable generated static rows."""

    return '''// Generated by ptx_frontend.code_gen. Do not edit.
#pragma once
#include <array>
#include <cstdint>
#include <span>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_foundation.hpp>

namespace ptx_frontend::resolved_ir {
/** One known Table 42 dense, non-WS f16-kind shape/output row.
 *  K is uniquely 16 and must not be specified explicitly in the descriptor.
 *  A/B type coupling beyond individual domains remains an obligation.
 */
struct TcgenF16ShapeRow {
  /** Number of CTAs in the MMA's typed group. */
  TcgenCtaGroup group;
  /** Output element type selected by known instruction bits. */
  MatrixElementType d_type;
  /** Closed allowed M values for this group. */
  std::array<uint16_t, 2> m_values;
  /** First allowed N value, measured in columns. */
  uint16_t n_first;
  /** Step between legal N values, measured in columns. */
  uint16_t n_step;
  /** Last allowed N value, measured in columns. */
  uint16_t n_last;
  /** Uniquely determined K value, measured in elements. */
  uint16_t k;
};
/** One dense, non-WS f16 Tensor Memory path from section 9.7.17.10.5. */
struct TcgenF16PathRow {
  /** CTA group that selects this path. */
  TcgenCtaGroup group;
  /** M dimension that selects this path. */
  uint16_t m;
  /** Written layout identity, one of A, B, D or F. */
  char layout;
  /** Whether known A/D Tensor Memory lane-half alignment must agree. */
  bool half_path;
};
/** Borrow the immutable generated Table 42 f16 rows for caller-known facts. */
[[nodiscard]] std::span<const TcgenF16ShapeRow> tcgen_f16_shape_rows() noexcept;
/** Borrow the immutable generated dense f16 datapath rows. */
[[nodiscard]] std::span<const TcgenF16PathRow> tcgen_f16_path_rows() noexcept;
/** Check dimensions against one row; this does not authenticate source words. */
[[nodiscard]] bool tcgen_f16_row_contains(const TcgenF16ShapeRow& row,
                                          uint16_t m, uint16_t n,
                                          uint16_t k) noexcept;
}  // namespace ptx_frontend::resolved_ir
''' + _QUERY_HEADER


def render_tcgen_mma_source() -> str:
    """Render catalogue-derived C++ storage with no duplicate encoded map."""

    operations.validate_catalogue()
    shape_rows = []
    for row in operations.F16_SHAPES:
        group = "One" if row.group == 1 else "Two"
        shape_rows.append(
            f'  TcgenF16ShapeRow{{TcgenCtaGroup::{group}, '
            f'MatrixElementType::{row.d_type}, '
            f'{{{{{row.m_values[0]}, {row.m_values[1]}}}}}, '
            f'{row.n_first}, {row.n_step}, {row.n_last}, {row.k}}}')
    path_rows = []
    for row in operations.F16_PATHS:
        group = "One" if row.group == 1 else "Two"
        half = "true" if row.half_path else "false"
        path_rows.append(
            f"  TcgenF16PathRow{{TcgenCtaGroup::{group}, {row.m}, "
            f"'{row.layout}', {half}}}")
    shape_text = ",\n".join(shape_rows)
    path_text = ",\n".join(path_rows)
    target_rows = ",\n".join(
        '  TcgenF16TargetGate{"%s", %s, {%d, %d}, %s}' % (
            gate.feature, "true" if gate.exact else "false",
            gate.ptx_major, gate.ptx_minor,
            "true" if gate.scaled_d else "false")
        for gate in operations.F16_TARGET_GATES)
    return f'''// Generated by ptx_frontend.code_gen. Do not edit.
#include <ptx_frontend/resolved_ir/{HEADER_NAME}>

namespace ptx_frontend::resolved_ir {{
namespace {{
constexpr std::array<TcgenF16ShapeRow, {len(shape_rows)}> kShapes = {{{{
{shape_text}
}}}};
constexpr std::array<TcgenF16PathRow, {len(path_rows)}> kPaths = {{{{
{path_text}
}}}};
}}  // namespace
std::span<const TcgenF16ShapeRow> tcgen_f16_shape_rows() noexcept {{
  return kShapes;
}}
std::span<const TcgenF16PathRow> tcgen_f16_path_rows() noexcept {{
  return kPaths;
}}
bool tcgen_f16_row_contains(const TcgenF16ShapeRow& row,
                            uint16_t m, uint16_t n, uint16_t k) noexcept {{
  return (m == row.m_values[0] || m == row.m_values[1]) &&
         n >= row.n_first && n <= row.n_last &&
         (n - row.n_first) % row.n_step == 0 && k == row.k;
}}
}}  // namespace ptx_frontend::resolved_ir
''' + (_QUERY_SOURCE.replace("__TARGET_ROWS__", target_rows)
                    .replace("__TARGET_COUNT__",
                             str(len(operations.F16_TARGET_GATES))))


def generate_tcgen_mma_header(_context: object, *, output_path: Path) -> None:
    """Write the planned public operational rows."""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_tcgen_mma_header(), encoding="utf-8")


def generate_tcgen_mma_source(_context: object, *, output_path: Path) -> None:
    """Write the planned private operational row backing."""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_tcgen_mma_source(), encoding="utf-8")


_QUERY_HEADER = r'''
#include <optional>
#include <vector>
#include <ptx_frontend/resolved_ir/tcgen_descriptor_domains.gen.hpp>

namespace ptx_frontend::resolved_ir {
/** One independently completed dense f16 operational check. */
enum class TcgenF16Checked : uint8_t {
  InstructionFields, ASharedFields, BSharedFields, Dense, Shape, Types,
  AMajor, BMajor, ASwizzle, BSwizzle, Datapath, HalfAlignment, Target
};
/** A violation proved by supplied known values, not by an opaque register. */
enum class TcgenF16Violation : uint8_t {
  Kind, Group, DenseSparse, Shape, AType, BType, APlacementFacts,
  AMajor, BMajor, ASwizzle, BSwizzle, ALaneHalf, DLaneHalf,
  HalfAlignment, Target, InvalidContext
};
/** A missing fact or unresolved rule that prevents a stronger conclusion. */
enum class TcgenF16Obligation : uint8_t {
  ASharedWord, BSharedWord, AMajor, BMajor, MixedInputPair,
  ALaneHalf, DLaneHalf, Target
};
/** Caller-supplied known words and context, independent of MMA source registers. */
struct TcgenF16KnownFacts {
  /** Group selected by the source qualifier. */
  TcgenCtaGroup group;
  /** Whether A is a Tensor Memory address rather than a shared descriptor. */
  bool a_in_tmem;
  /** Whether the optional D scaling immediate is present. */
  bool scaled_d;
  /** Independently known instruction bits and explicit kind. */
  TcgenInstructionWord instruction;
  /** Optional caller-known Table 43 A word; absent for Tensor Memory A. */
  std::optional<TcgenSharedWord> a_shared_word;
  /** Optional caller-known Table 43 B word. */
  std::optional<TcgenSharedWord> b_shared_word;
  /** Context for A word field checks, including known major/bytes. */
  TcgenSharedContext a_context;
  /** Context for B word field checks, including known major/bytes. */
  TcgenSharedContext b_context;
  /** Independently known A Tensor Memory lane half, either 0 or 16. */
  std::optional<uint8_t> a_lane_half;
  /** Independently known D Tensor Memory lane half, either 0 or 16. */
  std::optional<uint8_t> d_lane_half;
  /** Explicit cataloged target identity, when known. */
  std::optional<base::TargetIdentity> target;
  /** Explicit PTX version, when known. */
  std::optional<checker::PtxVersion> ptx_version;
};
/** Defined-field results plus individually checked, violated, and missing facts. */
struct TcgenF16OperationalReport {
  /** Accepted Tables 45–47 field report, always populated. */
  TcgenDefinedFieldReport instruction_fields;
  /** Accepted Table 43 A report, present only for supplied shared A words. */
  std::optional<TcgenDefinedFieldReport> a_shared_fields;
  /** Accepted Table 43 B report, present only for supplied B words. */
  std::optional<TcgenDefinedFieldReport> b_shared_fields;
  /** Checks actually evaluated with enough supplied facts. */
  std::vector<TcgenF16Checked> checked;
  /** Operational failures proved by supplied facts. */
  std::vector<TcgenF16Violation> violations;
  /** Facts/rules still needed; absence does not mean validity. */
  std::vector<TcgenF16Obligation> missing;
  /** Data-path layout selected from known group and M, if supported. */
  std::optional<char> path_layout;
  /** Report whether every supplied checked fact passed its own rule. */
  [[nodiscard]] bool supplied_facts_ok() const noexcept {
    return instruction_fields.defined_fields_ok() &&
           (!a_shared_fields || a_shared_fields->defined_fields_ok()) &&
           (!b_shared_fields || b_shared_fields->defined_fields_ok()) &&
           violations.empty();
  }
};
/** Validate independent known words against dense non-WS f16 operational rules.
 *  Caller-supplied words are never authenticated against source registers.
 */
[[nodiscard]] TcgenF16OperationalReport check_tcgen_f16_known_operation(
    const TcgenF16KnownFacts& facts);
}  // namespace ptx_frontend::resolved_ir
'''

_QUERY_SOURCE = r'''
#include <algorithm>
#include <array>
#include <string_view>
#include <utility>

namespace ptx_frontend::resolved_ir {
namespace {
/** One approved target floor, matched through the accepted profile catalog. */
struct TcgenF16TargetGate {
  /** Exact target spelling or enabled family feature. */
  std::string_view feature;
  /** Whether the spelling must match the identity exactly. */
  bool exact;
  /** PTX version from which the gate is available. */
  checker::PtxVersion minimum_ptx;
  /** Whether this row applies only when D scaling is present. */
  bool scaled_d;
};
constexpr std::array<TcgenF16TargetGate, __TARGET_COUNT__> kTargetGates = {{
__TARGET_ROWS__
}};
/** Check a supplied target identity and version against the closed rows. */
bool accepts_target(const TcgenF16KnownFacts& facts) {
  const auto profile = base::find_target_profile(facts.target->source_spelling);
  if (!profile || profile->identity != *facts.target) return false;
  for (const auto& gate : kTargetGates) {
    if (gate.scaled_d != facts.scaled_d ||
        *facts.ptx_version < gate.minimum_ptx) continue;
    if (gate.exact && facts.target->source_spelling == gate.feature)
      return true;
    if (!gate.exact &&
        std::find(profile->enabled_family_features.begin(),
                  profile->enabled_family_features.end(), gate.feature) !=
            profile->enabled_family_features.end())
      return true;
  }
  return false;
}
/** Apply the per-operand 16-bit Table 57 rule after field validation. */
void check_shared_operand(bool is_a, bool transpose,
                          TcgenSharedWord word, TcgenSharedContext context,
                          const TcgenF16KnownFacts& facts,
                          TcgenF16OperationalReport& report) {
  if (context.target && facts.target && *context.target != *facts.target)
    report.violations.push_back(TcgenF16Violation::InvalidContext);
  if (context.ptx_version && facts.ptx_version &&
      *context.ptx_version != *facts.ptx_version)
    report.violations.push_back(TcgenF16Violation::InvalidContext);
  if (!context.target) context.target = facts.target;
  if (!context.ptx_version) context.ptx_version = facts.ptx_version;
  if (is_a) context.transpose_a = transpose;
  else context.transpose_b = transpose;
  auto fields = validate_tcgen_shared_defined_fields(word, context);
  if (is_a) {
    report.a_shared_fields = std::move(fields);
    report.checked.push_back(TcgenF16Checked::ASharedFields);
  } else {
    report.b_shared_fields = std::move(fields);
    report.checked.push_back(TcgenF16Checked::BSharedFields);
  }
  if (!context.major) {
    report.missing.push_back(is_a ? TcgenF16Obligation::AMajor
                                  : TcgenF16Obligation::BMajor);
  } else {
    if (*context.major != (transpose ? TcgenMajor::MN : TcgenMajor::K))
      report.violations.push_back(is_a ? TcgenF16Violation::AMajor
                                        : TcgenF16Violation::BMajor);
    report.checked.push_back(is_a ? TcgenF16Checked::AMajor
                                  : TcgenF16Checked::BMajor);
  }
  const auto decoded = decode_tcgen_shared(word);
  if (!decoded.swizzle ||
      (transpose && *decoded.swizzle == TcgenSwizzle::B128Atom32))
    report.violations.push_back(is_a ? TcgenF16Violation::ASwizzle
                                      : TcgenF16Violation::BSwizzle);
  report.checked.push_back(is_a ? TcgenF16Checked::ASwizzle
                                : TcgenF16Checked::BSwizzle);
}
}  // namespace

TcgenF16OperationalReport check_tcgen_f16_known_operation(
    const TcgenF16KnownFacts& facts) {
  TcgenF16OperationalReport report;
  report.instruction_fields =
      validate_tcgen_instruction_defined_fields(facts.instruction);
  report.checked.push_back(TcgenF16Checked::InstructionFields);
  if (facts.instruction.kind != TcgenMmaKind::F16) {
    report.violations.push_back(TcgenF16Violation::Kind);
    return report;
  }
  if (facts.group != TcgenCtaGroup::One && facts.group != TcgenCtaGroup::Two) {
    report.violations.push_back(TcgenF16Violation::Group);
    return report;
  }
  const auto decoded = decode_tcgen_instruction(facts.instruction);
  if (decoded.sparse) report.violations.push_back(TcgenF16Violation::DenseSparse);
  report.checked.push_back(TcgenF16Checked::Dense);
  const TcgenF16ShapeRow* shape = nullptr;
  for (const auto& row : kShapes) {
    if (row.group == facts.group && decoded.d_type &&
        row.d_type == *decoded.d_type &&
        tcgen_f16_row_contains(row, decoded.m, decoded.n, 16)) {
      shape = &row;
      break;
    }
  }
  if (!shape) report.violations.push_back(TcgenF16Violation::Shape);
  report.checked.push_back(TcgenF16Checked::Shape);
  if (decoded.d_type && decoded.a_type && decoded.b_type) {
    const bool output_f16 = *decoded.d_type == MatrixElementType::F16;
    const bool output_f32 = *decoded.d_type == MatrixElementType::F32;
    const auto input_allowed = [output_f16, output_f32](MatrixElementType type) {
      return (output_f16 && type == MatrixElementType::F16) ||
             (output_f32 && (type == MatrixElementType::F16 ||
                             type == MatrixElementType::BF16));
    };
    if (!input_allowed(*decoded.a_type))
      report.violations.push_back(TcgenF16Violation::AType);
    if (!input_allowed(*decoded.b_type))
      report.violations.push_back(TcgenF16Violation::BType);
    if (output_f32 && input_allowed(*decoded.a_type) &&
        input_allowed(*decoded.b_type) &&
        *decoded.a_type != *decoded.b_type)
      report.missing.push_back(TcgenF16Obligation::MixedInputPair);
    report.checked.push_back(TcgenF16Checked::Types);
  }
  if (facts.a_in_tmem) {
    if (facts.a_shared_word)
      report.violations.push_back(TcgenF16Violation::APlacementFacts);
  } else if (!facts.a_shared_word) {
    report.missing.push_back(TcgenF16Obligation::ASharedWord);
  } else {
    check_shared_operand(true, decoded.transpose_a, *facts.a_shared_word,
                         facts.a_context, facts, report);
  }
  if (!facts.b_shared_word) {
    report.missing.push_back(TcgenF16Obligation::BSharedWord);
  } else {
    check_shared_operand(false, decoded.transpose_b, *facts.b_shared_word,
                         facts.b_context, facts, report);
  }
  for (const auto& row : kPaths) {
    if (row.group != facts.group || row.m != decoded.m) continue;
    report.path_layout = row.layout;
    report.checked.push_back(TcgenF16Checked::Datapath);
    if (row.half_path && facts.a_in_tmem) {
      if (!facts.a_lane_half)
        report.missing.push_back(TcgenF16Obligation::ALaneHalf);
      else if (*facts.a_lane_half != 0 && *facts.a_lane_half != 16)
        report.violations.push_back(TcgenF16Violation::ALaneHalf);
      if (!facts.d_lane_half)
        report.missing.push_back(TcgenF16Obligation::DLaneHalf);
      else if (*facts.d_lane_half != 0 && *facts.d_lane_half != 16)
        report.violations.push_back(TcgenF16Violation::DLaneHalf);
      if (facts.a_lane_half && facts.d_lane_half &&
          (*facts.a_lane_half == 0 || *facts.a_lane_half == 16) &&
          (*facts.d_lane_half == 0 || *facts.d_lane_half == 16)) {
        if (*facts.a_lane_half != *facts.d_lane_half)
          report.violations.push_back(TcgenF16Violation::HalfAlignment);
        report.checked.push_back(TcgenF16Checked::HalfAlignment);
      }
    }
    break;
  }
  if (!facts.target || !facts.ptx_version)
    report.missing.push_back(TcgenF16Obligation::Target);
  else {
    if (!accepts_target(facts))
      report.violations.push_back(TcgenF16Violation::Target);
    report.checked.push_back(TcgenF16Checked::Target);
  }
  return report;
}
}  // namespace ptx_frontend::resolved_ir
'''
