"""Emit the public TCGEN known-word API from the single fixed-table catalogue."""

from __future__ import annotations

from pathlib import Path

from ptx_frontend.code_gen.context import GenerationContext
from ptx_frontend.spec import tcgen_descriptor_domains as domain


def _enum(name: str, members: tuple[str, ...]) -> str:
    """Emit a small closed public enum with stable catalogue order."""

    return (f"/** {name} identity for fixed TCGEN descriptor queries. */\n"
            f"enum class {name} : uint8_t {{ " + ", ".join(members) + " };\n")


def generate_tcgen_descriptor_header(
    _context: GenerationContext, *, output_path: Path
) -> None:
    """Write public value, field, report and layout declarations."""

    kinds = _enum("TcgenMmaKind", tuple(kind.name for kind in domain.KINDS))
    swizzles = _enum("TcgenSwizzle", tuple(name for _, name in domain.SWIZZLES))
    content = r'''// Generated by ptx_frontend.code_gen. Do not edit.
#pragma once
#include <array>
#include <cstdint>
#include <optional>
#include <span>
#include <string_view>
#include <vector>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_foundation.hpp>

namespace ptx_frontend::resolved_ir {

__KINDS__
__SWIZZLES__
/** Caller-supplied Table 43 bits, independent of any opaque source register. */
struct TcgenSharedWord { uint64_t bits; };
/** Caller-supplied Tables 45–47 bits and separately supplied MMA kind. */
struct TcgenInstructionWord { uint32_t bits; TcgenMmaKind kind; };
/** Caller-supplied Table 48 bits, independent of any opaque source register. */
struct TcgenZeroColumnWord { uint64_t bits; };
/** Semantic major of a TCGEN shared matrix. */
enum class TcgenMajor : uint8_t { K, MN };
/** Whether Table 43 leading bits encode relative spacing or an absolute chunk. */
enum class TcgenLeadingMode : uint8_t { Relative, Absolute };
/** Work-stealing register-reuse shift selected by Table 45. */
enum class TcgenReuseShift : uint8_t { None, B8, B16, B32 };
/** Word field table selected without unchecked indexing. */
enum class TcgenWordTableKind : uint8_t {
  Shared, Instruction45, Instruction46, Instruction47, ZeroColumn
};
/** One named encoded field; fixed_value is absent for variable fields. */
struct TcgenBitField {
  std::string_view name;
  uint8_t first_bit;
  uint8_t width;
  std::optional<uint32_t> fixed_value;
};
/** Immutable generated field partition; fields borrow static generated storage. */
struct TcgenWordTable {
  uint8_t width;
  std::span<const TcgenBitField> fields;
  uint64_t fixed_mask;
  uint64_t reserved_mask;
  uint64_t unclassified_mask;
};
/** Return the generated table, or null for an invalid cast enum. */
[[nodiscard]] const TcgenWordTable* tcgen_word_table(TcgenWordTableKind kind) noexcept;

/** Field-specific defined-word violation. */
enum class TcgenDescriptorViolation : uint8_t {
  FixedField, InvalidCode, InvalidKind, InvalidContext, Saturation, Negation,
  Transpose, ScaleId, SparseKChoice, Alignment, EncodedByteMismatch,
  AbsoluteSwizzle, AbsoluteBase, AbsoluteMajor, AbsoluteTranspose,
  AbsoluteTarget, PatternBase, ZeroPartition, ZeroShift
};
/** A fact needed to finish a conditional check without guessing runtime state. */
enum class TcgenDescriptorObligation : uint8_t {
  Major, Target, InstructionTranspose, PatternStart, PatternApplicability,
  LayoutApplicability, ZeroM, ZeroN
};
/** One defined-field violation with its associated encoded field mask. */
struct TcgenFieldFinding {
  TcgenDescriptorViolation kind;
  uint64_t field_mask;
};
/** Defined-fields result; unclassified bits are reported, not deemed reserved. */
struct TcgenDefinedFieldReport {
  std::vector<TcgenFieldFinding> violations;
  std::vector<TcgenDescriptorObligation> missing_context;
  uint64_t unclassified_bits{};
  /** Return whether all checks with supplied facts passed. */
  [[nodiscard]] bool defined_fields_ok() const noexcept { return violations.empty(); }
};

/** Independently supplied known byte facts, never inferred from the word. */
struct TcgenSharedByteFacts {
  std::optional<uint64_t> start;
  std::optional<uint64_t> leading;
  std::optional<uint64_t> stride;
  std::optional<uint64_t> absolute_next_chunk;
  std::optional<uint64_t> repeating_pattern_start;
};
/** Optional facts that scope Table 43 conditional checks. */
struct TcgenSharedContext {
  std::optional<TcgenMajor> major;
  std::optional<base::TargetIdentity> target;
  std::optional<checker::PtxVersion> ptx_version;
  std::optional<bool> transpose_a;
  std::optional<bool> transpose_b;
  TcgenSharedByteFacts bytes;
};
/** Raw and safely typed Table 43 fields with byte quantities limited to low 18 bits. */
struct TcgenSharedFields {
  uint16_t start_code;
  uint16_t leading_code;
  uint16_t stride_code;
  uint32_t start_low18_bytes;
  uint32_t leading_low18_bytes;
  uint32_t stride_low18_bytes;
  uint8_t base_code;
  uint8_t swizzle_code;
  std::optional<TcgenSwizzle> swizzle;
  TcgenLeadingMode leading_mode;
};
/** Return owned Table 43 field values, independent of operand lifetime. */
[[nodiscard]] TcgenSharedFields decode_tcgen_shared(TcgenSharedWord word) noexcept;
/** Validate Table 43 fixed and defined conditional fields only. */
[[nodiscard]] TcgenDefinedFieldReport validate_tcgen_shared_defined_fields(
    TcgenSharedWord word, const TcgenSharedContext& context);

/** Raw and conditional Tables 45–47 fields, including unqualified shape envelope. */
struct TcgenInstructionFields {
  TcgenMmaKind kind;
  TcgenWordTableKind table_kind;
  uint8_t a_code;
  uint8_t b_code;
  uint8_t d_code;
  uint8_t scale_a_code;
  uint8_t scale_b_code;
  uint8_t scale_type_code;
  uint8_t sparse_selector;
  bool sparse;
  bool saturate;
  bool negate_a;
  bool negate_b;
  bool transpose_a;
  bool transpose_b;
  uint16_t m;
  uint16_t n;
  uint8_t k_choice_code;
  std::optional<MatrixElementType> a_type;
  std::optional<MatrixElementType> b_type;
  std::optional<MatrixElementType> d_type;
  std::optional<MatrixScaleType> scale_type;
  std::optional<TcgenReuseShift> reuse_shift;
};
/** Decode fields selected by explicit kind; invalid kinds retain raw bits safely. */
[[nodiscard]] TcgenInstructionFields decode_tcgen_instruction(TcgenInstructionWord word) noexcept;
/** Validate only intrinsic Tables 45–47 fields, not Table 42 MMA legality. */
[[nodiscard]] TcgenDefinedFieldReport validate_tcgen_instruction_defined_fields(
    TcgenInstructionWord word);

/** Raw Table 48 fields; high two bits remain unclassified. */
struct TcgenZeroColumnFields {
  std::array<uint8_t, 4> start_counts;
  std::array<bool, 4> first_span;
  bool zero_all;
  uint16_t skip_span_columns;
  uint16_t use_span_columns;
  uint8_t shift_columns;
  uint64_t unclassified_bits;
};
/** Known dimensions for conditional zero-mask partition and shift checks. */
struct TcgenZeroContext { std::optional<uint32_t> m; std::optional<uint32_t> n; };
/** Active mask count and columns per active mask for supplied M/N. */
struct TcgenZeroPartition { uint8_t active_masks; uint32_t columns_per_mask; };
/** Decode Table 48 fields without claiming validity of unclassified bits. */
[[nodiscard]] TcgenZeroColumnFields decode_tcgen_zero_column(TcgenZeroColumnWord word) noexcept;
/** Query M/N partition; absence requires the report's applicability diagnostic. */
[[nodiscard]] std::optional<TcgenZeroPartition> tcgen_zero_partition(uint32_t m, uint32_t n) noexcept;
/** Validate Table 48 defined fields with optional M/N context. */
[[nodiscard]] TcgenDefinedFieldReport validate_tcgen_zero_defined_fields(
    TcgenZeroColumnWord word, const TcgenZeroContext& context);

/** One symbolic normalized layout factor, not a packed-byte calculation. */
enum class TcgenLayoutSymbol : uint8_t { One, T, M, K, LBO, SBO };
/** Positive multiplier of a symbolic normalized layout factor. */
struct TcgenLayoutTerm { uint8_t multiplier; TcgenLayoutSymbol symbol; };
/** Up to three factors in one shape or stride tuple. */
struct TcgenLayoutTuple {
  std::array<TcgenLayoutTerm, 3> terms;
  uint8_t size;
};
/** One of the eight documented relative major/swizzle layouts. */
struct TcgenRelativeLayoutRow {
  TcgenMajor major;
  TcgenSwizzle swizzle;
  std::array<TcgenLayoutTuple, 2> shape;
  std::array<TcgenLayoutTuple, 2> stride;
  std::array<uint8_t, 3> swizzle_tuple;
};
/** Return eight rows backed by immutable generated static storage. */
[[nodiscard]] std::span<const TcgenRelativeLayoutRow> tcgen_relative_layout_rows() noexcept;
/** Find a documented relative row; special code 1 has no invented ninth row. */
[[nodiscard]] const TcgenRelativeLayoutRow* tcgen_relative_layout(
    TcgenMajor major, TcgenSwizzle swizzle) noexcept;
/** Table 58 special code-1 MN atom, conditional on major and swizzle. */
[[nodiscard]] std::optional<std::array<uint8_t, 2>> tcgen_special_atom(
    TcgenMajor major, TcgenSwizzle swizzle) noexcept;

}  // namespace ptx_frontend::resolved_ir
'''
    content = content.replace("__KINDS__", kinds).replace("__SWIZZLES__", swizzles)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def generate_tcgen_descriptor_source(
    _context: GenerationContext, *, output_path: Path
) -> None:
    """Write pure defined-field algorithms and catalogue-derived static rows."""

    content = _source_text()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def _source_text() -> str:
    """Substitute all encoded facts from the immutable Python catalogue."""

    content = _SOURCE
    for word in domain.WORDS:
        rows = ",\n".join(
            '  TcgenBitField{"%s", %d, %d, %s}' % (
                field.name, field.first, field.width,
                ("std::nullopt" if field.fixed is None
                 else f"std::optional<uint32_t>{{{field.fixed}}}"),
            ) for field in word.fields
        )
        content = content.replace(f"__FIELDS_{word.name.upper()}__", rows)
        content = content.replace(f"__COUNT_{word.name.upper()}__", str(len(word.fields)))
        content = content.replace(f"__UNCLASSIFIED_{word.name.upper()}__",
                                  str(word.unclassified) + "ULL")
        content = content.replace(f"__FIXED_{word.name.upper()}__",
                                  str(word.fixed_mask) + "ULL")
        content = content.replace(f"__RESERVED_{word.name.upper()}__",
                                  str(word.reserved_mask) + "ULL")
        for field in word.fields:
            key = f"__{word.name.upper()}_{field.name.upper()}__"
            content = content.replace(key, str(field.first))
    content = content.replace("__SWIZZLE_ROWS__", ", ".join(
        f"{{{code}, TcgenSwizzle::{name}}}" for code, name in domain.SWIZZLES))
    content = content.replace("__SWIZZLE_COUNT__", str(len(domain.SWIZZLES)))
    backing, rows = _kind_rows()
    content = content.replace("__KIND_BACKING__", backing)
    content = content.replace("__KIND_ROWS__", rows)
    content = content.replace("__KIND_COUNT__", str(len(domain.KINDS)))
    content = content.replace("__LAYOUT_ROWS__", _layout_rows())
    content = content.replace("__PATTERN_ROWS__", ", ".join(
        f"{{{code}, {bytes_}}}" for code, bytes_ in domain.ORDINARY_PATTERN_BYTES))
    content = content.replace("__ABS_TARGET__", domain.ABSOLUTE_TARGET[0])
    content = content.replace("__ABS_PTX_MAJOR__", str(domain.ABSOLUTE_TARGET[1]))
    content = content.replace("__ABS_PTX_MINOR__", str(domain.ABSOLUTE_TARGET[2]))
    content = content.replace("__SPECIAL_ATOM_M__", str(domain.SPECIAL_ATOM[2]))
    content = content.replace("__SPECIAL_ATOM_N__", str(domain.SPECIAL_ATOM[3]))
    content = content.replace("__PARTITION_ROWS__", ", ".join(
        f"{{{m}, {count}}}" for m, count in domain.ZERO_PARTITIONS))
    return content


def _kind_rows() -> tuple[str, str]:
    """Emit one immutable record per explicit instruction kind."""

    backing: list[str] = []
    lines: list[str] = []
    for kind in domain.KINDS:
        table = next(i for i, word in enumerate(domain.WORDS)
                     if word.name == kind.table)
        stem = kind.name
        for suffix, cpp_type, rows, render in (
            ("A", "TypeCode", kind.a_types,
             lambda code, name: f"{{{code}, MatrixElementType::{name}}}"),
            ("B", "TypeCode", kind.b_types,
             lambda code, name: f"{{{code}, MatrixElementType::{name}}}"),
            ("D", "TypeCode", kind.d_types,
             lambda code, name: f"{{{code}, MatrixElementType::{name}}}"),
            ("ScaleIds", "uint8_t", tuple((code, "") for code in kind.scale_ids),
             lambda code, _name: str(code)),
            ("ScaleTypes", "ScaleCode", kind.scale_types,
             lambda code, name: f"{{{code}, MatrixScaleType::{name}}}"),
        ):
            values = ", ".join(render(code, name) for code, name in rows)
            backing.append(
                f"constexpr std::array<{cpp_type}, {len(rows)}> k{stem}{suffix} = "
                + "{{" + values + "}};"
            )
        lines.append(
            "  KindRule{TcgenMmaKind::%s, %d, k%sA, k%sB, k%sD, %s, %s, %s, k%sScaleIds, k%sScaleTypes}," % (
                kind.name, table, stem, stem, stem,
                "true" if kind.saturation else "false",
                "true" if kind.negate else "false",
                "true" if kind.transpose else "false", stem, stem,
            )
        )
    return "\n".join(backing), "\n".join(lines)


def _layout_rows() -> str:
    """Emit all eight relative rows with symbolic rather than truncated T."""

    def symbol(name: str) -> str:
        return {"one": "One", "T": "T", "m": "M", "k": "K",
                "LBO": "LBO", "SBO": "SBO"}[name]

    def group(items: tuple[domain.LayoutTerm, ...]) -> str:
        terms = ", ".join(
            f"TcgenLayoutTerm{{{term.coefficient}, TcgenLayoutSymbol::{symbol(term.symbol)}}}"
            for term in items
        )
        return "TcgenLayoutTuple{{" + terms + "}, " + str(len(items)) + "}"

    lines = []
    for row in domain.RELATIVE_LAYOUTS:
        shape = ", ".join(group(item) for item in row.shape)
        stride = ", ".join(group(item) for item in row.stride)
        swizzle = ", ".join(str(item) for item in row.swizzle_tuple)
        lines.append(
            "  TcgenRelativeLayoutRow{TcgenMajor::" + row.major +
            ", TcgenSwizzle::" + row.swizzle + ", {" + shape + "}, {" +
            stride + "}, {" + swizzle + "}},"
        )
    return "\n".join(lines)


_SOURCE = r'''// Generated by ptx_frontend.code_gen. Do not edit.
#include <ptx_frontend/resolved_ir/tcgen_descriptor_domains.gen.hpp>
#include <algorithm>
#include <array>
#include <utility>

namespace ptx_frontend::resolved_ir {
namespace {

constexpr std::array<TcgenBitField, __COUNT_SHARED__> kSharedFields = {{
__FIELDS_SHARED__
}};
constexpr std::array<TcgenBitField, __COUNT_INSTRUCTION_45__> kInstruction45Fields = {{
__FIELDS_INSTRUCTION_45__
}};
constexpr std::array<TcgenBitField, __COUNT_INSTRUCTION_46__> kInstruction46Fields = {{
__FIELDS_INSTRUCTION_46__
}};
constexpr std::array<TcgenBitField, __COUNT_INSTRUCTION_47__> kInstruction47Fields = {{
__FIELDS_INSTRUCTION_47__
}};
constexpr std::array<TcgenBitField, __COUNT_ZERO_COLUMN__> kZeroFields = {{
__FIELDS_ZERO_COLUMN__
}};
constexpr std::array<TcgenWordTable, 5> kWordTables = {{
  {64, kSharedFields, __FIXED_SHARED__, __RESERVED_SHARED__, __UNCLASSIFIED_SHARED__},
  {32, kInstruction45Fields, __FIXED_INSTRUCTION_45__, __RESERVED_INSTRUCTION_45__, __UNCLASSIFIED_INSTRUCTION_45__},
  {32, kInstruction46Fields, __FIXED_INSTRUCTION_46__, __RESERVED_INSTRUCTION_46__, __UNCLASSIFIED_INSTRUCTION_46__},
  {32, kInstruction47Fields, __FIXED_INSTRUCTION_47__, __RESERVED_INSTRUCTION_47__, __UNCLASSIFIED_INSTRUCTION_47__},
  {64, kZeroFields, __FIXED_ZERO_COLUMN__, __RESERVED_ZERO_COLUMN__, __UNCLASSIFIED_ZERO_COLUMN__},
}};
constexpr std::array<std::pair<uint8_t, TcgenSwizzle>, __SWIZZLE_COUNT__> kSwizzles = {{
  __SWIZZLE_ROWS__
}};
constexpr std::array<std::pair<uint8_t, uint16_t>, 3> kPatterns = {{
  __PATTERN_ROWS__
}};
constexpr std::array<std::pair<uint32_t, uint8_t>, 3> kPartitions = {{
  __PARTITION_ROWS__
}};
constexpr std::array<TcgenRelativeLayoutRow, 8> kLayouts = {{
__LAYOUT_ROWS__
}};

/** One encoded operand type result in a selected instruction kind. */
struct TypeCode { uint8_t code; MatrixElementType type; };
/** One encoded block-scale type result. */
struct ScaleCode { uint8_t code; MatrixScaleType type; };
/** Immutable table selection and intrinsic domains for one explicit MMA kind. */
struct KindRule {
  TcgenMmaKind kind;
  uint8_t table_index;
  std::span<const TypeCode> a_types;
  std::span<const TypeCode> b_types;
  std::span<const TypeCode> d_types;
  bool saturation;
  bool negate;
  bool transpose;
  std::span<const uint8_t> scale_ids;
  std::span<const ScaleCode> scale_types;
};
__KIND_BACKING__
constexpr std::array<KindRule, __KIND_COUNT__> kKinds = {{
__KIND_ROWS__
}};

/** Return the mask of one generated field without overflowing a word. */
uint64_t mask(const TcgenBitField& field) noexcept {
  return ((uint64_t{1} << field.width) - 1) << field.first_bit;
}
/** Extract a bounded field into its unsigned encoded value. */
uint32_t value(uint64_t word, const TcgenBitField& field) noexcept {
  return static_cast<uint32_t>((word & mask(field)) >> field.first_bit);
}
/** Find a field in static generated storage or return null. */
const TcgenBitField* field(const TcgenWordTable& table,
                            std::string_view name) noexcept {
  for (const auto& item : table.fields)
    if (item.name == name) return &item;
  return nullptr;
}
/** Extract a named field from the closed internal table. */
uint32_t get(uint64_t word, const TcgenWordTable& table,
             std::string_view name) noexcept {
  const auto* item = field(table, name);
  return item ? value(word, *item) : 0;
}
/** Return the exact rule for a valid explicit kind, if one exists. */
const KindRule* kind_rule(TcgenMmaKind kind) noexcept {
  for (const auto& rule : kKinds)
    if (rule.kind == kind) return &rule;
  return nullptr;
}
/** Safely turn one encoded value into a typed value from static backing. */
template <typename T, typename Entry>
std::optional<T> lookup(uint8_t code, std::span<const Entry> entries) noexcept {
  for (const auto& entry : entries)
    if (entry.code == code) return entry.type;
  return std::nullopt;
}
/** Append a field-specific defined-value failure. */
void add(TcgenDefinedFieldReport& report, TcgenDescriptorViolation violation,
         uint64_t bit_mask) {
  report.violations.push_back({violation, bit_mask});
}
/** Record a missing fact once, independently of field failures. */
void need(TcgenDefinedFieldReport& report, TcgenDescriptorObligation item) {
  if (std::find(report.missing_context.begin(), report.missing_context.end(), item)
      == report.missing_context.end())
    report.missing_context.push_back(item);
}
/** Compare every catalogue fixed field with its mandated code. */
void check_fixed(uint64_t bits, const TcgenWordTable& table,
                 TcgenDefinedFieldReport& report) {
  for (const auto& item : table.fields)
    if (item.fixed_value && value(bits, item) != *item.fixed_value)
      add(report, TcgenDescriptorViolation::FixedField, mask(item));
}
/** Check supplied bytes by alignment and their low-18-bit encoded relation. */
void check_bytes(std::optional<uint64_t> known, uint32_t encoded,
                 const TcgenBitField& field, TcgenDefinedFieldReport& report) {
  if (!known) return;
  if ((*known & 15) != 0)
    add(report, TcgenDescriptorViolation::Alignment, mask(field));
  if (((*known & 0x3ffffULL) >> 4) != encoded)
    add(report, TcgenDescriptorViolation::EncodedByteMismatch, mask(field));
}

}  // namespace

/** Return static field partition data without indexing an invalid enum. */
const TcgenWordTable* tcgen_word_table(TcgenWordTableKind kind) noexcept {
  const auto index = static_cast<uint8_t>(kind);
  return index < kWordTables.size() ? &kWordTables[index] : nullptr;
}

/** Decode Table 43 fields without asserting runtime source-register bits. */
TcgenSharedFields decode_tcgen_shared(TcgenSharedWord word) noexcept {
  const auto& table = kWordTables[0];
  const auto start = get(word.bits, table, "start");
  const auto leading = get(word.bits, table, "leading");
  const auto stride = get(word.bits, table, "stride");
  const auto swizzle_code = static_cast<uint8_t>(get(word.bits, table, "swizzle"));
  std::optional<TcgenSwizzle> swizzle;
  for (const auto& row : kSwizzles)
    if (row.first == swizzle_code) swizzle = row.second;
  return {static_cast<uint16_t>(start), static_cast<uint16_t>(leading),
          static_cast<uint16_t>(stride), start << 4, leading << 4, stride << 4,
          static_cast<uint8_t>(get(word.bits, table, "base")), swizzle_code,
          swizzle, get(word.bits, table, "absolute")
                       ? TcgenLeadingMode::Absolute : TcgenLeadingMode::Relative};
}

/** Validate Table 43 fields and separate conditional missing facts. */
TcgenDefinedFieldReport validate_tcgen_shared_defined_fields(
    TcgenSharedWord word, const TcgenSharedContext& context) {
  TcgenDefinedFieldReport report;
  const auto& table = kWordTables[0];
  check_fixed(word.bits, table, report);
  const auto decoded = decode_tcgen_shared(word);
  if (!decoded.swizzle)
    add(report, TcgenDescriptorViolation::InvalidCode,
        mask(*field(table, "swizzle")));
  check_bytes(context.bytes.start, decoded.start_code, *field(table, "start"), report);
  if (decoded.leading_mode == TcgenLeadingMode::Relative &&
      context.bytes.leading && !context.major)
    need(report, TcgenDescriptorObligation::Major);
  // In K-major swizzled mode the leading field is unused. An assumed-one
  // effective spacing never mandates any stored encoded leading value.
  if (decoded.leading_mode == TcgenLeadingMode::Relative && context.major &&
      (*context.major == TcgenMajor::MN ||
       (*context.major == TcgenMajor::K &&
        decoded.swizzle == TcgenSwizzle::None)))
    check_bytes(context.bytes.leading, decoded.leading_code,
                *field(table, "leading"), report);
  check_bytes(context.bytes.stride, decoded.stride_code,
              *field(table, "stride"), report);
  if (decoded.leading_mode == TcgenLeadingMode::Absolute)
    check_bytes(context.bytes.absolute_next_chunk, decoded.leading_code,
                *field(table, "leading"), report);
  if (decoded.leading_mode == TcgenLeadingMode::Absolute) {
    if (decoded.swizzle != TcgenSwizzle::B128Atom16)
      add(report, TcgenDescriptorViolation::AbsoluteSwizzle,
          mask(*field(table, "swizzle")));
    if (decoded.base_code)
      add(report, TcgenDescriptorViolation::AbsoluteBase,
          mask(*field(table, "base")));
    if (context.major && *context.major != TcgenMajor::K &&
        *context.major != TcgenMajor::MN)
      add(report, TcgenDescriptorViolation::InvalidContext, 0);
    if (!context.major) need(report, TcgenDescriptorObligation::Major);
    else if (*context.major != TcgenMajor::K)
      add(report, TcgenDescriptorViolation::AbsoluteMajor,
          mask(*field(table, "absolute")));
    if (!context.transpose_a || !context.transpose_b)
      need(report, TcgenDescriptorObligation::InstructionTranspose);
    if ((context.transpose_a && *context.transpose_a) ||
        (context.transpose_b && *context.transpose_b))
      add(report, TcgenDescriptorViolation::AbsoluteTranspose,
          mask(*field(table, "absolute")));
    if (!context.target || !context.ptx_version)
      need(report, TcgenDescriptorObligation::Target);
    else {
      const auto accepted = base::find_target_profile("__ABS_TARGET__");
      if (!accepted || *context.target != accepted->identity ||
          *context.ptx_version < checker::PtxVersion{__ABS_PTX_MAJOR__, __ABS_PTX_MINOR__})
        add(report, TcgenDescriptorViolation::AbsoluteTarget,
            mask(*field(table, "absolute")));
    }
  } else if (decoded.swizzle) {
    bool ordinary = false;
    for (const auto& [code, boundary] : kPatterns) {
      if (code != decoded.swizzle_code) continue;
      ordinary = true;
      if (!context.bytes.repeating_pattern_start)
        need(report, TcgenDescriptorObligation::PatternStart);
      else {
        const auto start = *context.bytes.repeating_pattern_start;
        const auto required = (start % boundary == 0) ? 0 : ((start >> 7) & 7);
        if (decoded.base_code != required)
          add(report, TcgenDescriptorViolation::PatternBase,
              mask(*field(table, "base")));
      }
    }
    if (!ordinary) need(report, TcgenDescriptorObligation::PatternApplicability);
    if (context.major && *context.major != TcgenMajor::K &&
        *context.major != TcgenMajor::MN)
      add(report, TcgenDescriptorViolation::InvalidContext, 0);
    if (!context.major) need(report, TcgenDescriptorObligation::Major);
    else if (!tcgen_relative_layout(*context.major, *decoded.swizzle))
      need(report, TcgenDescriptorObligation::LayoutApplicability);
  }
  return report;
}

/** Decode the selected Tables 45–47 fields with safe type-code lookup. */
TcgenInstructionFields decode_tcgen_instruction(TcgenInstructionWord word) noexcept {
  const auto* rule = kind_rule(word.kind);
  const auto& table = kWordTables[rule ? rule->table_index : 1];
  const auto a = static_cast<uint8_t>(get(word.bits, table, "a_type"));
  const auto b = static_cast<uint8_t>(get(word.bits, table, "b_type"));
  const auto d = static_cast<uint8_t>(get(word.bits, table, "d_type"));
  const auto scale_a = static_cast<uint8_t>(get(word.bits, table, "scale_a"));
  const auto scale_b = static_cast<uint8_t>(get(word.bits, table, "scale_b"));
  const auto scale_type = static_cast<uint8_t>(get(word.bits, table, "scale_type"));
  std::optional<TcgenReuseShift> reuse;
  if (rule && rule->table_index == 1)
    reuse = static_cast<TcgenReuseShift>(get(word.bits, table, "reuse"));
  return {word.kind, static_cast<TcgenWordTableKind>(rule ? rule->table_index : 1),
          a, b, d, scale_a, scale_b, scale_type,
          static_cast<uint8_t>(get(word.bits, table, "sparse_selector")),
          get(word.bits, table, "sparse") != 0,
          get(word.bits, table, "saturate") != 0,
          get(word.bits, table, "negate_a") != 0,
          get(word.bits, table, "negate_b") != 0,
          get(word.bits, table, "transpose_a") != 0,
          get(word.bits, table, "transpose_b") != 0,
          static_cast<uint16_t>(get(word.bits, table, "m") *
                                (rule && rule->table_index == 1 ? 16 : 128)),
          static_cast<uint16_t>(get(word.bits, table, "n") * 8),
          static_cast<uint8_t>(get(word.bits, table, "k_choice")),
          rule ? lookup<MatrixElementType>(a, rule->a_types) : std::nullopt,
          rule ? lookup<MatrixElementType>(b, rule->b_types) : std::nullopt,
          rule ? lookup<MatrixElementType>(d, rule->d_types) : std::nullopt,
          rule ? lookup<MatrixScaleType>(scale_type, rule->scale_types) : std::nullopt,
          reuse};
}

/** Check intrinsic selected-kind fields without Table 42 MMA assertions. */
TcgenDefinedFieldReport validate_tcgen_instruction_defined_fields(
    TcgenInstructionWord word) {
  TcgenDefinedFieldReport report;
  const auto* rule = kind_rule(word.kind);
  if (!rule) {
    add(report, TcgenDescriptorViolation::InvalidKind, 0);
    return report;
  }
  const auto& table = kWordTables[rule->table_index];
  check_fixed(word.bits, table, report);
  const auto decoded = decode_tcgen_instruction(word);
  if (!decoded.a_type)
    add(report, TcgenDescriptorViolation::InvalidCode, mask(*field(table, "a_type")));
  if (!decoded.b_type)
    add(report, TcgenDescriptorViolation::InvalidCode, mask(*field(table, "b_type")));
  if (rule->table_index == 1 && !decoded.d_type)
    add(report, TcgenDescriptorViolation::InvalidCode, mask(*field(table, "d_type")));
  if (decoded.saturate && !rule->saturation)
    add(report, TcgenDescriptorViolation::Saturation, mask(*field(table, "saturate")));
  if (!rule->negate && (decoded.negate_a || decoded.negate_b))
    add(report, TcgenDescriptorViolation::Negation,
        mask(*field(table, "negate_a")) | mask(*field(table, "negate_b")));
  if (!rule->transpose && (decoded.transpose_a || decoded.transpose_b))
    add(report, TcgenDescriptorViolation::Transpose,
        mask(*field(table, "transpose_a")) | mask(*field(table, "transpose_b")));
  if (!rule->scale_ids.empty()) {
    for (const auto name : {"scale_a", "scale_b"}) {
      const auto code = get(word.bits, table, name);
      if (std::find(rule->scale_ids.begin(), rule->scale_ids.end(), code)
          == rule->scale_ids.end())
        add(report, TcgenDescriptorViolation::ScaleId, mask(*field(table, name)));
    }
    if (!decoded.scale_type)
      add(report, TcgenDescriptorViolation::InvalidCode,
          mask(*field(table, "scale_type")));
  }
  if (rule->table_index == 3 && decoded.sparse && decoded.k_choice_code)
    add(report, TcgenDescriptorViolation::SparseKChoice,
        mask(*field(table, "k_choice")));
  return report;
}

/** Decode Table 48 fields while retaining both unclassified high bits. */
TcgenZeroColumnFields decode_tcgen_zero_column(TcgenZeroColumnWord word) noexcept {
  const auto& table = kWordTables[4];
  return {{{static_cast<uint8_t>(get(word.bits, table, "sc0")),
            static_cast<uint8_t>(get(word.bits, table, "sc1")),
            static_cast<uint8_t>(get(word.bits, table, "sc2")),
            static_cast<uint8_t>(get(word.bits, table, "sc3"))}},
          {{get(word.bits, table, "fs0") != 0, get(word.bits, table, "fs1") != 0,
            get(word.bits, table, "fs2") != 0, get(word.bits, table, "fs3") != 0}},
          get(word.bits, table, "zero_all") != 0,
          static_cast<uint16_t>(get(word.bits, table, "skip_span") + 1),
          static_cast<uint16_t>(get(word.bits, table, "use_span") + 1),
          static_cast<uint8_t>(get(word.bits, table, "shift")),
          word.bits & table.unclassified_mask};
}

/** Return the defined M/N partition only for positive divisible dimensions. */
std::optional<TcgenZeroPartition> tcgen_zero_partition(uint32_t m,
                                                         uint32_t n) noexcept {
  if (!n) return std::nullopt;
  for (const auto [rows, count] : kPartitions)
    if (m == rows && n % count == 0) return TcgenZeroPartition{count, n / count};
  return std::nullopt;
}

/** Check Table 48 defined fields and report absent M/N separately. */
TcgenDefinedFieldReport validate_tcgen_zero_defined_fields(
    TcgenZeroColumnWord word, const TcgenZeroContext& context) {
  TcgenDefinedFieldReport report;
  const auto& table = kWordTables[4];
  report.unclassified_bits = word.bits & table.unclassified_mask;
  check_fixed(word.bits, table, report);
  const auto decoded = decode_tcgen_zero_column(word);
  if (!context.m) need(report, TcgenDescriptorObligation::ZeroM);
  if (!context.n) need(report, TcgenDescriptorObligation::ZeroN);
  const bool supported_m = !context.m ||
      std::any_of(kPartitions.begin(), kPartitions.end(),
                  [&context](const auto& row) { return row.first == *context.m; });
  if (!supported_m ||
      (context.n && *context.n == 0) ||
      (context.m && context.n &&
       !tcgen_zero_partition(*context.m, *context.n)))
    add(report, TcgenDescriptorViolation::ZeroPartition, 0);
  if (decoded.shift_columns > 32 ||
      (context.m && *context.m == 32 && decoded.shift_columns > 16))
    add(report, TcgenDescriptorViolation::ZeroShift,
        mask(*field(table, "shift")));
  return report;
}

/** Borrow all eight immutable normalized relative layout rows. */
std::span<const TcgenRelativeLayoutRow> tcgen_relative_layout_rows() noexcept {
  return kLayouts;
}
/** Find one supported relative row or return null for special/invalid codes. */
const TcgenRelativeLayoutRow* tcgen_relative_layout(
    TcgenMajor major, TcgenSwizzle swizzle) noexcept {
  for (const auto& row : kLayouts)
    if (row.major == major && row.swizzle == swizzle) return &row;
  return nullptr;
}
/** Return the Table 58 special MN atom only in its conditional scope. */
std::optional<std::array<uint8_t, 2>> tcgen_special_atom(
    TcgenMajor major, TcgenSwizzle swizzle) noexcept {
  if (major == TcgenMajor::MN && swizzle == TcgenSwizzle::B128Atom32)
    return std::array<uint8_t, 2>{__SPECIAL_ATOM_M__, __SPECIAL_ATOM_N__};
  return std::nullopt;
}
}  // namespace ptx_frontend::resolved_ir
'''
