file(GLOB_RECURSE syntax_srcs CONFIGURE_DEPENDS src/*.cpp)
add_library(ptx_frontend_syntax STATIC ${syntax_srcs})
set_property(TARGET ptx_frontend_syntax PROPERTY EXPORT_NAME syntax)
add_library(ptx_frontend::syntax ALIAS ptx_frontend_syntax)
register_headers(ptx_frontend_syntax syntax PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(ptx_frontend_syntax PUBLIC ptx_frontend::base ptx_frontend::cst)

if(BUILD_TESTING)
    file(GLOB syntax_test_srcs CONFIGURE_DEPENDS test/*.cpp)
    add_executable(test_syntax ${syntax_test_srcs})
    find_package(GTest CONFIG REQUIRED)
    target_link_libraries(test_syntax PRIVATE GTest::gtest GTest::gtest_main ptx_frontend::syntax)
    gtest_discover_tests(test_syntax PROPERTIES TIMEOUT 10)
endif()
