file(GLOB_RECURSE syntax_srcs CONFIGURE_DEPENDS src/*.cpp)
add_library(syntax INTERFACE)
target_sources(syntax INTERFACE ${syntax_srcs})
add_library(ptx_frontend::syntax ALIAS syntax)
register_headers(syntax syntax INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(syntax INTERFACE ptx_frontend::cst)

if(BUILD_TESTING)
    file(GLOB syntax_test_srcs CONFIGURE_DEPENDS test/*.cpp)
    add_executable(test_syntax ${syntax_test_srcs})
    find_package(GTest CONFIG REQUIRED)
    target_link_libraries(test_syntax PRIVATE GTest::gtest GTest::gtest_main syntax)
    gtest_discover_tests(test_syntax)
endif()
