"""Emit checker descriptor storage derived from resolved-IR YAML metadata."""

from __future__ import annotations

from pathlib import Path
from collections.abc import Mapping

from ptx_frontend.base.utils import generated_at_comment
from ptx_frontend.code_gen.cpp_backend import CppDomain, cpp_value
from ptx_frontend.spec.database import CodegenDatabase
from ptx_frontend.spec.normalize import (
    parse_availability_target,
    validate_availability_family,
    validate_availability_sm_version,
)
from ptx_frontend.ir.resolved_ir import (
    ResolvedInstruction,
    ResolvedModifierValueDomain,
    ResolvedModifierValueAvailability,
    ResolvedOperandLayout,
    ResolvedOperandTypeCompatibility,
    ResolvedVariant,
    ResolvedValueKind,
    from_instruction_spec,
)
from ptx_frontend.code_gen.resolved_field_names import with_cpp_backend_field_names
from ptx_frontend.code_gen.resolved_value_traits import (
    modifier_value_descriptor_members,
)


def generate_resolved_checker_descriptor_source(
    database: CodegenDatabase,
    *,
    output_path: Path,
) -> None:
    """Generate private checker descriptor storage and instruction getters."""

    instructions = tuple(
        with_cpp_backend_field_names(from_instruction_spec(instruction))
        for instruction in database.instructions
    )
    _validate_unique_cpp_names(instructions)
    storage_definitions = "\n\n".join(
        _emit_instruction_descriptor_storage(instruction)
        for instruction in instructions
    )
    getter_definitions = "\n\n".join(
        _emit_instruction_descriptor_getter(instruction) for instruction in instructions
    )
    content = f"""// Generated by python/scripts/gen_all.py. Do not edit.
{generated_at_comment()}

#include <ptx_frontend/resolved_ir/ptx_resolved_ir_foundation.hpp>
#include <ptx_frontend/resolved_ir/ptx_resolved_ir_model.hpp>

namespace ptx_frontend::resolved_ir {{

namespace generated_detail {{

{storage_definitions}

}}  // namespace generated_detail

{getter_definitions}

}}  // namespace ptx_frontend::resolved_ir
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")


def _emit_instruction_descriptor_storage(instruction: ResolvedInstruction) -> str:
    storage_name = f"{instruction.cpp_name}CheckerDescriptorStorage"
    modifier_value_definitions = "\n\n".join(
        _emit_variant_modifier_value_descriptors(variant)
        for variant in instruction.variants
    )
    modifier_domain_definitions = "\n\n".join(
        _emit_variant_modifier_value_domain_descriptors(variant)
        for variant in instruction.variants
    )
    layout_definitions = "\n\n".join(
        _emit_variant_layout_descriptors(variant) for variant in instruction.variants
    )
    type_compatibility_definitions = "\n\n".join(
        _emit_variant_type_compatibility_descriptors(variant)
        for variant in instruction.variants
    )
    immediate_value_definitions = "\n\n".join(
        _emit_variant_immediate_value_descriptors(variant)
        for variant in instruction.variants
        if variant.immediate_value is not None
    )
    immediate_range_definitions = "\n\n".join(
        _emit_variant_immediate_range_descriptors(variant)
        for variant in instruction.variants
        if variant.immediate_ranges
    )
    address_alignment_definitions = "\n\n".join(
        _emit_variant_address_alignment_descriptors(variant)
        for variant in instruction.variants
        if variant.address_alignments
    )
    mmio_semantic_definitions = "\n\n".join(
        _emit_mmio_semantic_descriptors(variant)
        for variant in instruction.variants
        if variant.memory_consistency is not None
    )
    variants = ",\n".join(
        _emit_variant_descriptor(variant) for variant in instruction.variants
    )
    return f"""struct {storage_name} {{
{modifier_value_definitions}

{modifier_domain_definitions}

{layout_definitions}

{type_compatibility_definitions}

{immediate_value_definitions}

{immediate_range_definitions}

{address_alignment_definitions}

{mmio_semantic_definitions}

  static constexpr std::array<checker::VariantDescriptor, {len(instruction.variants)}>
      variants = {{
{variants}
      }};

  static constexpr checker::InstructionDescriptor descriptor{{
      .opcode_name = "{instruction.opcode}",
      .variants = variants,
  }};
}};
"""


def _emit_instruction_descriptor_getter(instruction: ResolvedInstruction) -> str:
    """Emit the checker descriptor getter outside generated_detail."""

    storage_name = f"{instruction.cpp_name}CheckerDescriptorStorage"
    return f"""\
const checker::InstructionDescriptor&
{instruction.cpp_name}::get_checker_descriptor() noexcept {{
  return generated_detail::{storage_name}::descriptor;
}}"""


def _emit_variant_descriptor(variant: ResolvedVariant) -> str:
    rule_id = variant.rule or ""
    consistency = variant.memory_consistency
    memory_consistency = ""
    if consistency is not None:
        memory_consistency = f"""
              .memory_consistency = {{
                  .semantics_field_id = "{consistency.semantics_field_id}",
                  .scope_field_id = "{consistency.scope_field_id}",
                  .mmio_field_id = "{consistency.mmio_field_id}",
                  .cache_field_id = "{consistency.cache_field_id}",
                  .address_field_id = "{consistency.address_field_id}",
                  .type_field_id = "{consistency.type_field_id}",
                  .state_space_field_id = "{consistency.state_space_field_id or ""}",
                  .mmio_semantics = {variant.cpp_name}_mmio_semantics,
              }},"""
    vector = variant.memory_vector
    memory_vector = ""
    if vector is not None:
        memory_vector = f"""
              .memory_vector = {{
                  .type_field_id = "{vector.type_field_id}",
                  .vector_field_id = "{vector.vector_field_id}",
                  .address_field_id = "{vector.address_field_id}",
                  .state_space_field_id = "{vector.state_space_field_id or ""}",
                  .availability = {_emit_availability(dict(vector.availability))},
                  .require_modern = {str(vector.require_modern).lower()},
              }},"""
    immediate_value = ""
    if variant.immediate_value is not None:
        immediate_value = f"""
              .immediate_value = {{
                  .operand_field_id = "{variant.immediate_value.operand_field_id}",
                  .allowed_values = {variant.cpp_name}_immediate_value_values,
              }},"""
    immediate_ranges = ""
    if variant.immediate_ranges:
        immediate_ranges = f"""
              .immediate_ranges = {variant.cpp_name}_immediate_ranges,"""
    immediate_multiple_of = ""
    if variant.immediate_multiple_of is not None:
        immediate_multiple_of = f"""
              .immediate_multiple_of = {{
                  .operand_field_id = "{variant.immediate_multiple_of.operand_field_id}",
                  .divisor = {_cpp_uint64(variant.immediate_multiple_of.divisor)},
              }},"""
    return f"""          checker::VariantDescriptor{{
              .variant_name = "{variant.cpp_name}",
              .availability = {_emit_availability(dict(variant.availability))},
              .modifier_value_domains = {variant.cpp_name}_modifier_value_domains,
              .modifier_value_availabilities =
                  {variant.cpp_name}_modifier_value_availabilities,
              .operand_layouts = {variant.cpp_name}_operand_layouts,
              .operand_type_compatibilities =
                  {variant.cpp_name}_operand_type_compatibilities,
              .rule_id = "{rule_id}",
              .permits_unified_address = {str(variant.permits_unified_address).lower()},
              .unified_address_access = checker::VariantDescriptor::UnifiedAddressAccess::{variant.unified_address_access.title()},
{memory_consistency}
{_emit_address_alignment_descriptor(variant)}
{memory_vector}
{immediate_value}
{immediate_multiple_of}
{immediate_ranges}
          }}"""


def _emit_mmio_semantic_descriptors(variant: ResolvedVariant) -> str:
    """Emit the target-qualified semantic alternatives permitted with MMIO."""

    consistency = variant.memory_consistency
    assert consistency is not None
    entries = ",\n".join(
        f"""          checker::VariantDescriptor::MmioSemanticDescriptor{{
              .semantics = {cpp_value(CppDomain.MEMORY_CONSISTENCIES, value)},
              .availability = {_emit_availability(dict(availability))},
          }}""" for value, availability in consistency.mmio_semantics
    )
    return f"""  static constexpr std::array<checker::VariantDescriptor::MmioSemanticDescriptor, {len(consistency.mmio_semantics)}>
      {variant.cpp_name}_mmio_semantics = {{{{
{entries}
      }}}};"""


def _emit_variant_immediate_value_descriptors(variant: ResolvedVariant) -> str:
    constraint = variant.immediate_value
    assert constraint is not None
    values = ", ".join(_cpp_uint64(value) for value in constraint.values)
    return f"""  static constexpr std::array<uint64_t, {len(constraint.values)}>
      {variant.cpp_name}_immediate_value_values = {{{{{values}}}}};"""


def _emit_variant_immediate_range_descriptors(variant: ResolvedVariant) -> str:
    entries = ",\n".join(
        f"""          checker::VariantDescriptor::ImmediateRangeDescriptor{{
              .operand_field_id = "{constraint.operand_field_id}",
              .minimum = {_cpp_uint64(constraint.minimum)},
              .has_maximum = {str(constraint.maximum is not None).lower()},
              .maximum = {_cpp_uint64(constraint.maximum) if constraint.maximum is not None else "~uint64_t{0}"},
          }}""" for constraint in variant.immediate_ranges
    )
    return f"""  static constexpr std::array<checker::VariantDescriptor::ImmediateRangeDescriptor, {len(variant.immediate_ranges)}>
      {variant.cpp_name}_immediate_ranges = {{{{
{entries}
      }}}};"""


def _cpp_uint64(value: int) -> str:
    """Emit one portable exact uint64_t initializer from normalized metadata."""

    return f"uint64_t{{{value}ULL}}"


def _emit_address_alignment_descriptor(variant: ResolvedVariant) -> str:
    if not variant.address_alignments:
        return ""
    return f"""              .address_alignments = {variant.cpp_name}_address_alignments,"""


def _emit_variant_address_alignment_descriptors(variant: ResolvedVariant) -> str:
    fields = "\n".join(
        f'''  static constexpr std::array<std::string_view, {len(alignment.address_field_ids)}>
      {variant.cpp_name}_address_alignment_{index}_address_fields = {{{{{", ".join(f'\"{address}\"' for address in alignment.address_field_ids)}}}}};'''
        for index, alignment in enumerate(variant.address_alignments)
    )
    entries = ",\n".join(f"""          checker::AddressAlignmentConstraint{{
              .address_field_ids = {variant.cpp_name}_address_alignment_{index}_address_fields,
              .type_field_id = "{alignment.type_field_id or ""}",
              .vector_field_id = "{alignment.vector_field_id or ""}",
              .immediate_operand_field_id = "{alignment.immediate_operand_field_id or ""}",
              .alignment = {alignment.alignment or 0},
          }}""" for index, alignment in enumerate(variant.address_alignments))
    return f"""{fields}
  static constexpr std::array<checker::AddressAlignmentConstraint, {len(variant.address_alignments)}>
      {variant.cpp_name}_address_alignments = {{{{
{entries}
      }}}};"""


def _emit_variant_modifier_value_descriptors(variant: ResolvedVariant) -> str:
    entries = ",\n".join(
        _emit_modifier_value_descriptor(entry)
        for entry in variant.modifier_value_availabilities
    )
    return f"""  static constexpr std::array<checker::ModifierValueAvailabilityDescriptor, {len(variant.modifier_value_availabilities)}>
      {variant.cpp_name}_modifier_value_availabilities = {{
{entries}
      }};"""


def _emit_variant_modifier_value_domain_descriptors(
    variant: ResolvedVariant,
) -> str:
    """Emit every typed semantic modifier value admitted by one variant."""

    entries = ",\n".join(
        _emit_modifier_value_domain_descriptor(entry)
        for entry in variant.modifier_value_domains
    )
    return f"""  static constexpr std::array<checker::ModifierValueDomainDescriptor, {len(variant.modifier_value_domains)}>
      {variant.cpp_name}_modifier_value_domains = {{
{entries}
      }};"""


def _emit_modifier_value_descriptor(
    entry: ResolvedModifierValueAvailability | ResolvedModifierValueDomain,
    *,
    descriptor_type: str = "checker::ModifierValueAvailabilityDescriptor",
    include_availability: bool = True,
) -> str:
    """Emit one typed modifier descriptor, with optional target metadata."""

    members = modifier_value_descriptor_members(
        entry.value_kind,
        entry.value,
    )

    availability = ""
    if include_availability:
        assert isinstance(
            entry,
            ResolvedModifierValueAvailability,
        )
        availability = (
            f"              .availability = "
            f"{_emit_availability(dict(entry.availability))},\n"
        )

    return f"""          {descriptor_type}{{
              .kind_id = "{entry.source_kind_id}",
              .value_kind = {cpp_value(
                  CppDomain.CHECKER_MODIFIER_VALUE_KINDS,
                  entry.value_kind.value,
              )},
              .bool_value = {members[ResolvedValueKind.BOOL]},
              .scalar_type = {members[ResolvedValueKind.SCALAR_TYPE]},
              .rounding_mode = {members[ResolvedValueKind.ROUNDING_MODE]},
              .comparison_operator = {members[ResolvedValueKind.COMPARISON_OPERATOR]},
              .boolean_operator = {members[ResolvedValueKind.BOOLEAN_OPERATOR]},
              .cache_operator = {members[ResolvedValueKind.CACHE_OPERATOR]},
              .eviction_priority = {members[ResolvedValueKind.EVICTION_PRIORITY]},
              .prefetch_size = {members[ResolvedValueKind.PREFETCH_SIZE]},
              .vector_arity = {members[ResolvedValueKind.VECTOR_ARITY]},
              .memory_state_space = {members[ResolvedValueKind.MEMORY_STATE_SPACE]},
              .memory_consistency = {members[ResolvedValueKind.MEMORY_CONSISTENCY]},
              .memory_scope = {members[ResolvedValueKind.MEMORY_SCOPE]},
              .mbarrier_phase_type = {members[ResolvedValueKind.MBARRIER_PHASE_TYPE]},
              .mbarrier_layout = {members[ResolvedValueKind.MBARRIER_LAYOUT]},
              .async_proxy_kind = {members[ResolvedValueKind.ASYNC_PROXY_KIND]},
              .proxy_kind_pair = {members[ResolvedValueKind.PROXY_KIND_PAIR]},
{availability}
          }}"""


def _emit_modifier_value_domain_descriptor(
    entry: ResolvedModifierValueDomain,
) -> str:
    """Emit one target-independent typed semantic modifier value."""

    return _emit_modifier_value_descriptor(
        entry,
        descriptor_type="checker::ModifierValueDomainDescriptor",
        include_availability=False,
    )


def _emit_variant_layout_descriptors(variant: ResolvedVariant) -> str:
    """Emit checker availability metadata for every layout of one variant."""

    entries = ",\n".join(
        _emit_operand_layout_descriptor(layout) for layout in variant.operand_layouts
    )
    return f"""  static constexpr std::array<checker::OperandLayoutDescriptor, {len(variant.operand_layouts)}>
      {variant.cpp_name}_operand_layouts = {{
{entries}
      }};"""


def _emit_operand_layout_descriptor(layout: ResolvedOperandLayout) -> str:
    return f"""          checker::OperandLayoutDescriptor{{
              .layout_name = "{layout.layout_id}",
              .availability = {_emit_availability(dict(layout.availability))},
          }}"""


def _emit_variant_type_compatibility_descriptors(
    variant: ResolvedVariant,
) -> str:
    entries = ",\n".join(
        _emit_operand_type_compatibility_descriptor(entry)
        for entry in variant.operand_type_compatibilities
    )
    return f"""  static constexpr std::array<checker::OperandTypeCompatibilityDescriptor, {len(variant.operand_type_compatibilities)}>
      {variant.cpp_name}_operand_type_compatibilities = {{{{
{entries}
      }}}};"""


def _emit_operand_type_compatibility_descriptor(
    entry: ResolvedOperandTypeCompatibility,
) -> str:
    return f"""          checker::OperandTypeCompatibilityDescriptor{{
              .target_field_id = "{entry.target_field_id}",
              .special_register_kind = {cpp_value(CppDomain.SPECIAL_REGISTER_KINDS, entry.special_register_kind)},
              .instruction_width = {entry.instruction_width},
              .effective_type = {cpp_value(CppDomain.SCALAR_TYPES, entry.effective_type)},
              .availability = {_emit_availability(dict(entry.availability))},
          }}"""


def _emit_availability(availability: Mapping[str, object]) -> str:
    if "any_of" not in availability:
        minimum_ptx = _parse_ptx_version(availability.get("ptx", "0.0"))
        return f"""{{
                  .minimum_ptx_version = {{{minimum_ptx[0]}, {minimum_ptx[1]}}},
                  .minimum_sm_version = {validate_availability_sm_version(availability.get("sm", 0))},
                  .required_family = "{validate_availability_family(availability["family"]) if "family" in availability else ""}",
              }}"""

    clauses = availability["any_of"]
    assert isinstance(clauses, list)
    emitted = []
    for clause in clauses:
        assert isinstance(clause, dict)
        minimum_ptx = _parse_ptx_version(clause.get("ptx", "0.0"))
        target = clause.get("target")
        number, flavor = (
            parse_availability_target(target) if target is not None else (0, "Generic")
        )
        family = (
            validate_availability_family(clause["family"]) if "family" in clause else ""
        )
        capabilities = clause.get("capabilities", [])
        assert isinstance(capabilities, list)
        capability_values = ", ".join(f'"{value}"' for value in capabilities)
        emitted.append(f"""checker::AvailabilityClause{{
                      .minimum_ptx_version = {{{minimum_ptx[0]}, {minimum_ptx[1]}}},
                      .minimum_sm_version = {validate_availability_sm_version(clause.get("sm", 0))},
                      .has_exact_target = {str(target is not None).lower()},
                      .exact_target_architecture = {{{number}}},
                      .exact_target_flavor = base::TargetFlavor::{flavor},
                      .required_family = "{family}",
                      .capabilities = {{{{{capability_values}}}}},
                      .capability_count = {len(capabilities)},
                  }}""")
    return f'''{{
                  .any_of = {{{{
                      {",\n                      ".join(emitted)}
                  }}}},
                  .any_of_count = {len(clauses)},
              }}'''


def _parse_ptx_version(value: object) -> tuple[int, int]:
    text = str(value)
    pieces = text.split(".")
    if len(pieces) != 2 or not all(piece.isdecimal() for piece in pieces):
        raise ValueError(f"invalid PTX availability version {value!r}")
    major, minor = (int(piece) for piece in pieces)
    if not (0 <= major <= 0xFFFF and 0 <= minor <= 0xFFFF):
        raise ValueError(f"PTX availability version is out of range: {value!r}")
    return major, minor


def _validate_unique_cpp_names(instructions: tuple[ResolvedInstruction, ...]) -> None:
    seen: set[str] = set()
    for instruction in instructions:
        if instruction.cpp_name in seen:
            raise ValueError(
                f"multiple resolved instructions map to C++ type "
                f"{instruction.cpp_name!r}"
            )
        seen.add(instruction.cpp_name)
