[metadata]
name = ptx_frontend
version = 0.0.1b0
description = ptx frontend helper packages
author = endingly

[options]
packages = find:
include_package_data = True
install_requires =
    PyYAML>=6.0,<7
    jsonschema>=4.26,<5

[options.package_data]
code_gen =
    resources/*.yaml
    resources/ptx_spec/*.yaml

[options.entry_points]
console_scripts =
    ptx-frontend-codegen = code_gen.cli:main

[options.packages.find]
where = .
exclude =
    test
    test.*
    tests
    tests.*
