[metadata]
name = ptx_frontend
version = 0.0.1b0
description = ptx frontend helper packages
author = endingly

[options]
packages =
    ptx_frontend.base
    ptx_frontend.code_gen
    ptx_frontend.code_gen.resources
    ptx_frontend.ir
package_dir =
    ptx_frontend.base = base
    ptx_frontend.code_gen = code_gen
    ptx_frontend.code_gen.resources = code_gen/resources
    ptx_frontend.ir = ir
include_package_data = True
install_requires =
    PyYAML>=6.0,<7
    jsonschema>=4.26,<5

[options.package_data]
ptx_frontend.code_gen.resources =
    *.yaml
    ptx_spec/*.yaml

[options.entry_points]
console_scripts =
    ptx-frontend-codegen = ptx_frontend.code_gen.cli:main
