// AUTO-GENERATED by scripts/gen_visit_dispatch.py — DO NOT EDIT
#pragma once
#include "ptx_visit.hpp"

namespace ptx_frontend {

template <OperandLike Op, typename Err>
inline expected<void, Err> visit_instruction(
    const Instruction<Op>& instr,
    Visitor<Op, Err>& visitor,
    std::optional<VisitTypeSpace> type_space,
    bool relaxed_type_check) {
  return std::visit([&](const auto& i) -> expected<void, Err> {
    using T = std::decay_t<decltype(i)>;
    if constexpr (std::is_same_v<T, InstrAbs<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrActivemask<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAdd<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAddExtended<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSubExtended<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMadExtended<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAnd<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAtom<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAtomCas<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBarWarp<Op>>) {
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBar<Op>>) {
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (i.src2.has_value()) {
        if (auto _r = visitor.visit(*i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      }
      return {};
    } else if constexpr (std::is_same_v<T, InstrBarRed<Op>>) {
      if (auto _r = visitor.visit(i.dst1, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_barrier, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_predicate, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_negate_predicate, type_space, false, relaxed_type_check); !_r) return _r;
      if (i.src_threadcount.has_value()) {
        if (auto _r = visitor.visit(*i.src_threadcount, type_space, false, relaxed_type_check); !_r) return _r;
      }
      return {};
    } else if constexpr (std::is_same_v<T, InstrBfe<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBfi<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src4, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBmsk<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_a, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_b, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBra<typename Op::id_type>>) {
      if (auto _r = visitor.visit_ident(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBrev<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCall<Op>>) {
      if (auto _r = visitor.visit_ident(i.arguments.func, type_space, false, relaxed_type_check); !_r) return _r;
      for (const auto& _ra : i.arguments.return_arguments) {
        if (auto _r = visitor.visit_ident(_ra, type_space, true, relaxed_type_check); !_r) return _r;
      }
      for (const auto& _ia : i.arguments.input_arguments) {
        if (auto _r = visitor.visit(_ia, type_space, false, relaxed_type_check); !_r) return _r;
      }
      return {};
    } else if constexpr (std::is_same_v<T, InstrClz<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCos<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCpAsync<Op>>) {
      if (auto _r = visitor.visit(i.src_to, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_from, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCpAsyncCommitGroup>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrCpAsyncWaitGroup<Op>>) {
      if (auto _r = visitor.visit(i.src_group, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCpAsyncWaitAll>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrCreatePolicyFractional<Op>>) {
      if (auto _r = visitor.visit(i.dst_policy, type_space, true, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCvt<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      if (i.src2.has_value()) {
        if (auto _r = visitor.visit(*i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      }
      return {};
    } else if constexpr (std::is_same_v<T, InstrCvtPack<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCvta<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrDiv<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrDp4a<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrEx2<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrFma<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrLd<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrLg2<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMad<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMax<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMembar>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrMin<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMov<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMul<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMul24<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrNanosleep<Op>>) {
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrNeg<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrNot<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrOr<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrPopc<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrPrmt<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrRcp<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrRem<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrRet>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrRsqrt<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSelp<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSet<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSetBool<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSetp<Op>>) {
      if (auto _r = visitor.visit(i.dst1, type_space, true, relaxed_type_check); !_r) return _r;
      if (i.dst2.has_value()) {
        if (auto _r = visitor.visit(*i.dst2, type_space, true, relaxed_type_check); !_r) return _r;
      }
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSetpBool<Op>>) {
      if (auto _r = visitor.visit(i.dst1, type_space, true, relaxed_type_check); !_r) return _r;
      if (i.dst2.has_value()) {
        if (auto _r = visitor.visit(*i.dst2, type_space, true, relaxed_type_check); !_r) return _r;
      }
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrShflSync<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (i.dst_pred.has_value()) {
        if (auto _r = visitor.visit(*i.dst_pred, type_space, true, relaxed_type_check); !_r) return _r;
      }
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_lane, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_opts, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_membermask, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrShf<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_a, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_b, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_c, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrShl<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrShr<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSin<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSqrt<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSt<Op>>) {
      if (auto _r = visitor.visit(i.src1, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSub<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrTrap>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrXor<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrTanh<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrVote<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrReduxSync<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_membermask, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrLdMatrix<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrGridDepControl>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrMma<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCopysign<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrPrefetch<Op>>) {
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSad<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrDp2a<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else {
      static_assert(!std::is_same_v<T, T>, "unhandled instruction type in visit_instruction");
    }
  }, instr);
}

template <OperandLike Op, typename Err>
inline expected<void, Err> visit_instruction_mut(
    Instruction<Op>& instr,
    VisitorMut<Op, Err>& visitor,
    std::optional<VisitTypeSpace> type_space,
    bool relaxed_type_check) {
  return std::visit([&](auto& i) -> expected<void, Err> {
    using T = std::decay_t<decltype(i)>;
    if constexpr (std::is_same_v<T, InstrAbs<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrActivemask<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAdd<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAddExtended<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSubExtended<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMadExtended<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAnd<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAtom<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrAtomCas<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBarWarp<Op>>) {
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBar<Op>>) {
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (i.src2.has_value()) {
        if (auto _r = visitor.visit(*i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      }
      return {};
    } else if constexpr (std::is_same_v<T, InstrBarRed<Op>>) {
      if (auto _r = visitor.visit(i.dst1, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_barrier, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_predicate, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_negate_predicate, type_space, false, relaxed_type_check); !_r) return _r;
      if (i.src_threadcount.has_value()) {
        if (auto _r = visitor.visit(*i.src_threadcount, type_space, false, relaxed_type_check); !_r) return _r;
      }
      return {};
    } else if constexpr (std::is_same_v<T, InstrBfe<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBfi<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src4, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBmsk<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_a, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_b, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBra<typename Op::id_type>>) {
      if (auto _r = visitor.visit_ident(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrBrev<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCall<Op>>) {
      if (auto _r = visitor.visit_ident(i.arguments.func, type_space, false, relaxed_type_check); !_r) return _r;
      for (auto& _ra : i.arguments.return_arguments) {
        if (auto _r = visitor.visit_ident(_ra, type_space, true, relaxed_type_check); !_r) return _r;
      }
      for (auto& _ia : i.arguments.input_arguments) {
        if (auto _r = visitor.visit(_ia, type_space, false, relaxed_type_check); !_r) return _r;
      }
      return {};
    } else if constexpr (std::is_same_v<T, InstrClz<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCos<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCpAsync<Op>>) {
      if (auto _r = visitor.visit(i.src_to, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_from, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCpAsyncCommitGroup>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrCpAsyncWaitGroup<Op>>) {
      if (auto _r = visitor.visit(i.src_group, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCpAsyncWaitAll>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrCreatePolicyFractional<Op>>) {
      if (auto _r = visitor.visit(i.dst_policy, type_space, true, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCvt<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      if (i.src2.has_value()) {
        if (auto _r = visitor.visit(*i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      }
      return {};
    } else if constexpr (std::is_same_v<T, InstrCvtPack<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCvta<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrDiv<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrDp4a<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrEx2<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrFma<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrLd<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrLg2<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMad<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMax<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMembar>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrMin<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMov<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMul<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrMul24<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrNanosleep<Op>>) {
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrNeg<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrNot<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrOr<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrPopc<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrPrmt<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrRcp<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrRem<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrRet>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrRsqrt<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSelp<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSet<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSetBool<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSetp<Op>>) {
      if (auto _r = visitor.visit(i.dst1, type_space, true, relaxed_type_check); !_r) return _r;
      if (i.dst2.has_value()) {
        if (auto _r = visitor.visit(*i.dst2, type_space, true, relaxed_type_check); !_r) return _r;
      }
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSetpBool<Op>>) {
      if (auto _r = visitor.visit(i.dst1, type_space, true, relaxed_type_check); !_r) return _r;
      if (i.dst2.has_value()) {
        if (auto _r = visitor.visit(*i.dst2, type_space, true, relaxed_type_check); !_r) return _r;
      }
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrShflSync<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (i.dst_pred.has_value()) {
        if (auto _r = visitor.visit(*i.dst_pred, type_space, true, relaxed_type_check); !_r) return _r;
      }
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_lane, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_opts, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_membermask, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrShf<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_a, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_b, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_c, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrShl<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrShr<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSin<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSqrt<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSt<Op>>) {
      if (auto _r = visitor.visit(i.src1, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSub<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrTrap>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrXor<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrTanh<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrVote<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrReduxSync<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src_membermask, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrLdMatrix<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrGridDepControl>) {
      return {};
    } else if constexpr (std::is_same_v<T, InstrMma<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrCopysign<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrPrefetch<Op>>) {
      if (auto _r = visitor.visit(i.src, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrSad<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else if constexpr (std::is_same_v<T, InstrDp2a<Op>>) {
      if (auto _r = visitor.visit(i.dst, type_space, true, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src1, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src2, type_space, false, relaxed_type_check); !_r) return _r;
      if (auto _r = visitor.visit(i.src3, type_space, false, relaxed_type_check); !_r) return _r;
      return {};
    } else {
      static_assert(!std::is_same_v<T, T>, "unhandled instruction type in visit_instruction_mut");
    }
  }, instr);
}

template <OperandLike Op, OperandLike NewOp, typename Err>
inline expected<Instruction<NewOp>, Err> visit_instruction_map(
    Instruction<Op> instr,
    VisitorMap<Op, NewOp, Err>& visitor,
    std::optional<VisitTypeSpace> type_space,
    bool relaxed_type_check) {
  return std::visit([&](auto&& i) -> expected<Instruction<NewOp>, Err> {
    using T = std::decay_t<decltype(i)>;
    if constexpr (std::is_same_v<T, InstrAbs<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrAbs<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrActivemask<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      return InstrActivemask<NewOp>{.dst = std::move(*_r_dst)};
    } else if constexpr (std::is_same_v<T, InstrAdd<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrAdd<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrAddExtended<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrAddExtended<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrSubExtended<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrSubExtended<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrMadExtended<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrMadExtended<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrAnd<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrAnd<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrAtom<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrAtom<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrAtomCas<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrAtomCas<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrBarWarp<Op>>) {
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrBarWarp<NewOp>{.src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrBar<Op>>) {
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      std::optional<NewOp> _r_src2;
      if (i.src2.has_value()) {
        auto _mapped = visitor.visit(std::move(*i.src2), type_space, false, relaxed_type_check);
        if (!_mapped) return tl::unexpected(_mapped.error());
        _r_src2 = std::move(*_mapped);
      }
      return InstrBar<NewOp>{.data = i.data, .src1 = std::move(*_r_src1), .src2 = std::move(_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrBarRed<Op>>) {
      auto _r_dst1 = visitor.visit(std::move(i.dst1), type_space, true, relaxed_type_check);
      if (!_r_dst1) return tl::unexpected(_r_dst1.error());
      auto _r_src_barrier = visitor.visit(std::move(i.src_barrier), type_space, false, relaxed_type_check);
      if (!_r_src_barrier) return tl::unexpected(_r_src_barrier.error());
      auto _r_src_predicate = visitor.visit(std::move(i.src_predicate), type_space, false, relaxed_type_check);
      if (!_r_src_predicate) return tl::unexpected(_r_src_predicate.error());
      auto _r_src_negate_predicate = visitor.visit(std::move(i.src_negate_predicate), type_space, false, relaxed_type_check);
      if (!_r_src_negate_predicate) return tl::unexpected(_r_src_negate_predicate.error());
      std::optional<NewOp> _r_src_threadcount;
      if (i.src_threadcount.has_value()) {
        auto _mapped = visitor.visit(std::move(*i.src_threadcount), type_space, false, relaxed_type_check);
        if (!_mapped) return tl::unexpected(_mapped.error());
        _r_src_threadcount = std::move(*_mapped);
      }
      return InstrBarRed<NewOp>{.data = i.data, .dst1 = std::move(*_r_dst1), .src_barrier = std::move(*_r_src_barrier), .src_predicate = std::move(*_r_src_predicate), .src_negate_predicate = std::move(*_r_src_negate_predicate), .src_threadcount = std::move(_r_src_threadcount)};
    } else if constexpr (std::is_same_v<T, InstrBfe<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrBfe<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrBfi<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      auto _r_src4 = visitor.visit(std::move(i.src4), type_space, false, relaxed_type_check);
      if (!_r_src4) return tl::unexpected(_r_src4.error());
      return InstrBfi<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3), .src4 = std::move(*_r_src4)};
    } else if constexpr (std::is_same_v<T, InstrBmsk<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src_a = visitor.visit(std::move(i.src_a), type_space, false, relaxed_type_check);
      if (!_r_src_a) return tl::unexpected(_r_src_a.error());
      auto _r_src_b = visitor.visit(std::move(i.src_b), type_space, false, relaxed_type_check);
      if (!_r_src_b) return tl::unexpected(_r_src_b.error());
      return InstrBmsk<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src_a = std::move(*_r_src_a), .src_b = std::move(*_r_src_b)};
    } else if constexpr (std::is_same_v<T, InstrBra<typename Op::id_type>>) {
      auto _r_src = visitor.visit_ident(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrBra<typename NewOp::id_type>{.src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrBrev<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrBrev<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrCall<Op>>) {
      CallArgs<typename NewOp::id_type> _new_args;
      _new_args.is_external = i.arguments.is_external;
      {
        auto _r = visitor.visit_ident(std::move(i.arguments.func), type_space, false, relaxed_type_check);
        if (!_r) return tl::unexpected(_r.error());
        _new_args.func = std::move(*_r);
      }
      for (auto&& _ra : i.arguments.return_arguments) {
        auto _r = visitor.visit_ident(std::move(_ra), type_space, true, relaxed_type_check);
        if (!_r) return tl::unexpected(_r.error());
        _new_args.return_arguments.push_back(std::move(*_r));
      }
      for (auto&& _ia : i.arguments.input_arguments) {
        auto _r = visitor.visit(std::move(_ia), type_space, false, relaxed_type_check);
        if (!_r) return tl::unexpected(_r.error());
        _new_args.input_arguments.push_back(std::move(*_r));
      }
      return InstrCall<NewOp>{.data = i.data, .arguments = std::move(_new_args)};
    } else if constexpr (std::is_same_v<T, InstrClz<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrClz<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrCos<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrCos<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrCpAsync<Op>>) {
      auto _r_src_to = visitor.visit(std::move(i.src_to), type_space, true, relaxed_type_check);
      if (!_r_src_to) return tl::unexpected(_r_src_to.error());
      auto _r_src_from = visitor.visit(std::move(i.src_from), type_space, false, relaxed_type_check);
      if (!_r_src_from) return tl::unexpected(_r_src_from.error());
      return InstrCpAsync<NewOp>{.data = i.data, .src_to = std::move(*_r_src_to), .src_from = std::move(*_r_src_from)};
    } else if constexpr (std::is_same_v<T, InstrCpAsyncCommitGroup>) {
      return InstrCpAsyncCommitGroup{};
    } else if constexpr (std::is_same_v<T, InstrCpAsyncWaitGroup<Op>>) {
      auto _r_src_group = visitor.visit(std::move(i.src_group), type_space, false, relaxed_type_check);
      if (!_r_src_group) return tl::unexpected(_r_src_group.error());
      return InstrCpAsyncWaitGroup<NewOp>{.src_group = std::move(*_r_src_group)};
    } else if constexpr (std::is_same_v<T, InstrCpAsyncWaitAll>) {
      return InstrCpAsyncWaitAll{};
    } else if constexpr (std::is_same_v<T, InstrCreatePolicyFractional<Op>>) {
      auto _r_dst_policy = visitor.visit(std::move(i.dst_policy), type_space, true, relaxed_type_check);
      if (!_r_dst_policy) return tl::unexpected(_r_dst_policy.error());
      return InstrCreatePolicyFractional<NewOp>{.data = i.data, .dst_policy = std::move(*_r_dst_policy)};
    } else if constexpr (std::is_same_v<T, InstrCvt<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      std::optional<NewOp> _r_src2;
      if (i.src2.has_value()) {
        auto _mapped = visitor.visit(std::move(*i.src2), type_space, false, relaxed_type_check);
        if (!_mapped) return tl::unexpected(_mapped.error());
        _r_src2 = std::move(*_mapped);
      }
      return InstrCvt<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src), .src2 = std::move(_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrCvtPack<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrCvtPack<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrCvta<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrCvta<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrDiv<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrDiv<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrDp4a<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrDp4a<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrEx2<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrEx2<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrFma<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrFma<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrLd<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrLd<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrLg2<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrLg2<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrMad<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrMad<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrMax<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrMax<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrMembar>) {
      return InstrMembar{.data = i.data};
    } else if constexpr (std::is_same_v<T, InstrMin<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrMin<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrMov<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrMov<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrMul<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrMul<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrMul24<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrMul24<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrNanosleep<Op>>) {
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrNanosleep<NewOp>{.src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrNeg<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrNeg<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrNot<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrNot<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrOr<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrOr<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrPopc<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrPopc<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrPrmt<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrPrmt<NewOp>{.dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrRcp<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrRcp<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrRem<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrRem<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrRet>) {
      return InstrRet{.data = i.data};
    } else if constexpr (std::is_same_v<T, InstrRsqrt<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrRsqrt<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrSelp<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrSelp<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrSet<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrSet<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrSetBool<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrSetBool<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrSetp<Op>>) {
      auto _r_dst1 = visitor.visit(std::move(i.dst1), type_space, true, relaxed_type_check);
      if (!_r_dst1) return tl::unexpected(_r_dst1.error());
      std::optional<NewOp> _r_dst2;
      if (i.dst2.has_value()) {
        auto _mapped = visitor.visit(std::move(*i.dst2), type_space, true, relaxed_type_check);
        if (!_mapped) return tl::unexpected(_mapped.error());
        _r_dst2 = std::move(*_mapped);
      }
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrSetp<NewOp>{.data = i.data, .dst1 = std::move(*_r_dst1), .dst2 = std::move(_r_dst2), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrSetpBool<Op>>) {
      auto _r_dst1 = visitor.visit(std::move(i.dst1), type_space, true, relaxed_type_check);
      if (!_r_dst1) return tl::unexpected(_r_dst1.error());
      std::optional<NewOp> _r_dst2;
      if (i.dst2.has_value()) {
        auto _mapped = visitor.visit(std::move(*i.dst2), type_space, true, relaxed_type_check);
        if (!_mapped) return tl::unexpected(_mapped.error());
        _r_dst2 = std::move(*_mapped);
      }
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrSetpBool<NewOp>{.data = i.data, .dst1 = std::move(*_r_dst1), .dst2 = std::move(_r_dst2), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrShflSync<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      std::optional<NewOp> _r_dst_pred;
      if (i.dst_pred.has_value()) {
        auto _mapped = visitor.visit(std::move(*i.dst_pred), type_space, true, relaxed_type_check);
        if (!_mapped) return tl::unexpected(_mapped.error());
        _r_dst_pred = std::move(*_mapped);
      }
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      auto _r_src_lane = visitor.visit(std::move(i.src_lane), type_space, false, relaxed_type_check);
      if (!_r_src_lane) return tl::unexpected(_r_src_lane.error());
      auto _r_src_opts = visitor.visit(std::move(i.src_opts), type_space, false, relaxed_type_check);
      if (!_r_src_opts) return tl::unexpected(_r_src_opts.error());
      auto _r_src_membermask = visitor.visit(std::move(i.src_membermask), type_space, false, relaxed_type_check);
      if (!_r_src_membermask) return tl::unexpected(_r_src_membermask.error());
      return InstrShflSync<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .dst_pred = std::move(_r_dst_pred), .src = std::move(*_r_src), .src_lane = std::move(*_r_src_lane), .src_opts = std::move(*_r_src_opts), .src_membermask = std::move(*_r_src_membermask)};
    } else if constexpr (std::is_same_v<T, InstrShf<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src_a = visitor.visit(std::move(i.src_a), type_space, false, relaxed_type_check);
      if (!_r_src_a) return tl::unexpected(_r_src_a.error());
      auto _r_src_b = visitor.visit(std::move(i.src_b), type_space, false, relaxed_type_check);
      if (!_r_src_b) return tl::unexpected(_r_src_b.error());
      auto _r_src_c = visitor.visit(std::move(i.src_c), type_space, false, relaxed_type_check);
      if (!_r_src_c) return tl::unexpected(_r_src_c.error());
      return InstrShf<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src_a = std::move(*_r_src_a), .src_b = std::move(*_r_src_b), .src_c = std::move(*_r_src_c)};
    } else if constexpr (std::is_same_v<T, InstrShl<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrShl<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrShr<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrShr<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrSin<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrSin<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrSqrt<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrSqrt<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrSt<Op>>) {
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, true, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrSt<NewOp>{.data = i.data, .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrSub<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrSub<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrTrap>) {
      return InstrTrap{};
    } else if constexpr (std::is_same_v<T, InstrXor<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrXor<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrTanh<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrTanh<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrVote<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrVote<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrReduxSync<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      auto _r_src_membermask = visitor.visit(std::move(i.src_membermask), type_space, false, relaxed_type_check);
      if (!_r_src_membermask) return tl::unexpected(_r_src_membermask.error());
      return InstrReduxSync<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src), .src_membermask = std::move(*_r_src_membermask)};
    } else if constexpr (std::is_same_v<T, InstrLdMatrix<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrLdMatrix<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrGridDepControl>) {
      return InstrGridDepControl{.data = i.data};
    } else if constexpr (std::is_same_v<T, InstrMma<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrMma<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrCopysign<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      return InstrCopysign<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2)};
    } else if constexpr (std::is_same_v<T, InstrPrefetch<Op>>) {
      auto _r_src = visitor.visit(std::move(i.src), type_space, false, relaxed_type_check);
      if (!_r_src) return tl::unexpected(_r_src.error());
      return InstrPrefetch<NewOp>{.data = i.data, .src = std::move(*_r_src)};
    } else if constexpr (std::is_same_v<T, InstrSad<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrSad<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else if constexpr (std::is_same_v<T, InstrDp2a<Op>>) {
      auto _r_dst = visitor.visit(std::move(i.dst), type_space, true, relaxed_type_check);
      if (!_r_dst) return tl::unexpected(_r_dst.error());
      auto _r_src1 = visitor.visit(std::move(i.src1), type_space, false, relaxed_type_check);
      if (!_r_src1) return tl::unexpected(_r_src1.error());
      auto _r_src2 = visitor.visit(std::move(i.src2), type_space, false, relaxed_type_check);
      if (!_r_src2) return tl::unexpected(_r_src2.error());
      auto _r_src3 = visitor.visit(std::move(i.src3), type_space, false, relaxed_type_check);
      if (!_r_src3) return tl::unexpected(_r_src3.error());
      return InstrDp2a<NewOp>{.data = i.data, .dst = std::move(*_r_dst), .src1 = std::move(*_r_src1), .src2 = std::move(*_r_src2), .src3 = std::move(*_r_src3)};
    } else {
      static_assert(!std::is_same_v<T, T>, "unhandled instruction type in visit_instruction_map");
    }
  }, std::move(instr));
}

}  // namespace ptx_frontend
