include_guard(GLOBAL)

file(GLOB_RECURSE PTX_PUBLIC_INSTALL_HEADERS ${PTX_GEN_PUBLIC_DIR}/*.gen.hpp)
message(STATUS )
install(
    FILES ${PTX_PUBLIC_INSTALL_HEADERS}
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)